/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    'blog-categories': BlogCategory;
    'blog-tags': BlogTag;
    'blog-series': BlogSery;
    'blog-posts': BlogPost;
    'blog-redirects': BlogRedirect;
    'blog-ai-generation-logs': BlogAiGenerationLog;
    'blog-content-templates': BlogContentTemplate;
    'newsletter-subscribers': NewsletterSubscriber;
    projects: Project;
    'service-faqs': ServiceFaq;
    'site-content': SiteContent;
    pages: Page;
    'site-design': SiteDesign;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-tags': BlogTagsSelect<false> | BlogTagsSelect<true>;
    'blog-series': BlogSeriesSelect<false> | BlogSeriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-redirects': BlogRedirectsSelect<false> | BlogRedirectsSelect<true>;
    'blog-ai-generation-logs': BlogAiGenerationLogsSelect<false> | BlogAiGenerationLogsSelect<true>;
    'blog-content-templates': BlogContentTemplatesSelect<false> | BlogContentTemplatesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'service-faqs': ServiceFaqsSelect<false> | ServiceFaqsSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'site-design': SiteDesignSelect<false> | SiteDesignSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * CloudTopia authors and editorial profiles for article bylines and author archive pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Auto-generated from the name when empty. Used in /insights/author/[slug].
   */
  slug: string;
  name: string;
  image?: (number | null) | Media;
  role?: {
    en?: string | null;
    ar?: string | null;
  };
  /**
   * Compact author card biography.
   */
  shortBio?: string | null;
  bio?: {
    en?: string | null;
    ar?: string | null;
  };
  email?: string | null;
  /**
   * Show this author on public article and author archive pages.
   */
  showProfile?: boolean | null;
  expertise?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  knowsAbout?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  linkedinUrl?: string | null;
  xUrl?: string | null;
  websiteUrl?: string | null;
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  authorSEO?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Editorial topics for CloudTopia Insights. Categories power filters, archive pages, and article badges.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  /**
   * Use English for the main /insights route. Arabic power localized archive pages.
   */
  locale: 'en' | 'ar';
  name: string;
  /**
   * Auto-generated from the name when empty. Used in /insights/category/[slug].
   */
  slug: string;
  /**
   * Short archive-page description and SEO fallback.
   */
  description?: string | null;
  /**
   * Compact category-card copy.
   */
  shortDescription?: string | null;
  /**
   * Optional category visual for archive and category cards.
   */
  image?: (number | null) | Media;
  /**
   * Optional icon keyword, for example "cloud", "automation", or "ai".
   */
  icon?: string | null;
  /**
   * Optional accent color used for subtle UI details.
   */
  color?: string | null;
  /**
   * Optional flat SEO title for editors who prefer quick fields. The SEO group below remains the canonical metadata source.
   */
  seoTitle?: string | null;
  seoDescription?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Optional parent topic for future nested navigation.
   */
  parentCategory?: (number | null) | BlogCategory;
  /**
   * Lower numbers appear first in category lists.
   */
  order?: number | null;
  /**
   * Featured categories appear in the Insights hub topic section.
   */
  featured?: boolean | null;
  /**
   * Show this topic in Insights filters and topic navigation.
   */
  showInNavigation?: boolean | null;
  categoryCTA?: {
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  relatedServices?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Small topical labels used for article discovery and tag archive pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags".
 */
export interface BlogTag {
  id: number;
  /**
   * Match the post locale that should use this tag.
   */
  locale: 'en' | 'ar';
  name: string;
  /**
   * Auto-generated from the name when empty. Used in /insights/tag/[slug].
   */
  slug: string;
  /**
   * Optional tag archive description and SEO fallback.
   */
  description?: string | null;
  color?: string | null;
  featured?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Multi-part CloudTopia guide series for deep editorial programs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-series".
 */
export interface BlogSery {
  id: number;
  title: string;
  /**
   * Used for series URLs and article series boxes.
   */
  slug: string;
  description?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Order these manually to create previous/next reading paths.
   */
  posts?: (number | BlogPost)[] | null;
  order?: number | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * CloudTopia Insights editorial dashboard. Drafts stay private; published posts appear on /insights.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * English posts appear on /insights. Arabic use prefixed locale routes.
   */
  locale: 'en' | 'ar';
  /**
   * Workflow: idea -> outline -> draft -> in review -> scheduled -> published.
   */
  status: 'idea' | 'outline' | 'draft' | 'in_review' | 'scheduled' | 'published' | 'archived';
  approvalStatus?: ('not_required' | 'waiting' | 'approved' | 'rejected') | null;
  title: string;
  /**
   * Auto-generated from the title when empty. Editable for SEO-safe URLs.
   */
  slug: string;
  subtitle?: string | null;
  /**
   * Main summary for cards, article hero, metadata fallbacks, and search results.
   */
  excerpt: string;
  /**
   * Very short card or featured-strip teaser.
   */
  shortExcerpt?: string | null;
  featured?: boolean | null;
  pinned?: boolean | null;
  editorPick?: boolean | null;
  trending?: boolean | null;
  publishedAt?: string | null;
  scheduledAt?: string | null;
  lastReviewedAt?: string | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  contentType?:
    | ('guide' | 'article' | 'case_study' | 'checklist' | 'comparison' | 'tutorial' | 'opinion' | 'news')
    | null;
  targetAudience?:
    | (
        | 'startups'
        | 'small_businesses'
        | 'medium_businesses'
        | 'real_estate'
        | 'clinics'
        | 'ecommerce'
        | 'service_companies'
        | 'founders'
        | 'developers'
      )
    | null;
  serviceFocus?:
    | (
        | 'websites'
        | 'web_apps'
        | 'crm'
        | 'erp'
        | 'automation'
        | 'ai'
        | 'cloud'
        | 'digital_presence'
        | 'business_systems'
      )
    | null;
  readingTime?: number | null;
  wordCount?: number | null;
  contentScore?: number | null;
  seoScore?: number | null;
  /**
   * Use headings, lists, quotes, images, tables, and code blocks to structure the core article.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Structured premium article sections rendered after the rich text body.
   */
  contentBlocks?:
    | (
        | {
            type?: ('info' | 'warning' | 'success' | 'tip' | 'cloudtopia-note') | null;
            title?: string | null;
            content?: string | null;
            icon?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBlock';
          }
        | {
            title: string;
            description?: string | null;
            buttonText?: string | null;
            buttonUrl?: string | null;
            style?: ('light' | 'azure' | 'dark' | 'gradient') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaInlineBlock';
          }
        | {
            question: string;
            answer: string;
            /**
             * Include this question in FAQPage JSON-LD when the article enables FAQ schema.
             */
            includeInSchema?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            title?: string | null;
            rows?:
              | {
                  feature: string;
                  optionA?: string | null;
                  optionB?: string | null;
                  winner?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparisonTableBlock';
          }
        | {
            pros?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            cons?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prosConsBlock';
          }
        | {
            title?: string | null;
            steps?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepProcessBlock';
          }
        | {
            service?: string | null;
            title: string;
            description?: string | null;
            buttonText?: string | null;
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicePromoBlock';
          }
        | {
            posts?: (number | BlogPost)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedPostsManualBlock';
          }
        | {
            statNumber: string;
            statLabel: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statBlock';
          }
        | {
            image: number | Media;
            alt: string;
            caption?: string | null;
            layout?: ('full' | 'wide' | 'normal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageWithCaptionBlock';
          }
        | {
            language?: string | null;
            filename?: string | null;
            code: string;
            explanation?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeSnippetBlock';
          }
        | {
            title: string;
            description?: string | null;
            file?: (number | null) | Media;
            buttonText?: string | null;
            emailRequired?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadMagnetBlock';
          }
      )[]
    | null;
  /**
   * Primary image used across cards, article hero, Open Graph fallbacks, and sitemap images.
   */
  coverImage: number | Media;
  /**
   * Accessible image alt text. Required by the content score.
   */
  featuredImageAlt?: string | null;
  socialImage?: (number | null) | Media;
  leadMagnetFile?: (number | null) | Media;
  seo?: {
    /**
     * Recommended length: 45-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    focusKeyword?: string | null;
    secondaryKeywords?: string | null;
    keywords?: string | null;
    canonicalUrl?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | Media;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    structuredDataType?: ('BlogPosting' | 'Article' | 'TechArticle' | 'HowTo' | 'FAQPage') | null;
    faqSchema?: boolean | null;
    breadcrumbSchema?: boolean | null;
    articleSchema?: boolean | null;
    lastModifiedSchema?: boolean | null;
  };
  aiGenerated?: boolean | null;
  aiAssisted?: boolean | null;
  readabilityScore?: number | null;
  estimatedRankingDifficulty?: number | null;
  searchIntent?: ('informational' | 'commercial' | 'transactional' | 'navigational') | null;
  funnelStage?: ('awareness' | 'consideration' | 'conversion' | 'retention') | null;
  internalLinksSuggestions?:
    | {
        label?: string | null;
        url: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  externalSources?:
    | {
        title?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        label?: string | null;
        url?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  factChecked?: boolean | null;
  factCheckedBy?: (number | null) | User;
  factCheckedAt?: string | null;
  assignedTo?: (number | null) | User;
  reviewer?: (number | null) | User;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  editorNotes?: string | null;
  privateNotes?: string | null;
  revisionNotes?: string | null;
  linkedinPost?: string | null;
  instagramCaption?: string | null;
  xPost?: string | null;
  whatsappMessage?: string | null;
  emailNewsletterIntro?: string | null;
  socialStatus?: ('not_prepared' | 'prepared' | 'scheduled' | 'published') | null;
  showCTA?: boolean | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaButtonText?: string | null;
  ctaButtonUrl?: string | null;
  secondaryCTAButtonText?: string | null;
  secondaryCTAButtonUrl?: string | null;
  leadMagnetTitle?: string | null;
  newsletterPlacement?: ('none' | 'after_intro' | 'middle' | 'end' | 'sidebar') | null;
  primaryCTA?: ('start_project' | 'talk_to_cloudtopia' | 'view_services' | 'book_consultation') | null;
  relatedServices?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  viewsCount?: number | null;
  uniqueViewsCount?: number | null;
  averageReadTime?: number | null;
  conversionClicks?: number | null;
  newsletterSignups?: number | null;
  lastViewedAt?: string | null;
  /**
   * Primary topic for filters, badges, archive pages, and related-post matching.
   */
  category: number | BlogCategory;
  /**
   * Optional discovery tags. Keep them focused and reusable.
   */
  tags?: (number | BlogTag)[] | null;
  /**
   * Primary byline author.
   */
  author: number | Author;
  coAuthors?: (number | Author)[] | null;
  series?: (number | null) | BlogSery;
  /**
   * Show a sticky article table of contents when headings exist.
   */
  tableOfContents?: boolean | null;
  /**
   * Optional manual related posts. Otherwise the frontend uses same-category and same-tag articles.
   */
  relatedPosts?: (number | BlogPost)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Managed legacy blog redirects for old URLs and campaign links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-redirects".
 */
export interface BlogRedirect {
  id: number;
  /**
   * Old path, for example /blog/old-post.
   */
  fromPath: string;
  /**
   * New destination, for example /insights/new-post.
   */
  toPath: string;
  statusCode: '301' | '302';
  active?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit log for AI writing assistant requests. Outputs are stored as previews only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-ai-generation-logs".
 */
export interface BlogAiGenerationLog {
  id: number;
  promptType:
    | 'idea'
    | 'outline'
    | 'title'
    | 'excerpt'
    | 'intro'
    | 'rewrite'
    | 'faq'
    | 'seo'
    | 'social'
    | 'cta'
    | 'analyze'
    | 'translate';
  sourcePost?: (number | null) | BlogPost;
  user?: (number | null) | User;
  userEmail?: string | null;
  provider?: string | null;
  model?: string | null;
  inputPreview?: string | null;
  outputPreview?: string | null;
  status?: ('success' | 'error') | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable article templates for CloudTopia editorial planning.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-content-templates".
 */
export interface BlogContentTemplate {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  contentType?:
    | ('guide' | 'article' | 'case_study' | 'checklist' | 'comparison' | 'tutorial' | 'opinion' | 'news')
    | null;
  defaultOutline?: string | null;
  recommendedBlocks?:
    | {
        blockType: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  defaultCTA?: {
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  seoChecklist?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  targetAudience?:
    | (
        | 'startups'
        | 'small_businesses'
        | 'medium_businesses'
        | 'real_estate'
        | 'clinics'
        | 'ecommerce'
        | 'service_companies'
        | 'founders'
        | 'developers'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subscribers captured from the Insights newsletter form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  name?: string | null;
  /**
   * Where the subscriber came from. The Insights form sends "insights".
   */
  source?: string | null;
  /**
   * Optional topics selected from the Insights form.
   */
  interests?:
    | {
        interest: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tracks that the subscriber consented to receive CloudTopia insights.
   */
  consent?: boolean | null;
  locale?: ('en' | 'ar') | null;
  utmSource?: string | null;
  utmCampaign?: string | null;
  subscribedAt?: string | null;
  status: 'active' | 'unsubscribed' | 'bounced';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  locale: 'en' | 'ar';
  /**
   * Auto-generated in the format locale:project-id when left empty.
   */
  cmsKey?: string | null;
  /**
   * Auto-generated from locale and title when left empty.
   */
  id: string;
  category: string;
  type: string;
  featured?: boolean | null;
  title: string;
  problem: string;
  solution: string;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Fallback public image URL. Choosing Project Media below fills this automatically.
   */
  image?: string | null;
  /**
   * Upload or choose a project image. Payload stores it in Media and the public site uses its URL.
   */
  imageMedia?: (number | null) | Media;
  metrics?: {
    label?: string | null;
    value?: string | null;
  };
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-faqs".
 */
export interface ServiceFaq {
  id: number;
  serviceSlug: string;
  faqs?: {
    en?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
    ar?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  locale: 'en' | 'ar';
  /**
   * Full structured site dictionary for this locale. Seeded from the existing translation files.
   */
  dictionary:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Structured public page controls. Hero and CTA fields sync back into the live locale dictionary on save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  locale: 'en' | 'ar';
  /**
   * Route path without locale, for example "/", "services", or "website-design".
   */
  slug: string;
  title: string;
  /**
   * Controls how the public route interprets the structured sections below.
   */
  template:
    | 'home'
    | 'services'
    | 'service-detail'
    | 'projects'
    | 'about'
    | 'contact'
    | 'labs'
    | 'legal'
    | 'blog-coming-soon'
    | 'content';
  /**
   * Preview path generated from locale and slug.
   */
  publicPath?: string | null;
  status: 'draft' | 'published';
  /**
   * Primary visible hero copy for this route. Saving this page updates the live locale dictionary.
   */
  hero?: {
    badge?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    description?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  /**
   * Default call-to-action used by the route and editorial previews.
   */
  cta?: {
    label?: string | null;
    href?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  /**
   * SEO title, description, OG settings, schema notes, and canonical controls.
   */
  seo:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Structured section payload for this route. This must contain real section data, never placeholder instructions.
   */
  sections:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Per-page layout and visual overrides.
   */
  design:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes for editors. Not rendered publicly.
   */
  editorNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Global design, navigation, footer, and brand controls for the public website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-design".
 */
export interface SiteDesign {
  id: number;
  /**
   * Use "default" for the active public website design settings.
   */
  key: string;
  /**
   * Brand identity used by the header, footer, metadata helpers, and admin previews.
   */
  brand: {
    name: string;
    tagline: string;
    logo: string;
  };
  /**
   * Public CSS variables and dashboard color tokens.
   */
  colors: {
    dark: string;
    primary: string;
    secondary: string;
    background: string;
  };
  typography: {
    heading: string;
    body: string;
    logo: string;
  };
  radius: {
    card: number;
    control: number;
  };
  motion?: {
    enabled?: boolean | null;
    intensity?: ('quiet' | 'standard' | 'expressive') | null;
  };
  /**
   * Header CTA button used across locales unless a page overrides it.
   */
  cta: {
    label: string;
    href: string;
  };
  /**
   * Header link labels for the default English navigation model.
   */
  navigationLabels: {
    home: string;
    services: string;
    projects: string;
    labs: string;
    about: string;
    blog: string;
    contact: string;
  };
  footer: {
    description: string;
    copyright: string;
  };
  contact: {
    email: string;
    phone: string;
    whatsapp: string;
  };
  social?: {
    whatsapp?: string | null;
    x?: string | null;
    github?: string | null;
    instagram?: string | null;
  };
  /**
   * Generated from the structured fields above. Hidden from editors.
   */
  theme?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Generated from the structured fields above. Hidden from editors.
   */
  navigation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Advanced section visibility controls. Keep this JSON unless you are intentionally hiding public sections.
   */
  editableSections:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  image?: T;
  role?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  shortBio?: T;
  bio?:
    | T
    | {
        en?: T;
        ar?: T;
      };
  email?: T;
  showProfile?: T;
  expertise?:
    | T
    | {
        area?: T;
        id?: T;
      };
  knowsAbout?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  linkedinUrl?: T;
  xUrl?: T;
  websiteUrl?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  authorSEO?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  locale?: T;
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  icon?: T;
  color?: T;
  seoTitle?: T;
  seoDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  parentCategory?: T;
  order?: T;
  featured?: T;
  showInNavigation?: T;
  categoryCTA?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  relatedServices?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags_select".
 */
export interface BlogTagsSelect<T extends boolean = true> {
  locale?: T;
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  featured?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-series_select".
 */
export interface BlogSeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  posts?: T;
  order?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  locale?: T;
  status?: T;
  approvalStatus?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  excerpt?: T;
  shortExcerpt?: T;
  featured?: T;
  pinned?: T;
  editorPick?: T;
  trending?: T;
  publishedAt?: T;
  scheduledAt?: T;
  lastReviewedAt?: T;
  difficulty?: T;
  contentType?: T;
  targetAudience?: T;
  serviceFocus?: T;
  readingTime?: T;
  wordCount?: T;
  contentScore?: T;
  seoScore?: T;
  content?: T;
  contentBlocks?:
    | T
    | {
        calloutBlock?:
          | T
          | {
              type?: T;
              title?: T;
              content?: T;
              icon?: T;
              id?: T;
              blockName?: T;
            };
        ctaInlineBlock?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              question?: T;
              answer?: T;
              includeInSchema?: T;
              id?: T;
              blockName?: T;
            };
        comparisonTableBlock?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    feature?: T;
                    optionA?: T;
                    optionB?: T;
                    winner?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        prosConsBlock?:
          | T
          | {
              pros?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              cons?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepProcessBlock?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicePromoBlock?:
          | T
          | {
              service?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        relatedPostsManualBlock?:
          | T
          | {
              posts?: T;
              id?: T;
              blockName?: T;
            };
        statBlock?:
          | T
          | {
              statNumber?: T;
              statLabel?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        imageWithCaptionBlock?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        codeSnippetBlock?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              explanation?: T;
              id?: T;
              blockName?: T;
            };
        leadMagnetBlock?:
          | T
          | {
              title?: T;
              description?: T;
              file?: T;
              buttonText?: T;
              emailRequired?: T;
              id?: T;
              blockName?: T;
            };
      };
  coverImage?: T;
  featuredImageAlt?: T;
  socialImage?: T;
  leadMagnetFile?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        focusKeyword?: T;
        secondaryKeywords?: T;
        keywords?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        noIndex?: T;
        noFollow?: T;
        structuredDataType?: T;
        faqSchema?: T;
        breadcrumbSchema?: T;
        articleSchema?: T;
        lastModifiedSchema?: T;
      };
  aiGenerated?: T;
  aiAssisted?: T;
  readabilityScore?: T;
  estimatedRankingDifficulty?: T;
  searchIntent?: T;
  funnelStage?: T;
  internalLinksSuggestions?:
    | T
    | {
        label?: T;
        url?: T;
        reason?: T;
        id?: T;
      };
  externalSources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  references?:
    | T
    | {
        label?: T;
        url?: T;
        note?: T;
        id?: T;
      };
  factChecked?: T;
  factCheckedBy?: T;
  factCheckedAt?: T;
  assignedTo?: T;
  reviewer?: T;
  approvedBy?: T;
  approvedAt?: T;
  editorNotes?: T;
  privateNotes?: T;
  revisionNotes?: T;
  linkedinPost?: T;
  instagramCaption?: T;
  xPost?: T;
  whatsappMessage?: T;
  emailNewsletterIntro?: T;
  socialStatus?: T;
  showCTA?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  ctaButtonText?: T;
  ctaButtonUrl?: T;
  secondaryCTAButtonText?: T;
  secondaryCTAButtonUrl?: T;
  leadMagnetTitle?: T;
  newsletterPlacement?: T;
  primaryCTA?: T;
  relatedServices?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  viewsCount?: T;
  uniqueViewsCount?: T;
  averageReadTime?: T;
  conversionClicks?: T;
  newsletterSignups?: T;
  lastViewedAt?: T;
  category?: T;
  tags?: T;
  author?: T;
  coAuthors?: T;
  series?: T;
  tableOfContents?: T;
  relatedPosts?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-redirects_select".
 */
export interface BlogRedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  statusCode?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-ai-generation-logs_select".
 */
export interface BlogAiGenerationLogsSelect<T extends boolean = true> {
  promptType?: T;
  sourcePost?: T;
  user?: T;
  userEmail?: T;
  provider?: T;
  model?: T;
  inputPreview?: T;
  outputPreview?: T;
  status?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-content-templates_select".
 */
export interface BlogContentTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  contentType?: T;
  defaultOutline?: T;
  recommendedBlocks?:
    | T
    | {
        blockType?: T;
        notes?: T;
        id?: T;
      };
  defaultCTA?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  seoChecklist?:
    | T
    | {
        item?: T;
        id?: T;
      };
  targetAudience?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  source?: T;
  interests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  consent?: T;
  locale?: T;
  utmSource?: T;
  utmCampaign?: T;
  subscribedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  locale?: T;
  cmsKey?: T;
  id?: T;
  category?: T;
  type?: T;
  featured?: T;
  title?: T;
  problem?: T;
  solution?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  image?: T;
  imageMedia?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
      };
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-faqs_select".
 */
export interface ServiceFaqsSelect<T extends boolean = true> {
  serviceSlug?: T;
  faqs?:
    | T
    | {
        en?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
        ar?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  locale?: T;
  dictionary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  locale?: T;
  slug?: T;
  title?: T;
  template?: T;
  publicPath?: T;
  status?: T;
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  seo?: T;
  sections?: T;
  design?: T;
  editorNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-design_select".
 */
export interface SiteDesignSelect<T extends boolean = true> {
  key?: T;
  brand?:
    | T
    | {
        name?: T;
        tagline?: T;
        logo?: T;
      };
  colors?:
    | T
    | {
        dark?: T;
        primary?: T;
        secondary?: T;
        background?: T;
      };
  typography?:
    | T
    | {
        heading?: T;
        body?: T;
        logo?: T;
      };
  radius?:
    | T
    | {
        card?: T;
        control?: T;
      };
  motion?:
    | T
    | {
        enabled?: T;
        intensity?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  navigationLabels?:
    | T
    | {
        home?: T;
        services?: T;
        projects?: T;
        labs?: T;
        about?: T;
        blog?: T;
        contact?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        copyright?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
      };
  social?:
    | T
    | {
        whatsapp?: T;
        x?: T;
        github?: T;
        instagram?: T;
      };
  theme?: T;
  navigation?: T;
  editableSections?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
