// AUTO-GENERATED by scripts/generate-subservice-nav-index.ts — do not edit by hand.
// Regenerate with: npm run generate:service-nav
import type { Locale } from '@/lib/i18n/config'

export type SubserviceNavItem = { slug: string; name: string; description?: string; href: string }

const INDEX: Record<string, { en: SubserviceNavItem[]; ar: SubserviceNavItem[] }> = {
  "application-modernization-performance": {
    "en": [
      {
        "slug": "legacy-application-refactoring-and-rewrites",
        "name": "Legacy Application Refactoring & Rewrites",
        "description": "Untangle brittle code so your app is safe and cheap to evolve again.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "monolith-to-microservices-migration",
        "name": "Monolith to Microservices Migration",
        "description": "Break a tangled monolith into well-bounded services so it scales by part, not all at once.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "web-app-speed-and-core-web-vitals-optimization",
        "name": "Web App Speed & Core Web Vitals Optimization",
        "description": "Fix the real bottlenecks — queries, bundles, caching, images — to pass Core Web Vitals.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "end-to-end-automated-testing-and-qa",
        "name": "End-to-End Automated Testing & QA",
        "description": "Automated tests close the gaps that cause outages, regressions, and broken releases.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "security-auditing-and-vulnerability-patching",
        "name": "Security Auditing & Vulnerability Patching",
        "description": "Audit, patch known vulnerabilities, and update risky dependencies so the gaps stay closed.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "deployment-pipelines-and-24-7-monitoring",
        "name": "Deployment Pipelines & 24/7 Monitoring",
        "description": "CI/CD releases and round-the-clock monitoring catch problems before your users do.",
        "href": "/services/web-applications/application-modernization-performance"
      }
    ],
    "ar": [
      {
        "slug": "legacy-application-refactoring-and-rewrites",
        "name": "إعادة هيكلة وإعادة كتابة التطبيقات القديمة",
        "description": "نفكّ الكود الهشّ ليعود تطبيقك آمناً ورخيص التطوير من جديد.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "monolith-to-microservices-migration",
        "name": "الترحيل من نظام متجانس إلى microservices",
        "description": "نقسّم النظام المتجانس المتشابك إلى خدمات محدودة النطاق ليتوسّع بالجزء لا دفعة واحدة.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "web-app-speed-and-core-web-vitals-optimization",
        "name": "تحسين سرعة تطبيق الويب وCore Web Vitals",
        "description": "نُصلح الاختناقات الحقيقية — الاستعلامات والحزم والتخزين المؤقت والصور — لاجتياز Core Web Vitals.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "end-to-end-automated-testing-and-qa",
        "name": "اختبار آلي شامل وضمان جودة",
        "description": "اختبارات آلية تُغلق الفجوات التي تسبّب الأعطال والانحدارات والإصدارات المكسورة.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "security-auditing-and-vulnerability-patching",
        "name": "تدقيق أمني وترقيع الثغرات",
        "description": "نُدقّق ونرقّع الثغرات المعروفة ونحدّث الاعتماديات الخطرة لتبقى الفجوات مغلقة.",
        "href": "/services/web-applications/application-modernization-performance"
      },
      {
        "slug": "deployment-pipelines-and-24-7-monitoring",
        "name": "خطوط النشر والمراقبة 24/7",
        "description": "إصدارات CI/CD ومراقبة على مدار الساعة تلتقط المشكلات قبل مستخدميك.",
        "href": "/services/web-applications/application-modernization-performance"
      }
    ]
  },
  "business-management-systems": {
    "en": [
      {
        "slug": "inventory-management-systems",
        "name": "Inventory Management Systems",
        "description": "Stop guessing what you have, what it cost, and what to reorder. We build an inventory system around your actual products, units, and suppliers — so every item, value, and movement stays accurate and yours to control.",
        "href": "/services/business-management-systems/inventory-management-systems"
      },
      {
        "slug": "hr-management-systems",
        "name": "HR Management Systems",
        "description": "One internal system that holds every employee record, runs leave and attendance, and routes approvals the way your company actually works. Built around your policies, bilingual in Arabic and English, and fully owned by you — no per-seat licence to renew.",
        "href": "/services/business-management-systems/hr-management-systems"
      },
      {
        "slug": "sales-management-systems",
        "name": "Sales Management Systems",
        "description": "Run your entire sales operation from one system built around how your team actually sells — accounts, territories, targets, daily activity, and order handoff all in one place. Your managers get a true picture of performance, and your team owns every line of the code and data.",
        "href": "/services/business-management-systems/sales-management-systems"
      },
      {
        "slug": "order-management-systems",
        "name": "Order Management Systems",
        "description": "Run every order from one place — captured from any channel, checked against stock, invoiced, and tracked from confirmed to delivered. We build the order workflow around how your business actually sells, and you own all of it.",
        "href": "/services/business-management-systems/order-management-systems"
      }
    ],
    "ar": [
      {
        "slug": "inventory-management-systems",
        "name": "أنظمة إدارة المخزون",
        "description": "توقّف عن تخمين ما لديك وكم كلّف وما يجب إعادة طلبه. نبني نظام مخزون حول منتجاتك ووحداتك ومورّديك الفعليين — فيبقى كل صنف وقيمة وحركة دقيقاً وتحت سيطرتك.",
        "href": "/services/business-management-systems/inventory-management-systems"
      },
      {
        "slug": "hr-management-systems",
        "name": "أنظمة إدارة الموارد البشرية",
        "description": "نظام داخلي واحد يضم كل سجل موظف، ويدير الإجازات والحضور، ويوجّه الاعتمادات بالطريقة التي تعمل بها شركتك فعلياً. مبني حول سياساتك، ثنائي اللغة بالعربية والإنجليزية، ومملوك لك بالكامل — دون رخصة لكل مستخدم تتجدد.",
        "href": "/services/business-management-systems/hr-management-systems"
      },
      {
        "slug": "sales-management-systems",
        "name": "أنظمة إدارة المبيعات",
        "description": "أدِر عملياتك البيعية بالكامل من نظام واحد مصمم حول طريقة عمل فريقك — الحسابات والمناطق والأهداف والنشاط اليومي وتسليم الطلبات في مكان واحد. يحصل مديروك على صورة حقيقية للأداء، وفريقك يمتلك كل سطر من الكود والبيانات.",
        "href": "/services/business-management-systems/sales-management-systems"
      },
      {
        "slug": "order-management-systems",
        "name": "أنظمة إدارة الطلبات",
        "description": "أدِر كل طلب من مكان واحد — يُلتقط من أي قناة، ويُفحص مقابل المخزون، ويُفوتَر، ويُتابَع من التأكيد إلى التسليم. نبني سير عمل الطلبات حول طريقة بيع عملك فعلياً، وأنت تملكه كاملاً.",
        "href": "/services/business-management-systems/order-management-systems"
      }
    ]
  },
  "business-process-automation": {
    "en": [
      {
        "slug": "workflow-automation",
        "name": "Workflow Automation",
        "description": "Turn the repetitive, multi-step work your team does by hand into automation that runs itself. We map a real process end to end, then build the triggers, rules, and handoffs that move it forward without anyone copying data between apps or chasing the next step.",
        "href": "/services/business-process-automation/workflow-automation"
      },
      {
        "slug": "automated-invoicing-payment-reminders",
        "name": "Automated Invoicing & Payment Reminder Workflows",
        "description": "Stop chasing payments by hand. We build a workflow that raises invoices automatically, sends polite WhatsApp and email reminders on your schedule, and goes quiet the moment a client pays.",
        "href": "/services/business-process-automation/automated-invoicing-payment-reminders"
      },
      {
        "slug": "whatsapp-crm-lead-capture",
        "name": "WhatsApp-to-CRM Lead Capture & Routing Setup",
        "description": "We connect your WhatsApp Business line straight into your CRM, so every enquiry becomes a tracked lead and lands with the right rep within seconds — no message left on read, no deal lost in a shared inbox.",
        "href": "/services/business-process-automation/whatsapp-crm-lead-capture"
      },
      {
        "slug": "accounting-system-integration",
        "name": "Accounting System Integration",
        "description": "Stop typing the same sale, expense, and payment into your books by hand. We wire your sales, payroll, inventory, and bank feeds straight into your accounting software so entries post themselves, VAT stays clean, and month-end stops being a scramble.",
        "href": "/services/business-process-automation/accounting-system-integration"
      },
      {
        "slug": "cross-platform-api-integration",
        "name": "Cross-Platform API Syncing (Website, CRM & Accounting)",
        "description": "Stop copying the same order, contact, and invoice between three systems. We wire your website, CRM, and accounting together so every record updates itself the moment something changes — and you own the integration end to end.",
        "href": "/services/business-process-automation/cross-platform-api-integration"
      },
      {
        "slug": "custom-api-development",
        "name": "Custom API Development & Integration",
        "description": "We build the APIs that let your software, your partners, and the apps you already pay for talk to each other — and we connect to almost any third-party or government service that exposes one. You own every endpoint, every key, and every line of code.",
        "href": "/services/business-process-automation/custom-api-development"
      },
      {
        "slug": "automated-proposal-quotation-generation",
        "name": "Automated Proposal, Quotation & PDF Generation",
        "description": "Turn enquiries into branded, error-free quotes and proposals in minutes, generated as polished PDFs straight from your own data. Built around your pricing, your templates, and your approval rules, in Arabic and English.",
        "href": "/services/business-process-automation/automated-proposal-quotation-generation"
      },
      {
        "slug": "sales-followup-drip-automation",
        "name": "Sales Follow-Up & Drip Campaign Automation",
        "description": "Stop losing deals to slow or forgotten follow-up. We build automation that chases every new lead on WhatsApp and email, nurtures the ones who go quiet, and hands your reps only the prospects ready to talk.",
        "href": "/services/business-process-automation/sales-followup-drip-automation"
      },
      {
        "slug": "esignature-contract-management",
        "name": "E-Signature & Contract Management Automation",
        "description": "Send, sign, and track contracts in hours instead of days, with bilingual signing pages and audit-ready records that hold up in a dispute. Built around your approval flow and owned entirely by you.",
        "href": "/services/business-process-automation/esignature-contract-management"
      },
      {
        "slug": "employee-onboarding-automation",
        "name": "Automated Employee Onboarding & Offboarding Flows",
        "description": "Turn every new hire and exit into a single triggered workflow that creates accounts, grants the right access, chases signatures, and notifies every department on time. When someone leaves, the same flow revokes access the moment it should, so nothing slips through.",
        "href": "/services/business-process-automation/employee-onboarding-automation"
      },
      {
        "slug": "purchase-order-approval-workflows",
        "name": "Purchase Order & Manager Approval Workflows",
        "description": "Replace email chains and paper sign-offs with a structured PO system that routes every request to the right approver, enforces your spending limits, and keeps a clean audit trail. Faster approvals, controlled spend, and a workflow your team fully owns.",
        "href": "/services/business-process-automation/purchase-order-approval-workflows"
      }
    ],
    "ar": [
      {
        "slug": "workflow-automation",
        "name": "أتمتة سير العمل",
        "description": "حوّل العمل المتكرر متعدد الخطوات الذي يؤديه فريقك يدوياً إلى أتمتة تُدير نفسها. نرسم عملية حقيقية من أولها لآخرها، ثم نبني المشغّلات والقواعد والتسليمات التي تدفعها إلى الأمام دون أن ينسخ أحد بيانات بين التطبيقات أو يطارد الخطوة التالية.",
        "href": "/services/business-process-automation/workflow-automation"
      },
      {
        "slug": "automated-invoicing-payment-reminders",
        "name": "أتمتة الفوترة وسير عمل تذكيرات السداد",
        "description": "توقّف عن ملاحقة المدفوعات يدوياً. نبني سير عمل يُصدر الفواتير تلقائياً، ويرسل تذكيرات مهذبة عبر واتساب والبريد وفق جدولك، ويصمت في اللحظة التي يسدّد فيها العميل.",
        "href": "/services/business-process-automation/automated-invoicing-payment-reminders"
      },
      {
        "slug": "whatsapp-crm-lead-capture",
        "name": "إعداد استقطاب العملاء وتوجيههم من واتساب إلى CRM",
        "description": "نربط خط واتساب بزنس الخاص بك مباشرةً بـ CRM، فيصبح كل استفسار عميلاً محتملاً مُتتبَّعاً يصل إلى المندوب المناسب في ثوانٍ — لا رسالة تُتجاهل، ولا صفقة تضيع في بريد وارد مشترك.",
        "href": "/services/business-process-automation/whatsapp-crm-lead-capture"
      },
      {
        "slug": "accounting-system-integration",
        "name": "تكامل نظام المحاسبة",
        "description": "توقّف عن إدخال المبيعة والمصروف والدفعة نفسها يدوياً في دفاترك. نربط مبيعاتك ورواتبك ومخزونك وحساباتك البنكية مباشرةً ببرنامج المحاسبة لديك، فتُرحَّل القيود تلقائياً، وتبقى ضريبة القيمة المضافة دقيقة، ويتوقف الإقفال الشهري عن كونه سباقاً مرهقاً.",
        "href": "/services/business-process-automation/accounting-system-integration"
      },
      {
        "slug": "cross-platform-api-integration",
        "name": "مزامنة الأنظمة عبر الـ API (الموقع والـ CRM والمحاسبة)",
        "description": "توقّف عن نسخ الطلب وجهة الاتصال والفاتورة نفسها بين ثلاثة أنظمة. نربط موقعك ونظام CRM والمحاسبة معاً، فيُحدّث كل سجل نفسه لحظة تغيّر أي شيء — وأنت تملك التكامل من طرف إلى طرف.",
        "href": "/services/business-process-automation/cross-platform-api-integration"
      },
      {
        "slug": "custom-api-development",
        "name": "تطوير وتكامل واجهات API مخصصة",
        "description": "نبني واجهات API التي تتيح لبرمجياتك وشركائك والتطبيقات التي تدفع مقابلها أن تتحدث معاً — ونتكامل مع أي خدمة طرف ثالث أو خدمة حكومية توفّر واجهة. أنت تملك كل نقطة وصول وكل مفتاح وكل سطر برمجي.",
        "href": "/services/business-process-automation/custom-api-development"
      },
      {
        "slug": "automated-proposal-quotation-generation",
        "name": "أتمتة توليد العروض الفنية وعروض الأسعار بصيغة PDF",
        "description": "حوّل الاستفسارات إلى عروض أسعار وعروض فنية احترافية خالية من الأخطاء في دقائق، تُولَّد كملفات PDF أنيقة من بياناتك مباشرةً. مبنية حول أسعارك وقوالبك وقواعد اعتمادك، بالعربية والإنجليزية.",
        "href": "/services/business-process-automation/automated-proposal-quotation-generation"
      },
      {
        "slug": "sales-followup-drip-automation",
        "name": "أتمتة متابعة المبيعات وحملات التنقيط",
        "description": "توقف عن خسارة الصفقات بسبب المتابعة البطيئة أو المنسية. نبني لك أتمتة تلاحق كل عميل محتمل جديد عبر واتساب والبريد الإلكتروني، وترعى من يختفي، ولا تسلّم مندوبيك إلا المشترين الجاهزين للحديث.",
        "href": "/services/business-process-automation/sales-followup-drip-automation"
      },
      {
        "slug": "esignature-contract-management",
        "name": "أتمتة التوقيع الإلكتروني وإدارة العقود",
        "description": "أرسل العقود ووقّعها وتابعها في ساعات بدل أيام، بصفحات توقيع ثنائية اللغة وسجلات جاهزة للتدقيق تصمد أمام أي نزاع. مبنية حول مسار اعتمادك ومملوكة لك بالكامل.",
        "href": "/services/business-process-automation/esignature-contract-management"
      },
      {
        "slug": "employee-onboarding-automation",
        "name": "أتمتة مسارات تعيين الموظفين وإنهاء خدمتهم",
        "description": "حوّل كل تعيين ومغادرة إلى سير عمل واحد يُنشئ الحسابات، ويمنح الصلاحيات المناسبة، ويلاحق التواقيع، ويُبلّغ كل قسم في وقته. وعند مغادرة أحدهم، يُلغي المسار نفسه الوصول في اللحظة المناسبة، فلا يفلت شيء.",
        "href": "/services/business-process-automation/employee-onboarding-automation"
      },
      {
        "slug": "purchase-order-approval-workflows",
        "name": "سير عمل أوامر الشراء واعتماد المديرين",
        "description": "استبدل سلاسل البريد والتواقيع الورقية بنظام أوامر شراء منظّم يوجّه كل طلب إلى المعتمِد المناسب، ويفرض حدود الإنفاق، ويحتفظ بسجل تدقيق نظيف. اعتمادات أسرع، وإنفاق منضبط، وسير عمل يملكه فريقك بالكامل.",
        "href": "/services/business-process-automation/purchase-order-approval-workflows"
      }
    ]
  },
  "content-marketing-authority": {
    "en": [
      {
        "slug": "seo-blog-post-and-article-writing",
        "name": "SEO Blog Post & Article Writing",
        "description": "Original, research-backed articles built around real search intent — written to rank on Google and turn readers into enquiries, not just traffic.",
        "href": "/services/content-creation/seo-blog-post-and-article-writing"
      },
      {
        "slug": "website-copywriting",
        "name": "Website Copywriting",
        "description": "Sharp, structured copy for every page — homepage to services — that explains what you do, why it matters, and what to do next.",
        "href": "/services/content-creation/website-copywriting"
      },
      {
        "slug": "landing-page-copywriting",
        "name": "Landing Page Copywriting",
        "description": "Persuasive, single-focus landing page copy for ads, launches, and campaigns — with the message, structure, and CTA that convert paid traffic.",
        "href": "/services/content-creation/landing-page-copywriting"
      },
      {
        "slug": "case-study-and-portfolio-writing",
        "name": "Case Study & Portfolio Writing",
        "description": "Turn your best projects into persuasive case studies — challenge, approach, and outcome — that give serious buyers a reason to choose you.",
        "href": "/services/content-creation/case-study-and-portfolio-writing"
      },
      {
        "slug": "email-newsletter-copywriting",
        "name": "Email Newsletter Copywriting",
        "description": "Engaging, on-brand email copy — subject lines to CTAs — that keeps your list warm and turns subscribers into repeat customers.",
        "href": "/services/content-creation/email-newsletter-copywriting"
      }
    ],
    "ar": [
      {
        "slug": "seo-blog-post-and-article-writing",
        "name": "كتابة مقالات المدونة المُحسّنة لمحركات البحث",
        "description": "مقالات أصيلة مدعومة بأبحاث حقيقية، مبنية على نية البحث الفعلية — مكتوبة لتتصدر Google وتحوّل القراء إلى استفسارات حقيقية، لا مجرد زيارات.",
        "href": "/services/content-creation/seo-blog-post-and-article-writing"
      },
      {
        "slug": "website-copywriting",
        "name": "كتابة نصوص المواقع الإلكترونية",
        "description": "نصوص حادة ومُهيكلة لكل صفحة — من الرئيسية إلى الخدمات — تشرح ما تفعله ولماذا يهمّ وما الخطوة التالية.",
        "href": "/services/content-creation/website-copywriting"
      },
      {
        "slug": "landing-page-copywriting",
        "name": "كتابة نصوص صفحات الهبوط",
        "description": "نصوص صفحات هبوط مقنعة وذات تركيز واحد للإعلانات والإطلاقات والحملات — بالرسالة والهيكل والدعوة للتصرف التي تحوّل الزيارات المدفوعة.",
        "href": "/services/content-creation/landing-page-copywriting"
      },
      {
        "slug": "case-study-and-portfolio-writing",
        "name": "كتابة دراسات الحالة وأعمال المحفظة",
        "description": "حوّل أفضل مشاريعك إلى دراسات حالة مقنعة — التحدي والأسلوب والنتيجة — تمنح العملاء الجادين سببًا وجيهًا لاختيارك.",
        "href": "/services/content-creation/case-study-and-portfolio-writing"
      },
      {
        "slug": "email-newsletter-copywriting",
        "name": "كتابة نشرات البريد الإلكتروني",
        "description": "نصوص بريد إلكتروني جذابة ومتوافقة مع هويتك — من سطر الموضوع حتى زر الدعوة للتصرف — تُبقي قائمتك دافئة وتحوّل المشتركين إلى عملاء متكررين.",
        "href": "/services/content-creation/email-newsletter-copywriting"
      }
    ]
  },
  "custom-erp-crm-solutions": {
    "en": [
      {
        "slug": "odoo-erp-implementation",
        "name": "Odoo ERP Implementation, Setup & Customization",
        "description": "We turn Odoo into a system shaped around how your business actually runs — sales, inventory, accounting, purchasing, and HR connected in one platform you fully own.",
        "href": "/services/custom-erp-crm-solutions/odoo-erp-implementation"
      },
      {
        "slug": "sales-crm-pipeline-architecture",
        "name": "Sales CRM Pipeline Architecture & Optimization",
        "description": "We architect a sales pipeline that mirrors how your team actually closes — clear stages, automatic follow-ups, and honest forecasts. The result is a CRM your reps trust and your team fully owns.",
        "href": "/services/custom-erp-crm-solutions/sales-crm-pipeline-architecture"
      },
      {
        "slug": "legacy-system-migration",
        "name": "Legacy Spreadsheet & Outdated System Migration",
        "description": "Move years of scattered spreadsheets, ageing desktop software, and disconnected tools into one clean system that fits how you work today. Your history comes with you — cleansed, deduplicated, and verified — and the result is fully yours to own.",
        "href": "/services/custom-erp-crm-solutions/legacy-system-migration"
      },
      {
        "slug": "lead-management-distribution",
        "name": "Centralized Lead Management & Distribution Engines",
        "description": "Every enquiry from WhatsApp, your website, ads, and phone lands in one inbox and is routed to the right rep in seconds. No lead sits unclaimed, no source goes untracked, and you fully own the whole engine — code, data, and rules.",
        "href": "/services/custom-erp-crm-solutions/lead-management-distribution"
      },
      {
        "slug": "multi-branch-operations-management",
        "name": "Multi-Branch & Franchise Operations Management",
        "description": "Run every branch, outlet, and franchisee on one connected system, with live consolidated numbers for head office and clean per-location control for each manager. You own the code, the data, and the documentation outright.",
        "href": "/services/custom-erp-crm-solutions/multi-branch-operations-management"
      },
      {
        "slug": "customer-support-ticketing-systems",
        "name": "Customer Support & Automated Ticketing Systems",
        "description": "We build a support desk shaped around how your team really handles customers — every WhatsApp message, email, and call turned into a tracked ticket that routes itself, escalates on time, and never slips through the cracks.",
        "href": "/services/custom-erp-crm-solutions/customer-support-ticketing-systems"
      },
      {
        "slug": "ecommerce-erp-synchronization",
        "name": "Omnichannel E-Commerce to ERP Synchronization",
        "description": "Connect your online store, marketplaces, and POS to your ERP so orders, stock, and customers stay in sync across every channel — automatically, with no spreadsheets or double entry. You own the integration end to end.",
        "href": "/services/custom-erp-crm-solutions/ecommerce-erp-synchronization"
      },
      {
        "slug": "role-based-access-control",
        "name": "Role-Based Access Control (RBAC) & Security Policies",
        "description": "Give every person exactly the access their role requires — no more, no less — across your ERP and CRM. We design permission matrices, enforce data-level rules, and log every action so sensitive records stay protected and fully auditable.",
        "href": "/services/custom-erp-crm-solutions/role-based-access-control"
      },
      {
        "slug": "crm-development",
        "name": "Custom CRM Development Built Around Your Business",
        "description": "We build a custom CRM shaped around how your team really works with customers — every contact, deal, and conversation in one place. You own the code, the data, and the documentation, with no monthly seat fees and no vendor lock-in.",
        "href": "/services/custom-erp-crm-solutions/crm-development"
      }
    ],
    "ar": [
      {
        "slug": "odoo-erp-implementation",
        "name": "تطبيق نظام Odoo ERP وإعداده وتخصيصه",
        "description": "نحوّل Odoo إلى نظام مبني حول طريقة عمل مؤسستك الفعلية — المبيعات والمخزون والمحاسبة والمشتريات والموارد البشرية مترابطة في منصة واحدة تملكها بالكامل.",
        "href": "/services/custom-erp-crm-solutions/odoo-erp-implementation"
      },
      {
        "slug": "sales-crm-pipeline-architecture",
        "name": "بنية خط مبيعات CRM وتحسينه",
        "description": "نصمم خط مبيعات يعكس كيفية إغلاق فريقك للصفقات فعلياً — مراحل واضحة، ومتابعات تلقائية، وتوقعات صادقة. النتيجة نظام CRM يثق به مندوبوك ويمتلكه فريقك بالكامل.",
        "href": "/services/custom-erp-crm-solutions/sales-crm-pipeline-architecture"
      },
      {
        "slug": "legacy-system-migration",
        "name": "ترحيل جداول البيانات والأنظمة القديمة",
        "description": "انقل سنوات من جداول البيانات المبعثرة والبرمجيات المكتبية المتقادمة والأدوات المنفصلة إلى نظام واحد نظيف يناسب طريقة عملك اليوم. يأتي تاريخك معك — منقّى ومُزال التكرار ومُتحقَّقاً منه — والنتيجة ملك لك بالكامل.",
        "href": "/services/custom-erp-crm-solutions/legacy-system-migration"
      },
      {
        "slug": "lead-management-distribution",
        "name": "محركات مركزية لإدارة وتوزيع العملاء المحتملين",
        "description": "كل استفسار من واتساب وموقعك والإعلانات والهاتف يصل إلى صندوق واحد ويُوجَّه إلى المندوب المناسب خلال ثوانٍ. لا عميل يبقى بلا متابعة، ولا مصدر بلا تتبّع، وأنت تملك المحرك كاملاً — الكود والبيانات والقواعد.",
        "href": "/services/custom-erp-crm-solutions/lead-management-distribution"
      },
      {
        "slug": "multi-branch-operations-management",
        "name": "إدارة عمليات الفروع والامتيازات المتعددة",
        "description": "شغّل كل فرع ومنفذ وصاحب امتياز على نظام واحد مترابط، بأرقام موحّدة لحظية للإدارة الرئيسية وتحكم نظيف لكل موقع لكل مدير. تملك الكود والبيانات والتوثيق بالكامل.",
        "href": "/services/custom-erp-crm-solutions/multi-branch-operations-management"
      },
      {
        "slug": "customer-support-ticketing-systems",
        "name": "أنظمة دعم العملاء والتذاكر المؤتمتة",
        "description": "نبني مكتب دعم مبنياً حول طريقة تعامل فريقك الفعلية مع العملاء — كل رسالة واتساب وبريد ومكالمة تتحول إلى تذكرة متتبَّعة توجّه نفسها، وتُصعّد في وقتها، ولا تفلت أبداً.",
        "href": "/services/custom-erp-crm-solutions/customer-support-ticketing-systems"
      },
      {
        "slug": "ecommerce-erp-synchronization",
        "name": "مزامنة المتجر الإلكتروني متعدد القنوات مع ERP",
        "description": "اربط متجرك الإلكتروني والأسواق ونقاط البيع بنظام ERP لديك، فتبقى الطلبات والمخزون والعملاء متزامنين عبر كل قناة — تلقائياً، بلا جداول ولا إدخال مزدوج. أنت تملك التكامل من طرف إلى طرف.",
        "href": "/services/custom-erp-crm-solutions/ecommerce-erp-synchronization"
      },
      {
        "slug": "role-based-access-control",
        "name": "التحكم بالصلاحيات حسب الدور (RBAC) والسياسات الأمنية",
        "description": "امنح كل شخص الصلاحية التي يتطلبها دوره بالضبط — لا أكثر ولا أقل — عبر نظام ERP وCRM لديك. نصمم مصفوفات الأذونات، ونفرض قواعد على مستوى البيانات، ونسجّل كل إجراء، فتبقى السجلات الحساسة محمية وقابلة للتدقيق بالكامل.",
        "href": "/services/custom-erp-crm-solutions/role-based-access-control"
      },
      {
        "slug": "crm-development",
        "name": "تطوير نظام CRM مخصص مبني حول عملك",
        "description": "نبني نظام CRM مخصصاً مبنياً حول طريقة تعامل فريقك الفعلية مع العملاء — كل جهة اتصال وصفقة ومحادثة في مكان واحد. تملك الكود والبيانات والتوثيق، دون رسوم شهرية لكل مستخدم ودون احتكار.",
        "href": "/services/custom-erp-crm-solutions/crm-development"
      }
    ]
  },
  "custom-saas-mvp-development": {
    "en": [
      {
        "slug": "minimum-viable-product-mvp-development-for-startups",
        "name": "Minimum Viable Product (MVP) Development for Startups",
        "description": "Ship the one core loop that proves value and put it in front of real users fast.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      },
      {
        "slug": "software-as-a-service-saas-platform-architecture",
        "name": "Software-as-a-Service (SaaS) Platform Architecture",
        "description": "A clean, service-oriented codebase your v2 and funding round build on, not a rewrite.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      },
      {
        "slug": "multi-tenant-application-architecture",
        "name": "Multi-Tenant Application Architecture",
        "description": "Isolated data and settings per customer or workspace — one platform, many secure accounts.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      },
      {
        "slug": "subscription-based-product-development-stripe-billing",
        "name": "Subscription-Based Product Development (Stripe Billing)",
        "description": "Plans, free trials, upgrades, and invoices wired in so you charge recurring revenue from launch.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      }
    ],
    "ar": [
      {
        "slug": "minimum-viable-product-mvp-development-for-startups",
        "name": "تطوير المنتج الأولي (MVP) للشركات الناشئة",
        "description": "نطلق الحلقة الأساسية التي تثبت القيمة ونضعها أمام مستخدمين حقيقيين بسرعة.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      },
      {
        "slug": "software-as-a-service-saas-platform-architecture",
        "name": "بنية منصات البرمجيات كخدمة (SaaS)",
        "description": "كود نظيف موجّه للخدمات يُبنى عليه إصدارك الثاني وجولة تمويلك، لا إعادة كتابة.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      },
      {
        "slug": "multi-tenant-application-architecture",
        "name": "بنية تطبيقات متعددة المستأجرين",
        "description": "بيانات وإعدادات معزولة لكل عميل أو مساحة عمل — منصة واحدة تخدم حسابات كثيرة بأمان.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      },
      {
        "slug": "subscription-based-product-development-stripe-billing",
        "name": "تطوير منتجات بنظام الاشتراك (فوترة Stripe)",
        "description": "خطط وتجارب مجانية وترقيات وفواتير مدمجة لتتقاضى إيراداً متكرراً من الإطلاق.",
        "href": "/services/web-applications/custom-saas-mvp-development"
      }
    ]
  },
  "ecommerce-development": {
    "en": [
      {
        "slug": "custom-e-commerce-development",
        "name": "Custom E-Commerce Development",
        "description": "A bespoke e-commerce platform engineered for your catalog, checkout, and growth — not squeezed into a rigid template.",
        "href": "/services/ecommerce-development/custom-e-commerce-development"
      },
      {
        "slug": "shopify-store-development",
        "name": "Shopify Store Development",
        "description": "A custom-designed Shopify store tuned for your brand, your products, and Gulf shoppers — launched fast and built to convert.",
        "href": "/services/ecommerce-development/shopify-store-development"
      },
      {
        "slug": "woocommerce-store-development",
        "name": "WooCommerce Store Development",
        "description": "A flexible WooCommerce store on WordPress — full ownership, no platform fees, and customized to exactly how you sell.",
        "href": "/services/ecommerce-development/woocommerce-store-development"
      },
      {
        "slug": "multi-vendor-marketplace-development",
        "name": "Multi-Vendor Marketplace Development",
        "description": "Launch your own marketplace — vendor onboarding, product approvals, commissions, and automated payouts in one platform you own.",
        "href": "/services/ecommerce-development/multi-vendor-marketplace-development"
      },
      {
        "slug": "e-commerce-redesign-and-migration",
        "name": "E-Commerce Redesign & Migration",
        "description": "Modernize or re-platform your store without losing data or rankings — a faster, better-converting store, migrated safely.",
        "href": "/services/ecommerce-development/e-commerce-redesign-and-migration"
      },
      {
        "slug": "payment-gateway-integration",
        "name": "Payment Gateway Integration",
        "description": "Add the payment methods Gulf shoppers actually use — securely integrated for a smooth, trusted checkout that reduces drop-off.",
        "href": "/services/ecommerce-development/payment-gateway-integration"
      },
      {
        "slug": "b2b-wholesale-portal-development",
        "name": "B2B Wholesale Portal Development",
        "description": "A B2B ordering portal with per-account pricing, bulk and re-order flows, quotes, and credit terms — so wholesale buyers order with ease.",
        "href": "/services/ecommerce-development/b2b-wholesale-portal-development"
      },
      {
        "slug": "pos-integration",
        "name": "POS Integration for Online Stores",
        "description": "Connect your POS and online store so inventory, orders, and customers stay in sync across every channel — no more double entry.",
        "href": "/services/ecommerce-development/pos-integration"
      }
    ],
    "ar": [
      {
        "slug": "custom-e-commerce-development",
        "name": "تطوير متاجر إلكترونية مخصصة",
        "description": "منصة تجارة إلكترونية مُصمَّمة خصيصاً لكتالوجك وصفحة الدفع وأهدافك في النمو — بعيداً عن القوالب الجاهزة المقيِّدة.",
        "href": "/services/ecommerce-development/custom-e-commerce-development"
      },
      {
        "slug": "shopify-store-development",
        "name": "تطوير متجر Shopify",
        "description": "متجر Shopify مصمم خصيصاً لعلامتك التجارية ومنتجاتك والمتسوقين في الخليج — يُطلق بسرعة ومبني للتحويل.",
        "href": "/services/ecommerce-development/shopify-store-development"
      },
      {
        "slug": "woocommerce-store-development",
        "name": "تطوير متجر WooCommerce",
        "description": "متجر WooCommerce مرن على WordPress — ملكية كاملة وبدون رسوم منصة، ومخصص تماماً لأسلوب بيعك الخاص.",
        "href": "/services/ecommerce-development/woocommerce-store-development"
      },
      {
        "slug": "multi-vendor-marketplace-development",
        "name": "تطوير منصة متعددة البائعين",
        "description": "أطلق سوقك الإلكتروني الخاص — تسجيل البائعين وموافقات المنتجات والعمولات والمدفوعات الآلية، كل ذلك في منصة واحدة تمتلكها بالكامل.",
        "href": "/services/ecommerce-development/multi-vendor-marketplace-development"
      },
      {
        "slug": "e-commerce-redesign-and-migration",
        "name": "إعادة تصميم ونقل المتاجر الإلكترونية",
        "description": "حدِّث متجرك أو انتقل إلى منصة جديدة دون فقدان البيانات أو التصنيفات — متجر أسرع وأعلى تحويلاً، منقول بأمان.",
        "href": "/services/ecommerce-development/e-commerce-redesign-and-migration"
      },
      {
        "slug": "payment-gateway-integration",
        "name": "تكامل بوابات الدفع الإلكتروني",
        "description": "أضف وسائل الدفع التي يستخدمها المتسوقون في الخليج فعلاً — تكامل آمن لتجربة دفع سلسة وموثوقة تقلل معدل التخلي عن سلة التسوق.",
        "href": "/services/ecommerce-development/payment-gateway-integration"
      },
      {
        "slug": "b2b-wholesale-portal-development",
        "name": "تطوير بوابة البيع بالجملة B2B",
        "description": "بوابة طلبات B2B مع أسعار مخصصة لكل حساب، وتدفقات شراء بالجملة وإعادة الطلب، وعروض الأسعار، وشروط الائتمان — لتجعل عملية الطلب سلسة ومريحة لعملاء الجملة.",
        "href": "/services/ecommerce-development/b2b-wholesale-portal-development"
      },
      {
        "slug": "pos-integration",
        "name": "تكامل نقاط البيع مع المتاجر الإلكترونية",
        "description": "اربط نظام نقطة البيع بمتجرك الإلكتروني ليبقى المخزون والطلبات وبيانات العملاء متزامنة عبر كل القنوات — بدون إدخال مزدوج للبيانات.",
        "href": "/services/ecommerce-development/pos-integration"
      }
    ]
  },
  "full-stack-web-engineering": {
    "en": [
      {
        "slug": "next-js-and-react-front-end-engineering",
        "name": "Next.js & React Front-End Engineering",
        "description": "Fast, accessible, bilingual interfaces — server-rendered for SEO and speed.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "node-js-python-and-php-laravel-back-end-engineering",
        "name": "Node.js, Python & PHP/Laravel Back-End Engineering",
        "description": "Robust back-ends in the right runtime for the job, with clean, testable business logic.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "single-and-multi-page-application-development",
        "name": "Single & Multi-Page Application Development",
        "description": "SPAs for rich interactivity or MPAs for SEO reach — matched to your goals.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "progressive-web-app-pwa-development",
        "name": "Progressive Web App (PWA) Development",
        "description": "Installable apps that load instantly, work offline, and send push notifications.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "database-architecture-and-data-modeling",
        "name": "Database Architecture & Data Modeling",
        "description": "Proper schema design and indexing so the app stays fast and consistent as data grows.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "custom-api-third-party-integrations-and-payment-sso-setup",
        "name": "Custom API, Third-Party Integrations & Payment/SSO Setup",
        "description": "REST and GraphQL APIs, payment gateways, and single sign-on connected securely in one place.",
        "href": "/services/web-applications/full-stack-web-engineering"
      }
    ],
    "ar": [
      {
        "slug": "next-js-and-react-front-end-engineering",
        "name": "هندسة الواجهة الأمامية بـ Next.js وReact",
        "description": "واجهات سريعة وسهلة الوصول وثنائية اللغة، مُصيَّرة على الخادم للسيو والسرعة.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "node-js-python-and-php-laravel-back-end-engineering",
        "name": "هندسة الخلفية بـ Node.js وPython وPHP/Laravel",
        "description": "خلفيات متينة بالبيئة الأنسب للمهمة، بمنطق أعمال نظيف قابل للاختبار.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "single-and-multi-page-application-development",
        "name": "تطوير تطبيقات الصفحة الواحدة والمتعددة",
        "description": "تطبيقات صفحة واحدة للتفاعل الغني أو متعددة الصفحات لوصول السيو — مطابقة لأهدافك.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "progressive-web-app-pwa-development",
        "name": "تطوير تطبيقات الويب التقدمية (PWA)",
        "description": "تطبيقات قابلة للتثبيت تحمّل فوراً وتعمل دون إنترنت وترسل إشعارات دفع.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "database-architecture-and-data-modeling",
        "name": "بنية قاعدة البيانات ونمذجة البيانات",
        "description": "تصميم مخطط وفهرسة سليمين ليبقى التطبيق سريعاً ومتّسقاً مع نمو البيانات.",
        "href": "/services/web-applications/full-stack-web-engineering"
      },
      {
        "slug": "custom-api-third-party-integrations-and-payment-sso-setup",
        "name": "واجهات API مخصصة وتكاملات طرف ثالث وإعداد الدفع/SSO",
        "description": "واجهات REST وGraphQL وبوابات دفع وتسجيل دخول موحّد موصولة بأمان في مكان واحد.",
        "href": "/services/web-applications/full-stack-web-engineering"
      }
    ]
  },
  "interactive-portals-dashboards": {
    "en": [
      {
        "slug": "custom-client-and-customer-portals",
        "name": "Custom Client & Customer Portals",
        "description": "Secure, branded spaces where clients track projects, view invoices, and self-serve.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "admin-dashboards-and-control-panels",
        "name": "Admin Dashboards & Control Panels",
        "description": "A command center to manage users, content, orders, and operations on one screen you own.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "data-visualization-and-interactive-charting",
        "name": "Data Visualization & Interactive Charting",
        "description": "Live KPIs, trend lines, and interactive charts with filters and drill-down.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "role-based-access-control-and-permissions",
        "name": "Role-Based Access Control & Permissions",
        "description": "Granular RBAC gives each team and client their own view — nobody sees data they shouldn’t.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "file-upload-and-document-management-modules",
        "name": "File Upload & Document Management Modules",
        "description": "Upload, version, and share files in a searchable, permissioned document library.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      }
    ],
    "ar": [
      {
        "slug": "custom-client-and-customer-portals",
        "name": "بوابات مخصصة للعملاء والزبائن",
        "description": "مساحات آمنة بهويتك يتابع فيها العملاء المشاريع ويرون الفواتير ويخدمون أنفسهم.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "admin-dashboards-and-control-panels",
        "name": "لوحات إدارة ولوحات تحكم",
        "description": "مركز قيادة لإدارة المستخدمين والمحتوى والطلبات والعمليات على شاشة واحدة تملكها.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "data-visualization-and-interactive-charting",
        "name": "تصوير البيانات والرسوم التفاعلية",
        "description": "مؤشرات حية وخطوط اتجاه ورسوم تفاعلية بمرشّحات وتعمّق في التفاصيل.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "role-based-access-control-and-permissions",
        "name": "صلاحيات وتحكم بالوصول حسب الأدوار",
        "description": "تحكّم دقيق (RBAC) يمنح كل فريق وعميل عرضه الخاص — فلا يرى أحد بيانات لا تخصّه.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      },
      {
        "slug": "file-upload-and-document-management-modules",
        "name": "وحدات رفع الملفات وإدارة المستندات",
        "description": "ارفع وأصدر إصدارات وشارك الملفات في مكتبة مستندات قابلة للبحث ومحكومة الصلاحيات.",
        "href": "/services/web-applications/interactive-portals-dashboards"
      }
    ]
  },
  "media-entertainment-streaming": {
    "en": [
      {
        "slug": "vod-and-ott-streaming-platforms",
        "name": "VoD & OTT Streaming Platforms",
        "description": "On-demand libraries with categories, search, watchlists, and adaptive HLS/DASH playback.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "live-streaming-and-events",
        "name": "Live Streaming & Events",
        "description": "Low-latency live shows and webinars that scale from hundreds to tens of thousands of viewers.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "subscriptions-memberships-and-paywalls",
        "name": "Subscriptions, Memberships & Paywalls",
        "description": "Recurring plans, tiers, and pay-per-view via Stripe so your audience funds the content.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "media-asset-management-and-transcoding",
        "name": "Media Asset Management & Transcoding",
        "description": "Upload, transcode, tag, and organize a growing catalog with metadata and thumbnails.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "cdn-delivery-and-drm-content-protection",
        "name": "CDN Delivery & DRM Content Protection",
        "description": "Global CDN for fast start times, plus DRM and signed URLs to protect premium content.",
        "href": "/services/web-applications/media-entertainment-streaming"
      }
    ],
    "ar": [
      {
        "slug": "vod-and-ott-streaming-platforms",
        "name": "منصات بث VoD وOTT",
        "description": "مكتبات عند الطلب بتصنيفات وبحث وقوائم مشاهدة وتشغيل تكيّفي HLS/DASH.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "live-streaming-and-events",
        "name": "البث المباشر والفعاليات",
        "description": "برامج وندوات مباشرة بزمن استجابة منخفض تتوسّع من مئات إلى عشرات الآلاف من المشاهدين.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "subscriptions-memberships-and-paywalls",
        "name": "الاشتراكات والعضويات وجدران الدفع",
        "description": "خطط متكرّرة وعضويات ودفع لكل مشاهدة عبر Stripe ليموّل جمهورك المحتوى.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "media-asset-management-and-transcoding",
        "name": "إدارة الأصول الإعلامية وتحويل الترميز",
        "description": "ارفع وحوّل الترميز وصنّف ونظّم كتالوجاً متنامياً ببيانات وصفية وصور مصغّرة.",
        "href": "/services/web-applications/media-entertainment-streaming"
      },
      {
        "slug": "cdn-delivery-and-drm-content-protection",
        "name": "توصيل CDN وحماية المحتوى بـ DRM",
        "description": "CDN عالمي لأزمنة بدء سريعة، مع DRM وروابط موقّعة لحماية المحتوى المميّز.",
        "href": "/services/web-applications/media-entertainment-streaming"
      }
    ]
  },
  "search-engine-optimization": {
    "en": [
      {
        "slug": "technical-seo-and-indexing",
        "name": "Technical SEO & Indexing",
        "description": "We fix the technical foundations that decide whether your pages get found at all — crawlability, indexing, structured data, and site architecture — so search engines can read every page the way you intended. Every fix lands in your own code and Search Console, yours to keep with no lock-in.",
        "href": "/services/search-engine-optimization/technical-seo-and-indexing"
      },
      {
        "slug": "on-page-seo-optimization",
        "name": "On-Page SEO Optimization",
        "description": "We optimize each page from the inside out — titles, headings, copy, internal links, and structured data — so search engines understand it clearly and rank it for the right terms. Every change lands in your own site, documented and yours to keep.",
        "href": "/services/search-engine-optimization/on-page-seo-optimization"
      },
      {
        "slug": "off-page-seo-and-link-building",
        "name": "Off-Page SEO & Link Building",
        "description": "We build your site's reputation off-page through genuine, relevant backlinks, brand mentions, and digital PR — the signals Google uses to decide who deserves to rank. Every link is one we can show you, on a real site, with no spam and no shortcuts that get you penalised.",
        "href": "/services/search-engine-optimization/off-page-seo-and-link-building"
      },
      {
        "slug": "e-commerce-seo",
        "name": "E-Commerce SEO",
        "description": "We make your online store easy for Google to crawl and easy for shoppers to find — from product schema and category structure to the duplicate-content and filter traps that quietly bury big catalogs. Every change lives in your own store, with a clear before-and-after to show it worked.",
        "href": "/services/search-engine-optimization/e-commerce-seo"
      },
      {
        "slug": "local-and-global-seo-strategy",
        "name": "Local & Global SEO Strategy",
        "description": "We map out which markets are worth competing in — a single city, the whole GCC, or several countries — and build the keyword, language, and page structure to win each one. You leave with a documented plan and the accounts to run it.",
        "href": "/services/search-engine-optimization/local-and-global-seo-strategy"
      },
      {
        "slug": "seo-audits-and-competitor-analysis",
        "name": "SEO Audits & Competitor Analysis",
        "description": "We crawl your whole site, check it against Google's ranking signals, and line you up beside the competitors who beat you in search — then hand over a clear, prioritized fix list with the reasoning behind every item. You keep the full report and all the data; nothing is locked to us.",
        "href": "/services/search-engine-optimization/seo-audits-and-competitor-analysis"
      },
      {
        "slug": "keyword-research-and-strategy",
        "name": "Keyword Research & Strategy",
        "description": "We map what your customers in Oman and the GCC actually search for — in Arabic and English — and turn it into a prioritized keyword plan your team can act on and keep. No guesswork, no padded lists of terms nobody types.",
        "href": "/services/search-engine-optimization/keyword-research-and-strategy"
      },
      {
        "slug": "multilingual-and-international-seo",
        "name": "Multilingual & International SEO",
        "description": "We make the right page win for the right searcher — Arabic to Arabic, English to English, and the correct country edition for each GCC market. Proper hreflang, native keyword research, and a setup you own outright.",
        "href": "/services/search-engine-optimization/multilingual-and-international-seo"
      },
      {
        "slug": "voice-search-optimization",
        "name": "Voice Search Optimization",
        "description": "People increasingly search by talking — on phones, in cars, and through smart speakers — and they ask full questions, not keywords. We restructure your content so assistants like Google, Siri, and Alexa read your business as the spoken answer, in both Arabic and English.",
        "href": "/services/search-engine-optimization/voice-search-optimization"
      },
      {
        "slug": "image-and-video-seo",
        "name": "Image & Video SEO",
        "description": "Most sites publish photos and videos that search engines can't read, so they never surface in Google Images, video carousels, or AI answers. We optimize every visual asset — filenames, alt text, structured data, and sitemaps — so your media earns its own search traffic, in both Arabic and English.",
        "href": "/services/search-engine-optimization/image-and-video-seo"
      },
      {
        "slug": "google-business-profile-optimization",
        "name": "Google Business Profile Optimization",
        "description": "We turn a half-finished listing into a complete, keyword-rich Google Business Profile that surfaces in local and \"near me\" searches — driving more calls, direction requests, and walk-ins from people ready to buy nearby.",
        "href": "/services/search-engine-optimization/google-business-profile-optimization"
      },
      {
        "slug": "local-map-ranking-strategies",
        "name": "Local Map Ranking Strategies",
        "description": "We work the signals Google actually uses to rank the map pack — relevance, distance, and prominence — so your business shows up first when nearby customers search. You see exactly where you rank across the city before and after, on a real map grid.",
        "href": "/services/search-engine-optimization/local-map-ranking-strategies"
      },
      {
        "slug": "near-me-search-optimization",
        "name": "Near Me Search Optimization",
        "description": "When someone nearby reaches for their phone and types \"near me\" or \"open now,\" we make sure your business is the one that shows up — on the map, in the local pack, and ready to be called or visited. You own every account and asset we set up.",
        "href": "/services/search-engine-optimization/near-me-search-optimization"
      },
      {
        "slug": "franchise-and-multi-location-seo",
        "name": "Franchise & Multi-Location SEO",
        "description": "We make each outlet, clinic, or franchisee rank for its own neighborhood and \"near me\" searches across Oman and the GCC, instead of one head-office page competing with itself. You fully own every page, profile, and account we set up.",
        "href": "/services/search-engine-optimization/franchise-and-multi-location-seo"
      }
    ],
    "ar": [
      {
        "slug": "technical-seo-and-indexing",
        "name": "SEO التقني والفهرسة",
        "description": "نُصلح الأسس التقنية التي تحدد ما إذا كانت صفحاتك ستُكتشف أصلًا — قابلية الزحف والفهرسة والبيانات المنظمة وبنية الموقع — حتى تتمكن محركات البحث من قراءة كل صفحة كما أردتَ. كل إصلاح يُنفَّذ في كودك الخاص وSearch Console الخاص بك، ملك لك دون أي ارتباط.",
        "href": "/services/search-engine-optimization/technical-seo-and-indexing"
      },
      {
        "slug": "on-page-seo-optimization",
        "name": "تحسين SEO داخل الصفحة",
        "description": "نُحسّن كل صفحة من الداخل إلى الخارج — عناوين وترويسات ونصوص وروابط داخلية وبيانات منظمة — لتفهم محركات البحث مضمونها بوضوح وتُصنّفها للمصطلحات الصحيحة. كل تغيير يُنفَّذ في موقعك أنت، موثقاً وملكاً لك.",
        "href": "/services/search-engine-optimization/on-page-seo-optimization"
      },
      {
        "slug": "off-page-seo-and-link-building",
        "name": "SEO خارج الصفحة وبناء الروابط",
        "description": "نبني سمعة موقعك خارج الصفحة عبر روابط خلفية حقيقية وذات صلة وإشارات للعلامة التجارية وعلاقات عامة رقمية — الإشارات التي تعتمدها جوجل لتقرير من يستحق التصدر. كل رابط يمكننا إريتيه على موقع حقيقي دون رسائل مزعجة أو اختصارات قد تُعرضك للعقوبة.",
        "href": "/services/search-engine-optimization/off-page-seo-and-link-building"
      },
      {
        "slug": "e-commerce-seo",
        "name": "SEO للتجارة الإلكترونية",
        "description": "نجعل متجرك الإلكتروني سهل الزحف لجوجل وسهل الاكتشاف للمتسوقين — من بيانات المنتجات المنظمة وهيكل الفئات إلى فخاخ المحتوى المكرر والفلاتر التي تُغرق الكتالوجات الضخمة بصمت. كل تغيير يعيش في متجرك أنت، مع مقارنة واضحة قبل وبعد تُثبت نجاح العمل.",
        "href": "/services/search-engine-optimization/e-commerce-seo"
      },
      {
        "slug": "local-and-global-seo-strategy",
        "name": "استراتيجية SEO المحلي والعالمي",
        "description": "نُحدد الأسواق التي تستحق المنافسة — مدينة واحدة أو منطقة الخليج بأكملها أو عدة دول — وبنبي هيكل الكلمات المفتاحية واللغة والصفحات لتحقيق الفوز في كل سوق. تغادر بخطة موثقة والحسابات اللازمة لتشغيلها.",
        "href": "/services/search-engine-optimization/local-and-global-seo-strategy"
      },
      {
        "slug": "seo-audits-and-competitor-analysis",
        "name": "تدقيق SEO وتحليل المنافسين",
        "description": "نزحف عبر موقعك بالكامل، ونقيسه بمعايير الترتيب في Google، ونضعك جنبًا إلى جنب مع المنافسين الذين يتصدرونك في البحث — ثم نسلّمك قائمة إصلاحات واضحة ومرتّبة بحسب الأولوية مع مسوّغ كل بند. تحتفظ بالتقرير الكامل وجميع البيانات دون أي ربط بنا.",
        "href": "/services/search-engine-optimization/seo-audits-and-competitor-analysis"
      },
      {
        "slug": "keyword-research-and-strategy",
        "name": "بحث الكلمات المفتاحية واستراتيجيتها",
        "description": "نرسم خريطة لما يبحث عنه فعلاً عملاؤك في عُمان ودول الخليج — بالعربية والإنجليزية — ونحوّلها إلى خطة كلمات مفتاحية ذات أولويات يستطيع فريقك تنفيذها والاحتفاظ بها. لا تخمينات، لا قوائم منتفخة بمصطلحات لا يكتبها أحد.",
        "href": "/services/search-engine-optimization/keyword-research-and-strategy"
      },
      {
        "slug": "multilingual-and-international-seo",
        "name": "SEO متعدد اللغات والدولي",
        "description": "نجعل الصفحة الصحيحة تفوز أمام الباحث المناسب — العربية للعرب والإنجليزية للناطقين بها ونسخة الدولة الصحيحة لكل سوق خليجي. hreflang سليم وبحث أصيل للكلمات المفتاحية وإعداد تمتلكه بالكامل.",
        "href": "/services/search-engine-optimization/multilingual-and-international-seo"
      },
      {
        "slug": "voice-search-optimization",
        "name": "تحسين البحث الصوتي",
        "description": "يلجأ الناس بشكل متزايد إلى البحث بالكلام — على هواتفهم، في سياراتهم، وعبر مكبرات الصوت الذكية — ويطرحون أسئلة كاملة لا كلمات مفتاحية مقتضبة. نُعيد هيكلة محتواك لتقرأ فيه المساعدات كـ Google وSiri وAlexa إجابةً منطوقة لنشاطك التجاري، بالعربية والإنجليزية معًا.",
        "href": "/services/search-engine-optimization/voice-search-optimization"
      },
      {
        "slug": "image-and-video-seo",
        "name": "SEO الصور والفيديو",
        "description": "معظم المواقع تنشر صوراً ومقاطع فيديو لا تستطيع محركات البحث قراءتها، فلا تظهر في Google Images أو عروض الفيديو الدوّارة أو الإجابات الذكية. نُحسّن كل عنصر مرئي — أسماء الملفات والنصوص البديلة والبيانات المنظمة وخرائط الموقع — لتكسب وسائطك حركة بحث خاصة بها، بالعربية والإنجليزية.",
        "href": "/services/search-engine-optimization/image-and-video-seo"
      },
      {
        "slug": "google-business-profile-optimization",
        "name": "تحسين Google Business Profile",
        "description": "نحوّل القائمة غير المكتملة إلى ملف تعريفي شامل وغني بالكلمات المفتاحية على Google Business Profile يظهر في عمليات البحث المحلية و«بالقرب مني»، مما يزيد المكالمات وطلبات الاتجاهات والزيارات من العملاء المستعدين للشراء في المنطقة.",
        "href": "/services/search-engine-optimization/google-business-profile-optimization"
      },
      {
        "slug": "local-map-ranking-strategies",
        "name": "استراتيجيات التصنيف في خرائط جوجل المحلية",
        "description": "نعمل على الإشارات التي تستخدمها جوجل فعليًا لتصنيف حزمة الخرائط: الملاءمة والمسافة والبروز، حتى يظهر نشاطك أولاً حين يبحث العملاء القريبون. ترى بالضبط أين تتصدر في المدينة قبل وبعد، على شبكة خريطة حقيقية.",
        "href": "/services/search-engine-optimization/local-map-ranking-strategies"
      },
      {
        "slug": "near-me-search-optimization",
        "name": "تحسين البحث «بالقرب مني»",
        "description": "حين يمسك شخص قريب هاتفه ويكتب «بالقرب مني» أو «مفتوح الآن»، نتأكد أن نشاطك هو الذي يظهر: على الخريطة وفي الحزمة المحلية وجاهزًا للاتصال أو الزيارة. أنت تمتلك كل حساب وأصل ننشئه.",
        "href": "/services/search-engine-optimization/near-me-search-optimization"
      },
      {
        "slug": "franchise-and-multi-location-seo",
        "name": "تحسين محركات البحث للامتيازات التجارية والمواقع المتعددة",
        "description": "نجعل كل منفذ أو عيادة أو امتياز تجاري يتصدر نتائج البحث في حيّه الخاص وعمليات البحث بعبارة «بالقرب مني» في عُمان ودول الخليج، بدلاً من منافسة صفحة المقر الرئيسي لنفسها. أنت تمتلك بالكامل كل صفحة وملف تعريف وحساب ننشئه.",
        "href": "/services/search-engine-optimization/franchise-and-multi-location-seo"
      }
    ]
  },
  "social-media-management": {
    "en": [
      {
        "slug": "social-media-strategy-and-planning",
        "name": "Social Media Strategy & Planning",
        "description": "Stop posting randomly. We build a focused strategy — audience, channels, content pillars, and goals — so every post has a purpose.",
        "href": "/services/social-media-marketing/social-media-strategy-and-planning"
      },
      {
        "slug": "content-calendar-creation",
        "name": "Content Calendar Creation",
        "description": "A structured content calendar — themes, formats, and a posting schedule — so you always know what to post and never scramble.",
        "href": "/services/social-media-marketing/content-calendar-creation"
      },
      {
        "slug": "social-media-copywriting",
        "name": "Social Media Copywriting",
        "description": "On-brand captions, hooks, and CTAs written to grab attention and drive engagement — in Arabic and English.",
        "href": "/services/social-media-marketing/social-media-copywriting"
      },
      {
        "slug": "graphic-design-for-social-media",
        "name": "Graphic Design for Social Media",
        "description": "Eye-catching, on-brand graphics, carousels, and templates that make your feed look professional and stop the scroll.",
        "href": "/services/social-media-marketing/graphic-design-for-social-media"
      },
      {
        "slug": "short-form-video-editing",
        "name": "Short-Form Video Editing",
        "description": "Fast, punchy edits for Reels, TikTok, and Shorts — captions, hooks, and pacing that hold attention and grow reach.",
        "href": "/services/social-media-marketing/short-form-video-editing"
      },
      {
        "slug": "community-management-and-engagement",
        "name": "Community Management & Engagement",
        "description": "Active community management — replying to comments and DMs, sparking conversation, and turning followers into a loyal, engaged audience.",
        "href": "/services/social-media-marketing/community-management-and-engagement"
      },
      {
        "slug": "influencer-outreach-and-management",
        "name": "Influencer Outreach & Management",
        "description": "We identify, vet, and manage the right creators for your brand — from outreach to briefs to reporting — so partnerships actually pay off.",
        "href": "/services/social-media-marketing/influencer-outreach-and-management"
      },
      {
        "slug": "linkedin-b2b-personal-branding",
        "name": "LinkedIn B2B Personal Branding",
        "description": "Build your authority on LinkedIn — profile, content, and engagement — so the right people see you and inbound opportunities follow.",
        "href": "/services/social-media-marketing/linkedin-b2b-personal-branding"
      },
      {
        "slug": "social-media-analytics-and-reporting",
        "name": "Social Media Analytics & Reporting",
        "description": "Clear, regular reporting on the metrics that matter — reach, engagement, and conversions — with insights on what to do next.",
        "href": "/services/social-media-marketing/social-media-analytics-and-reporting"
      },
      {
        "slug": "email-marketing-automation",
        "name": "Email Marketing Automation",
        "description": "Automated welcome flows, lifecycle campaigns, and newsletters set up end to end — segmented, bilingual, and connected to your tools, so the right message reaches the right person without you sending it by hand.",
        "href": "/services/social-media-marketing/email-marketing-automation"
      },
      {
        "slug": "paid-ads-and-lead-generation",
        "name": "Paid Ads & Lead Generation",
        "description": "Strategy, creative, and management for paid advertising across Google, Meta, and LinkedIn — bilingual campaigns with proper conversion tracking, run inside ad accounts you own and can keep.",
        "href": "/services/social-media-marketing/paid-ads-and-lead-generation"
      }
    ],
    "ar": [
      {
        "slug": "social-media-strategy-and-planning",
        "name": "استراتيجية وسائل التواصل الاجتماعي والتخطيط",
        "description": "أوقف النشر العشوائي. نبني استراتيجية مركّزة — جمهور وقنوات ومحاور محتوى وأهداف — حتى يكون لكل منشور هدف.",
        "href": "/services/social-media-marketing/social-media-strategy-and-planning"
      },
      {
        "slug": "content-calendar-creation",
        "name": "إنشاء تقويم المحتوى",
        "description": "تقويم محتوى منظم — مواضيع وصيغ وجدول نشر — حتى تعرف دائماً ما ستنشره ولا تضطر إلى الارتجال.",
        "href": "/services/social-media-marketing/content-calendar-creation"
      },
      {
        "slug": "social-media-copywriting",
        "name": "كتابة محتوى وسائل التواصل الاجتماعي",
        "description": "تعليقات وخطافات ودعوات للعمل تعكس هوية علامتك التجارية وتشدّ الانتباه وتحفز التفاعل — بالعربية والإنجليزية.",
        "href": "/services/social-media-marketing/social-media-copywriting"
      },
      {
        "slug": "graphic-design-for-social-media",
        "name": "التصميم الجرافيكي لوسائل التواصل الاجتماعي",
        "description": "جرافيك وكاروسيل وقوالب جذابة تعكس هوية علامتك التجارية، تجعل صفحتك تبدو احترافية وتوقف التمرير.",
        "href": "/services/social-media-marketing/graphic-design-for-social-media"
      },
      {
        "slug": "short-form-video-editing",
        "name": "مونتاج مقاطع الفيديو القصيرة",
        "description": "مونتاج سريع ومؤثر للريلز وTikTok وShortsك — تعليقات وخطافات وإيقاع يُبقي المشاهد ويوسّع نطاق الوصول.",
        "href": "/services/social-media-marketing/short-form-video-editing"
      },
      {
        "slug": "community-management-and-engagement",
        "name": "إدارة المجتمع والتفاعل",
        "description": "إدارة مجتمع فعّالة — الرد على التعليقات والرسائل المباشرة، وإشعال المحادثات، وتحويل المتابعين إلى جمهور مخلص ومتفاعل.",
        "href": "/services/social-media-marketing/community-management-and-engagement"
      },
      {
        "slug": "influencer-outreach-and-management",
        "name": "التواصل مع المؤثرين وإدارتهم",
        "description": "نحدّد المبدعين المناسبين لعلامتك ونتحقق منهم وندير علاقتك معهم — من التواصل إلى التوجيهات الإبداعية حتى التقارير — حتى تؤتي الشراكات ثمارها.",
        "href": "/services/social-media-marketing/influencer-outreach-and-management"
      },
      {
        "slug": "linkedin-b2b-personal-branding",
        "name": "بناء العلامة الشخصية على LinkedIn للأعمال B2B",
        "description": "بناء سلطتك على LinkedIn — الملف الشخصي والمحتوى والتفاعل — حتى يراك الأشخاص المناسبون وتتدفق الفرص إليك.",
        "href": "/services/social-media-marketing/linkedin-b2b-personal-branding"
      },
      {
        "slug": "social-media-analytics-and-reporting",
        "name": "تحليلات وتقارير وسائل التواصل الاجتماعي",
        "description": "تقارير دورية واضحة عن المقاييس المهمة — الوصول والتفاعل والتحويلات — مع توصيات عملية للخطوة التالية.",
        "href": "/services/social-media-marketing/social-media-analytics-and-reporting"
      },
      {
        "slug": "email-marketing-automation",
        "name": "أتمتة التسويق عبر البريد الإلكتروني",
        "description": "مسارات ترحيب آلية وحملات دورة حياة ونشرات مُعدّة من البداية للنهاية — مقسَّمة وثنائية اللغة ومربوطة بأدواتك، لتصل الرسالة المناسبة إلى الشخص المناسب دون أن ترسلها يدوياً.",
        "href": "/services/social-media-marketing/email-marketing-automation"
      },
      {
        "slug": "paid-ads-and-lead-generation",
        "name": "الإعلانات المدفوعة وتوليد العملاء المحتملين",
        "description": "استراتيجية وإبداع وإدارة للإعلانات المدفوعة عبر جوجل وميتا ولينكدإن — حملات ثنائية اللغة بتتبّع تحويلات صحيح، تُدار داخل حسابات إعلانية تملكها وتحتفظ بها.",
        "href": "/services/social-media-marketing/paid-ads-and-lead-generation"
      }
    ]
  },
  "ui-ux-design-branding": {
    "en": [
      {
        "slug": "brand-strategy-and-positioning",
        "name": "Brand Strategy & Positioning",
        "description": "Before a logo or a website, you need to know who you serve, what you stand for, and why a customer should pick you. We turn that into a written brand strategy your whole team can act on — and that you own outright.",
        "href": "/services/ui-ux-design-branding/brand-strategy-and-positioning"
      },
      {
        "slug": "corporate-rebranding-strategy",
        "name": "Corporate Rebranding Strategy",
        "description": "A structured rebrand for established companies that have outgrown their identity — we audit the equity worth keeping, redesign the rest, and roll the new look across every touchpoint. You own the full brand system at the end.",
        "href": "/services/ui-ux-design-branding/corporate-rebranding-strategy"
      },
      {
        "slug": "logo-and-visual-identity-design",
        "name": "Logo & Visual Identity Design",
        "description": "We design a distinctive logo and a complete visual identity — colours, type, and supporting marks — that hold up everywhere your brand appears, from a phone screen to a shopfront sign. You see real options before you commit, and you own every file we deliver.",
        "href": "/services/ui-ux-design-branding/logo-and-visual-identity-design"
      },
      {
        "slug": "motion-graphics-and-web-animations",
        "name": "Motion Graphics & Web Animations",
        "description": "Animated logos, scroll effects, and interface micro-interactions that guide attention and add polish — tuned to stay smooth on real phones and handed over as files and code you own outright.",
        "href": "/services/ui-ux-design-branding/motion-graphics-and-web-animations"
      },
      {
        "slug": "ui-ux-design-and-testing",
        "name": "UI/UX Design & Testing",
        "description": "End-to-end UX and UI for your website or app — from user research and wireflows to polished interface design, validated through usability testing before a single line of production code is written.",
        "href": "/services/ui-ux-design-branding/ui-ux-design-and-testing"
      },
      {
        "slug": "mobile-and-web-app-interface-design",
        "name": "Mobile & Web App Interface Design",
        "description": "We design every screen, state, and flow your app needs — from sign-up to checkout — as a clickable prototype and a reusable design system your developers build straight from. You own the source files, components, and assets outright.",
        "href": "/services/ui-ux-design-branding/mobile-and-web-app-interface-design"
      },
      {
        "slug": "social-media-kit-and-assets-design",
        "name": "Social Media Kit & Assets Design",
        "description": "Editable templates, profile art, covers and highlight icons designed for the platforms you actually post on — in Arabic and English. You own the source files and reuse them for every post, so your feed looks consistent without a designer on call.",
        "href": "/services/ui-ux-design-branding/social-media-kit-and-assets-design"
      }
    ],
    "ar": [
      {
        "slug": "brand-strategy-and-positioning",
        "name": "استراتيجية العلامة التجارية وتحديد الموقع التنافسي",
        "description": "قبل الشعار والموقع الإلكتروني، تحتاج إلى معرفة من تخدم وما الذي تمثله ولماذا يختارك العميل. نحوّل ذلك إلى استراتيجية علامة تجارية مكتوبة يستطيع فريقك بأكمله العمل وفقها — وتملكها أنت بالكامل.",
        "href": "/services/ui-ux-design-branding/brand-strategy-and-positioning"
      },
      {
        "slug": "corporate-rebranding-strategy",
        "name": "استراتيجية إعادة بناء هوية الشركات",
        "description": "إعادة بناء هوية منهجية للشركات الراسخة التي تجاوزت هويتها الحالية — نراجع الرصيد الذي يستحق الحفاظ عليه ونعيد تصميم الباقي ونطرح الشكل الجديد على كل نقاط التواصل. تمتلك نظام العلامة التجارية الكامل في النهاية.",
        "href": "/services/ui-ux-design-branding/corporate-rebranding-strategy"
      },
      {
        "slug": "logo-and-visual-identity-design",
        "name": "تصميم الشعار والهوية البصرية",
        "description": "نصمم شعارًا مميزًا وهوية بصرية متكاملة — ألوان وخطوط وعلامات مساندة — تصمد في كل مكان تظهر فيه علامتك التجارية، من شاشة الهاتف إلى لافتة المتجر. ترى خيارات حقيقية قبل أن تلتزم، وتمتلك كل ملف نسلمه.",
        "href": "/services/ui-ux-design-branding/logo-and-visual-identity-design"
      },
      {
        "slug": "motion-graphics-and-web-animations",
        "name": "الموشن جرافيك والحركة التفاعلية للويب",
        "description": "شعارات متحركة، تأثيرات التمرير، وتفاعلات دقيقة تُوجّه الانتباه وتضيف لمسة احترافية — مضبوطة لتعمل بسلاسة على الأجهزة الحقيقية، وتُسلَّم إليك كملفات وكود تمتلكه بالكامل.",
        "href": "/services/ui-ux-design-branding/motion-graphics-and-web-animations"
      },
      {
        "slug": "ui-ux-design-and-testing",
        "name": "تصميم واختبار تجربة المستخدم",
        "description": "تجربة استخدام وواجهات متكاملة لموقعك أو تطبيقك — من أبحاث المستخدم ومخططات التدفّق إلى تصميم واجهات مصقول، مُتحقَّق منه عبر اختبار قابلية الاستخدام قبل كتابة أي سطر برمجي للإنتاج.",
        "href": "/services/ui-ux-design-branding/ui-ux-design-and-testing"
      },
      {
        "slug": "mobile-and-web-app-interface-design",
        "name": "تصميم واجهات تطبيقات الجوال والويب",
        "description": "نصمم كل شاشة وحالة وتدفق يحتاجه تطبيقك — من التسجيل إلى الدفع — كنموذج أولي قابل للنقر ونظام تصميم قابل لإعادة الاستخدام يبني منه مطوروك مباشرة. تمتلك الملفات المصدرية والمكونات والأصول بالكامل.",
        "href": "/services/ui-ux-design-branding/mobile-and-web-app-interface-design"
      },
      {
        "slug": "social-media-kit-and-assets-design",
        "name": "تصميم مجموعة وأصول التواصل الاجتماعي",
        "description": "قوالب قابلة للتعديل، وصور بروفايل وأغلفة وأيقونات هايلايت مصمّمة للمنصات التي تنشر عليها فعلاً — بالعربية والإنجليزية. تمتلك الملفات المصدرية وتستخدمها في كل منشور لتبدو قنواتك متسقة دون الحاجة إلى مصمم في كل مرة.",
        "href": "/services/ui-ux-design-branding/social-media-kit-and-assets-design"
      }
    ]
  },
  "website-development": {
    "en": [
      {
        "slug": "corporate-website-development",
        "name": "Corporate Website Development",
        "description": "A structured, multilingual corporate website for established companies — built around your leadership, divisions, and stakeholders, and handed over for your team to own and run.",
        "href": "/services/website-development/corporate-website-development"
      },
      {
        "slug": "business-website-development",
        "name": "Business Website Development",
        "description": "A lean, fast, multilingual website built around what your business actually sells — designed to win calls, messages, and quote requests, and handed over for your team to own and run.",
        "href": "/services/website-development/business-website-development"
      },
      {
        "slug": "landing-page-development",
        "name": "Landing Page Development",
        "description": "We build focused, fast-loading landing pages that turn a single campaign, ad, or offer into sign-ups, calls, and bookings — with the tracking already wired in so you can see exactly what's working.",
        "href": "/services/website-development/landing-page-development"
      },
      {
        "slug": "real-estate-website-development",
        "name": "Real Estate Website Development",
        "description": "A searchable, multilingual property website for developers, agencies, and brokers — built around listings, projects, and enquiry capture, and handed over for your team to own and run.",
        "href": "/services/website-development/real-estate-website-development"
      },
      {
        "slug": "educational-and-lms-website-development",
        "name": "Educational & LMS Website Development",
        "description": "We build education websites and learning platforms where students enroll, watch lessons, take quizzes, track progress, and earn certificates — all on a system you fully own. Built bilingual in Arabic and English, with WhatsApp support and a working demo before you commit.",
        "href": "/services/website-development/educational-and-lms-website-development"
      },
      {
        "slug": "healthcare-and-medical-website-development",
        "name": "Healthcare & Medical Website Development",
        "description": "We build clear, professional websites for clinics, hospitals, dental practices, and specialist doctors, with online booking, easy-to-scan service pages, and bilingual Arabic and English care. You own every line of code and every account, with no lock-in.",
        "href": "/services/website-development/healthcare-and-medical-website-development"
      },
      {
        "slug": "restaurant-and-hospitality-website-development",
        "name": "Restaurant & Hospitality Website Development",
        "description": "We build appetite-led websites for restaurants, cafes, and hotels in Oman and the GCC, with menus you can change yourself, online reservations, and direct delivery links. You own every file and account, in Arabic and English, with no monthly platform fee.",
        "href": "/services/website-development/restaurant-and-hospitality-website-development"
      },
      {
        "slug": "website-speed-and-performance-optimization",
        "name": "Website Speed & Performance Optimization",
        "description": "We diagnose what is dragging your site down and fix it for real: faster load times, smoother interaction, and a green pass on Google's Core Web Vitals. You keep every change in your own codebase, with a clear before-and-after to prove it worked.",
        "href": "/services/website-development/website-speed-and-performance-optimization"
      },
      {
        "slug": "website-redesign-and-modernization",
        "name": "Website Redesign & Modernization",
        "description": "We redesign ageing, slow, or hard-to-edit websites into clean, fast, mobile-first sites in Arabic and English — keeping the content and rankings you have earned. You see a live preview of the new design before you commit, and you own everything we hand over.",
        "href": "/services/website-development/website-redesign-and-modernization"
      },
      {
        "slug": "website-maintenance-and-support",
        "name": "Website Maintenance & Support",
        "description": "Launching a website is the start, not the finish. We handle the updates, backups, security patches, and content edits that keep yours running while you run your business — and you keep full ownership of the code and accounts the whole time.",
        "href": "/services/website-development/website-maintenance-and-support"
      },
      {
        "slug": "web-hosting-and-security-management",
        "name": "Web Hosting & Security Management",
        "description": "We host your website on fast, monitored infrastructure and lock it down with SSL, a firewall, and automated backups — on accounts you fully own, with no lock-in.",
        "href": "/services/website-development/web-hosting-and-security-management"
      }
    ],
    "ar": [
      {
        "slug": "corporate-website-development",
        "name": "تطوير مواقع الشركات",
        "description": "موقع شركة منظم ومتعدد اللغات للمؤسسات الراسخة، مبني حول قيادتك وأقسامك وأصحاب المصلحة، ويُسلَّم لفريقك لتمتلكوه وتديروه بالكامل.",
        "href": "/services/website-development/corporate-website-development"
      },
      {
        "slug": "business-website-development",
        "name": "تطوير مواقع الأعمال",
        "description": "موقع رشيق وسريع ومتعدد اللغات مبني حول ما تبيعه شركتك فعلاً — مصمَّم لكسب المكالمات والرسائل وطلبات عروض الأسعار، ويُسلَّم لفريقك ليمتلكه ويديره.",
        "href": "/services/website-development/business-website-development"
      },
      {
        "slug": "landing-page-development",
        "name": "تطوير صفحات الهبوط",
        "description": "نبني صفحات هبوط مركّزة وسريعة التحميل تحوّل حملة أو إعلانًا أو عرضًا واحدًا إلى تسجيلات ومكالمات وحجوزات، مع تتبع مُدمج مسبقًا لترى بالضبط ما يعمل.",
        "href": "/services/website-development/landing-page-development"
      },
      {
        "slug": "real-estate-website-development",
        "name": "تطوير مواقع العقارات",
        "description": "موقع عقاري قابل للبحث ومتعدد اللغات للمطوّرين والوكالات والوسطاء — مبني حول القوائم والمشاريع والتقاط الاستفسارات، ويُسلَّم لفريقك ليمتلكه ويديره.",
        "href": "/services/website-development/real-estate-website-development"
      },
      {
        "slug": "educational-and-lms-website-development",
        "name": "تطوير مواقع التعليم وأنظمة إدارة التعلم",
        "description": "نبني مواقع تعليمية ومنصات تعلم يسجّل فيها الطلاب ويشاهدون الدروس ويؤدون الاختبارات ويتابعون تقدمهم وينالون شهاداتهم، كل ذلك على نظام تمتلكه بالكامل. مبني ثنائي اللغة بالعربية والإنجليزية مع دعم WhatsApp ومعاينة فعلية قبل الالتزام.",
        "href": "/services/website-development/educational-and-lms-website-development"
      },
      {
        "slug": "healthcare-and-medical-website-development",
        "name": "تطوير مواقع الرعاية الصحية والطبية",
        "description": "نبني مواقع واضحة واحترافية للعيادات والمستشفيات وعيادات الأسنان والأطباء المتخصصين، مع الحجز الإلكتروني وصفحات خدمات سهلة التصفح ورعاية ثنائية اللغة بالعربية والإنجليزية. أنت تمتلك كل سطر من الكود وكل حساب دون أي تقييد.",
        "href": "/services/website-development/healthcare-and-medical-website-development"
      },
      {
        "slug": "restaurant-and-hospitality-website-development",
        "name": "تطوير مواقع المطاعم والضيافة",
        "description": "نبني مواقع تُعلي من شهية الطعام للمطاعم والمقاهي والفنادق في عُمان ودول الخليج، مع قوائم طعام تستطيع تغييرها بنفسك وحجوزات إلكترونية وروابط توصيل مباشرة. تمتلك كل ملف وحساب، بالعربية والإنجليزية، دون رسوم منصة شهرية.",
        "href": "/services/website-development/restaurant-and-hospitality-website-development"
      },
      {
        "slug": "website-speed-and-performance-optimization",
        "name": "تحسين سرعة الموقع وأدائه",
        "description": "نشخّص ما يُبطّئ موقعك ونُصلحه فعلياً: أوقات تحميل أسرع وتفاعل أسلس ونجاح أخضر في Core Web Vitals من Google. كل تغيير يبقى في قاعدة كودك الخاصة مع مقارنة واضحة قبل وبعد تُثبت النتيجة.",
        "href": "/services/website-development/website-speed-and-performance-optimization"
      },
      {
        "slug": "website-redesign-and-modernization",
        "name": "إعادة تصميم الموقع وتحديثه",
        "description": "نُعيد تصميم المواقع المتهالكة والبطيئة أو صعبة التحرير لتصبح مواقع نظيفة وسريعة ومحسّنة للجوال بالعربية والإنجليزية — مع الحفاظ على المحتوى والترتيبات التي اكتسبتها. ترى معاينة حية للتصميم الجديد قبل أي التزام، وتحتفظ بكل ما نُسلّمه إليك.",
        "href": "/services/website-development/website-redesign-and-modernization"
      },
      {
        "slug": "website-maintenance-and-support",
        "name": "صيانة الموقع الإلكتروني ودعمه",
        "description": "إطلاق الموقع بداية لا نهاية. نتولى التحديثات والنسخ الاحتياطية وتصحيحات الأمان وتعديلات المحتوى التي تُبقي موقعك يعمل بينما تركز أنت على إدارة عملك — وتحتفظ بالملكية الكاملة للكود والحسابات طوال الوقت.",
        "href": "/services/website-development/website-maintenance-and-support"
      },
      {
        "slug": "web-hosting-and-security-management",
        "name": "استضافة الويب وإدارة الأمان",
        "description": "نستضيف موقعك على بنية تحتية سريعة ومُراقبة ونؤمّنه بـ SSL وجدار حماية ونسخ احتياطية تلقائية — في حسابات تملكها أنت بالكامل ودون أي ارتباط مستمر.",
        "href": "/services/website-development/web-hosting-and-security-management"
      }
    ]
  }
}

export function getSubserviceNavItems(pillarSlug: string, locale: Locale, limit?: number): readonly SubserviceNavItem[] {
    const entry = INDEX[pillarSlug]
    if (!entry) return []
    const items = locale === 'ar' ? entry.ar : entry.en
    return typeof limit === 'number' ? items.slice(0, limit) : items
}

/** Canonical parent URL segment per nested sub-service slug (all branches). */
export const SUBSERVICE_CANONICAL_PARENT: Record<string, string> = {
  "accounting-system-integration": "business-process-automation",
  "automated-invoicing-payment-reminders": "business-process-automation",
  "automated-proposal-quotation-generation": "business-process-automation",
  "b2b-wholesale-portal-development": "ecommerce-development",
  "brand-strategy-and-positioning": "ui-ux-design-branding",
  "business-website-development": "website-development",
  "case-study-and-portfolio-writing": "content-creation",
  "community-management-and-engagement": "social-media-marketing",
  "content-calendar-creation": "social-media-marketing",
  "corporate-rebranding-strategy": "ui-ux-design-branding",
  "corporate-website-development": "website-development",
  "crm-development": "custom-erp-crm-solutions",
  "cross-platform-api-integration": "business-process-automation",
  "custom-api-development": "business-process-automation",
  "custom-e-commerce-development": "ecommerce-development",
  "customer-support-ticketing-systems": "custom-erp-crm-solutions",
  "e-commerce-redesign-and-migration": "ecommerce-development",
  "e-commerce-seo": "search-engine-optimization",
  "ecommerce-erp-synchronization": "custom-erp-crm-solutions",
  "educational-and-lms-website-development": "website-development",
  "email-marketing-automation": "social-media-marketing",
  "email-newsletter-copywriting": "content-creation",
  "employee-onboarding-automation": "business-process-automation",
  "esignature-contract-management": "business-process-automation",
  "franchise-and-multi-location-seo": "search-engine-optimization",
  "google-business-profile-optimization": "search-engine-optimization",
  "graphic-design-for-social-media": "social-media-marketing",
  "healthcare-and-medical-website-development": "website-development",
  "hr-management-systems": "business-management-systems",
  "image-and-video-seo": "search-engine-optimization",
  "influencer-outreach-and-management": "social-media-marketing",
  "inventory-management-systems": "business-management-systems",
  "keyword-research-and-strategy": "search-engine-optimization",
  "landing-page-copywriting": "content-creation",
  "landing-page-development": "website-development",
  "lead-management-distribution": "custom-erp-crm-solutions",
  "legacy-system-migration": "custom-erp-crm-solutions",
  "linkedin-b2b-personal-branding": "social-media-marketing",
  "local-and-global-seo-strategy": "search-engine-optimization",
  "local-map-ranking-strategies": "search-engine-optimization",
  "logo-and-visual-identity-design": "ui-ux-design-branding",
  "mobile-and-web-app-interface-design": "ui-ux-design-branding",
  "motion-graphics-and-web-animations": "ui-ux-design-branding",
  "multi-branch-operations-management": "custom-erp-crm-solutions",
  "multi-vendor-marketplace-development": "ecommerce-development",
  "multilingual-and-international-seo": "search-engine-optimization",
  "near-me-search-optimization": "search-engine-optimization",
  "odoo-erp-implementation": "custom-erp-crm-solutions",
  "off-page-seo-and-link-building": "search-engine-optimization",
  "on-page-seo-optimization": "search-engine-optimization",
  "order-management-systems": "business-management-systems",
  "paid-ads-and-lead-generation": "social-media-marketing",
  "payment-gateway-integration": "ecommerce-development",
  "pos-integration": "ecommerce-development",
  "purchase-order-approval-workflows": "business-process-automation",
  "real-estate-website-development": "website-development",
  "restaurant-and-hospitality-website-development": "website-development",
  "role-based-access-control": "custom-erp-crm-solutions",
  "sales-crm-pipeline-architecture": "custom-erp-crm-solutions",
  "sales-followup-drip-automation": "business-process-automation",
  "sales-management-systems": "business-management-systems",
  "seo-audits-and-competitor-analysis": "search-engine-optimization",
  "seo-blog-post-and-article-writing": "content-creation",
  "shopify-store-development": "ecommerce-development",
  "short-form-video-editing": "social-media-marketing",
  "social-media-analytics-and-reporting": "social-media-marketing",
  "social-media-copywriting": "social-media-marketing",
  "social-media-kit-and-assets-design": "ui-ux-design-branding",
  "social-media-strategy-and-planning": "social-media-marketing",
  "technical-seo-and-indexing": "search-engine-optimization",
  "ui-ux-design-and-testing": "ui-ux-design-branding",
  "voice-search-optimization": "search-engine-optimization",
  "web-hosting-and-security-management": "website-development",
  "website-copywriting": "content-creation",
  "website-maintenance-and-support": "website-development",
  "website-redesign-and-modernization": "website-development",
  "website-speed-and-performance-optimization": "website-development",
  "whatsapp-crm-lead-capture": "business-process-automation",
  "woocommerce-store-development": "ecommerce-development",
  "workflow-automation": "business-process-automation",
  "admin-dashboards": "web-applications",
  "application-modernization-performance": "web-applications",
  "booking-platforms": "web-applications",
  "client-portals": "web-applications",
  "custom-saas-mvp-development": "web-applications",
  "custom-web-application-development": "web-applications",
  "full-stack-web-engineering": "web-applications",
  "interactive-portals-dashboards": "web-applications",
  "internal-business-tools": "web-applications",
  "media-entertainment-streaming": "web-applications",
  "mobile-app-development": "web-applications",
  "progressive-web-app-development": "web-applications",
  "saas-mvp-development": "web-applications"
}
