import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * Payload platform upgrade: trash (soft delete) on blog posts and media,
 * media image sizes + duplicate-upload hash, and the tables for plugin-search,
 * plugin-import-export (plus the jobs queue it registers) and plugin-mcp.
 *
 * Generated by diffing drizzle snapshots of the committed config against the
 * new one (scripts/schema-snapshot.ts + scripts/schema-diff.ts), so it is the
 * exact delta — purely additive, no drops or type changes. New tables get RLS
 * with anon/authenticated revoked, like every other Payload table here:
 * payload_mcp_api_keys in particular must never be reachable via the public
 * Supabase REST API.
 */

const NEW_TABLES = ["search","search_rels","exports","exports_texts","imports","payload_mcp_api_keys","payload_jobs_log","payload_jobs"]

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(`
CREATE TYPE "public"."enum_exports_format" AS ENUM('csv', 'json');
CREATE TYPE "public"."enum_exports_sort_order" AS ENUM('asc', 'desc');
CREATE TYPE "public"."enum_exports_drafts" AS ENUM('yes', 'no');
CREATE TYPE "public"."enum_imports_import_mode" AS ENUM('create', 'update', 'upsert');
CREATE TYPE "public"."enum_imports_status" AS ENUM('pending', 'completed', 'partial', 'failed');
CREATE TYPE "public"."enum_payload_jobs_log_task_slug" AS ENUM('inline', 'createCollectionExport', 'createCollectionImport');
CREATE TYPE "public"."enum_payload_jobs_log_state" AS ENUM('failed', 'succeeded');
CREATE TYPE "public"."enum_payload_jobs_task_slug" AS ENUM('inline', 'createCollectionExport', 'createCollectionImport');
CREATE TABLE "search" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar,
	"priority" numeric,
	"locale" varchar,
	"status" varchar,
	"subtitle" varchar,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "search_rels" (
	"id" serial PRIMARY KEY NOT NULL,
	"order" integer,
	"parent_id" integer NOT NULL,
	"path" varchar NOT NULL,
	"blog_posts_id" integer,
	"pages_id" integer,
	"projects_id" varchar,
	"contact_inquiries_id" integer
);
CREATE TABLE "exports" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar,
	"format" "enum_exports_format" DEFAULT 'csv' NOT NULL,
	"limit" numeric,
	"page" numeric DEFAULT 1,
	"sort" varchar,
	"sort_order" "enum_exports_sort_order",
	"drafts" "enum_exports_drafts" DEFAULT 'yes',
	"collection_slug" varchar DEFAULT 'contact-inquiries' NOT NULL,
	"where" jsonb DEFAULT '{}'::jsonb,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"url" varchar,
	"thumbnail_u_r_l" varchar,
	"filename" varchar,
	"mime_type" varchar,
	"filesize" numeric,
	"width" numeric,
	"height" numeric,
	"focal_x" numeric,
	"focal_y" numeric
);
CREATE TABLE "exports_texts" (
	"id" serial PRIMARY KEY NOT NULL,
	"order" integer NOT NULL,
	"parent_id" integer NOT NULL,
	"path" varchar NOT NULL,
	"text" varchar
);
CREATE TABLE "imports" (
	"id" serial PRIMARY KEY NOT NULL,
	"collection_slug" varchar DEFAULT 'blog-categories' NOT NULL,
	"import_mode" "enum_imports_import_mode",
	"match_field" varchar DEFAULT 'id',
	"status" "enum_imports_status" DEFAULT 'pending',
	"summary_imported" numeric,
	"summary_updated" numeric,
	"summary_total" numeric,
	"summary_issues" numeric,
	"summary_issue_details" jsonb,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"url" varchar,
	"thumbnail_u_r_l" varchar,
	"filename" varchar,
	"mime_type" varchar,
	"filesize" numeric,
	"width" numeric,
	"height" numeric,
	"focal_x" numeric,
	"focal_y" numeric
);
CREATE TABLE "payload_mcp_api_keys" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"label" varchar,
	"description" varchar,
	"blog_posts_find" boolean DEFAULT false,
	"blog_posts_create" boolean DEFAULT false,
	"blog_posts_update" boolean DEFAULT false,
	"media_find" boolean DEFAULT false,
	"media_create" boolean DEFAULT false,
	"blog_categories_find" boolean DEFAULT false,
	"blog_tags_find" boolean DEFAULT false,
	"authors_find" boolean DEFAULT false,
	"pages_find" boolean DEFAULT false,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"enable_a_p_i_key" boolean,
	"api_key" varchar,
	"api_key_index" varchar
);
CREATE TABLE "payload_jobs_log" (
	"_order" integer NOT NULL,
	"_parent_id" integer NOT NULL,
	"id" varchar PRIMARY KEY NOT NULL,
	"executed_at" timestamp(3) with time zone NOT NULL,
	"completed_at" timestamp(3) with time zone NOT NULL,
	"task_slug" "enum_payload_jobs_log_task_slug" NOT NULL,
	"task_i_d" varchar NOT NULL,
	"input" jsonb,
	"output" jsonb,
	"state" "enum_payload_jobs_log_state" NOT NULL,
	"error" jsonb
);
CREATE TABLE "payload_jobs" (
	"id" serial PRIMARY KEY NOT NULL,
	"input" jsonb,
	"completed_at" timestamp(3) with time zone,
	"total_tried" numeric DEFAULT 0,
	"has_error" boolean DEFAULT false,
	"error" jsonb,
	"task_slug" "enum_payload_jobs_task_slug",
	"queue" varchar DEFAULT 'default',
	"wait_until" timestamp(3) with time zone,
	"processing" boolean DEFAULT false,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "media" ADD COLUMN "content_hash" varchar;
ALTER TABLE "media" ADD COLUMN "deleted_at" timestamp(3) with time zone;
ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_url" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_width" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_height" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_mime_type" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_filesize" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_filename" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_card_url" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_card_width" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_card_height" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_card_mime_type" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_card_filesize" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_card_filename" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_hero_url" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_hero_width" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_hero_height" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_hero_mime_type" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_hero_filesize" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_hero_filename" varchar;
ALTER TABLE "blog_posts" ADD COLUMN "deleted_at" timestamp(3) with time zone;
ALTER TABLE "_blog_posts_v" ADD COLUMN "version_deleted_at" timestamp(3) with time zone;
ALTER TABLE "payload_preferences_rels" ADD COLUMN "payload_mcp_api_keys_id" integer;
ALTER TABLE "search_rels" ADD CONSTRAINT "search_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."search"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "search_rels" ADD CONSTRAINT "search_rels_blog_posts_fk" FOREIGN KEY ("blog_posts_id") REFERENCES "public"."blog_posts"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "search_rels" ADD CONSTRAINT "search_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "search_rels" ADD CONSTRAINT "search_rels_projects_fk" FOREIGN KEY ("projects_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "search_rels" ADD CONSTRAINT "search_rels_contact_inquiries_fk" FOREIGN KEY ("contact_inquiries_id") REFERENCES "public"."contact_inquiries"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "exports_texts" ADD CONSTRAINT "exports_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."exports"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_mcp_api_keys" ADD CONSTRAINT "payload_mcp_api_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "payload_jobs_log" ADD CONSTRAINT "payload_jobs_log_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."payload_jobs"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "search_locale_idx" ON "search" USING btree ("locale");
CREATE INDEX "search_status_idx" ON "search" USING btree ("status");
CREATE INDEX "search_updated_at_idx" ON "search" USING btree ("updated_at");
CREATE INDEX "search_created_at_idx" ON "search" USING btree ("created_at");
CREATE INDEX "search_rels_order_idx" ON "search_rels" USING btree ("order");
CREATE INDEX "search_rels_parent_idx" ON "search_rels" USING btree ("parent_id");
CREATE INDEX "search_rels_path_idx" ON "search_rels" USING btree ("path");
CREATE INDEX "search_rels_blog_posts_id_idx" ON "search_rels" USING btree ("blog_posts_id");
CREATE INDEX "search_rels_pages_id_idx" ON "search_rels" USING btree ("pages_id");
CREATE INDEX "search_rels_projects_id_idx" ON "search_rels" USING btree ("projects_id");
CREATE INDEX "search_rels_contact_inquiries_id_idx" ON "search_rels" USING btree ("contact_inquiries_id");
CREATE INDEX "exports_updated_at_idx" ON "exports" USING btree ("updated_at");
CREATE INDEX "exports_created_at_idx" ON "exports" USING btree ("created_at");
CREATE UNIQUE INDEX "exports_filename_idx" ON "exports" USING btree ("filename");
CREATE INDEX "exports_texts_order_parent" ON "exports_texts" USING btree ("order","parent_id");
CREATE INDEX "imports_updated_at_idx" ON "imports" USING btree ("updated_at");
CREATE INDEX "imports_created_at_idx" ON "imports" USING btree ("created_at");
CREATE UNIQUE INDEX "imports_filename_idx" ON "imports" USING btree ("filename");
CREATE INDEX "payload_mcp_api_keys_user_idx" ON "payload_mcp_api_keys" USING btree ("user_id");
CREATE INDEX "payload_mcp_api_keys_updated_at_idx" ON "payload_mcp_api_keys" USING btree ("updated_at");
CREATE INDEX "payload_mcp_api_keys_created_at_idx" ON "payload_mcp_api_keys" USING btree ("created_at");
CREATE INDEX "payload_jobs_log_order_idx" ON "payload_jobs_log" USING btree ("_order");
CREATE INDEX "payload_jobs_log_parent_id_idx" ON "payload_jobs_log" USING btree ("_parent_id");
CREATE INDEX "payload_jobs_completed_at_idx" ON "payload_jobs" USING btree ("completed_at");
CREATE INDEX "payload_jobs_total_tried_idx" ON "payload_jobs" USING btree ("total_tried");
CREATE INDEX "payload_jobs_has_error_idx" ON "payload_jobs" USING btree ("has_error");
CREATE INDEX "payload_jobs_task_slug_idx" ON "payload_jobs" USING btree ("task_slug");
CREATE INDEX "payload_jobs_queue_idx" ON "payload_jobs" USING btree ("queue");
CREATE INDEX "payload_jobs_wait_until_idx" ON "payload_jobs" USING btree ("wait_until");
CREATE INDEX "payload_jobs_processing_idx" ON "payload_jobs" USING btree ("processing");
CREATE INDEX "payload_jobs_updated_at_idx" ON "payload_jobs" USING btree ("updated_at");
CREATE INDEX "payload_jobs_created_at_idx" ON "payload_jobs" USING btree ("created_at");
ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_payload_mcp_api_keys_fk" FOREIGN KEY ("payload_mcp_api_keys_id") REFERENCES "public"."payload_mcp_api_keys"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "media_content_hash_idx" ON "media" USING btree ("content_hash");
CREATE INDEX "media_deleted_at_idx" ON "media" USING btree ("deleted_at");
CREATE INDEX "media_sizes_thumbnail_sizes_thumbnail_filename_idx" ON "media" USING btree ("sizes_thumbnail_filename");
CREATE INDEX "media_sizes_card_sizes_card_filename_idx" ON "media" USING btree ("sizes_card_filename");
CREATE INDEX "media_sizes_hero_sizes_hero_filename_idx" ON "media" USING btree ("sizes_hero_filename");
CREATE INDEX "blog_posts_deleted_at_idx" ON "blog_posts" USING btree ("deleted_at");
CREATE INDEX "_blog_posts_v_version_version_deleted_at_idx" ON "_blog_posts_v" USING btree ("version_deleted_at");
CREATE INDEX "payload_preferences_rels_payload_mcp_api_keys_id_idx" ON "payload_preferences_rels" USING btree ("payload_mcp_api_keys_id");
`)

  for (const table of NEW_TABLES) {
    await db.execute(`
    do $$
    declare
      principal text;
      seq text;
    begin
      execute format('alter table public.%I enable row level security', '${table}');
      execute format('revoke all privileges on table public.%I from public', '${table}');
      foreach principal in array array['anon', 'authenticated']
      loop
        if exists (select 1 from pg_roles where rolname = principal) then
          execute format('revoke all privileges on table public.%I from %I', '${table}', principal);
        end if;
      end loop;
      select pg_get_serial_sequence(format('public.%I', '${table}'), 'id') into seq;
      if seq is not null then
        foreach principal in array array['anon', 'authenticated']
        loop
          if exists (select 1 from pg_roles where rolname = principal) then
            execute format('revoke all privileges on sequence %s from %I', seq, principal);
          end if;
        end loop;
      end if;
    end $$;
    `)
  }
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(`
    alter table public."media" drop column if exists "content_hash", drop column if exists "deleted_at", drop column if exists "sizes_thumbnail_url", drop column if exists "sizes_thumbnail_width", drop column if exists "sizes_thumbnail_height", drop column if exists "sizes_thumbnail_mime_type", drop column if exists "sizes_thumbnail_filesize", drop column if exists "sizes_thumbnail_filename", drop column if exists "sizes_card_url", drop column if exists "sizes_card_width", drop column if exists "sizes_card_height", drop column if exists "sizes_card_mime_type", drop column if exists "sizes_card_filesize", drop column if exists "sizes_card_filename", drop column if exists "sizes_hero_url", drop column if exists "sizes_hero_width", drop column if exists "sizes_hero_height", drop column if exists "sizes_hero_mime_type", drop column if exists "sizes_hero_filesize", drop column if exists "sizes_hero_filename";
    alter table public."blog_posts" drop column if exists "deleted_at";
    alter table public."_blog_posts_v" drop column if exists "version_deleted_at";
    alter table public."payload_preferences_rels" drop column if exists "payload_mcp_api_keys_id";
    drop table if exists public."search_rels", public."search", public."exports_texts", public."exports", public."imports", public."payload_jobs_log", public."payload_jobs", public."payload_mcp_api_keys" cascade;
    drop type if exists public."enum_exports_format", public."enum_exports_sort_order", public."enum_exports_drafts", public."enum_imports_import_mode", public."enum_imports_status", public."enum_payload_jobs_log_task_slug", public."enum_payload_jobs_log_state", public."enum_payload_jobs_task_slug";
  `)
}
