import { notFound, permanentRedirect } from 'next/navigation'
import type { Metadata } from 'next'
import { SUBSERVICE_CANONICAL_PARENT } from '@/lib/services/subservice-nav-index'

/**
 * Generic nested fallback: /services/<service>/<subservice>.
 *
 * Every canonical parent segment owns an explicit `[subservice]` route wrapper
 * (see `_shared/business-nested-page.tsx` / `digital-nested-page.tsx` /
 * `webapp-nested-page.tsx`), so this route only ever serves WRONG-parent URLs.
 * It resolves the canonical parent from the generated compact map and 301s —
 * importing no content database and no renderer, so requests here stay cheap
 * and the route contributes nothing to any page bundle.
 */

type PageProps = {
    params: Promise<{ locale: string; service: string; subservice: string }>
}

export function generateStaticParams() {
    // All canonical nested pages are generated by their explicit parent routes.
    return []
}

export async function generateMetadata(): Promise<Metadata> {
    return { title: 'Service Not Found' }
}

export default async function NestedSubServiceFallback({ params }: PageProps) {
    const { service, subservice } = await params

    const canonicalParent = SUBSERVICE_CANONICAL_PARENT[subservice]
    if (canonicalParent && canonicalParent !== service) {
        // Canonical guard: 301 to the single canonical home per sub-service.
        permanentRedirect(`/services/${canonicalParent}/${subservice}`)
    }

    notFound()
}
