import {
  BarChart3,
  Bot,
  Building2,
  CalendarClock,
  CheckCircle2,
  ClipboardList,
  Cloud,
  Code2,
  Database,
  Globe2,
  Layers,
  LineChart,
  MessageSquare,
  MonitorSmartphone,
  Rocket,
  Search,
  Settings2,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Store,
  Workflow,
  type LucideIcon,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  bot: Bot,
  building: Building2,
  calendar: CalendarClock,
  chart: BarChart3,
  check: CheckCircle2,
  clipboard: ClipboardList,
  cloud: Cloud,
  code: Code2,
  database: Database,
  globe: Globe2,
  layers: Layers,
  linechart: LineChart,
  message: MessageSquare,
  monitor: MonitorSmartphone,
  rocket: Rocket,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  shopping: ShoppingBag,
  sparkles: Sparkles,
  store: Store,
  workflow: Workflow,
}

export function getEnterpriseIcon(key: string): LucideIcon {
  return icons[key] || Sparkles
}

