/* Directly-authored content for the remaining Digital Presence sub-services.
 * Original CloudTopia copy — written in-file (no workflow agents). */
const fs = require('fs')

const PN = {
    'social-media-management': 'Social Media Management (SMM)',
    'customer-experience-portals': 'Customer Experience Portals',
    'content-marketing-authority': 'Content Marketing & Authority',
    'review-reputation-management': 'Review & Reputation Management',
    'analytics-performance-reporting': 'Analytics & Performance Reporting',
}
const OWN_ITEM = { title: 'You own everything', description: 'Code, data, accounts, and documentation stay with you — no lock-in to CloudTopia.' }
const BILINGUAL_FAQ = { question: 'Do you deliver in Arabic and English?', answer: 'Yes — bilingual Arabic + English with full RTL support, so both audiences get a first-class experience.' }
const OWN_FAQ = { question: 'Do we own the result?', answer: 'Completely. You keep the accounts, data, configurations, and documentation. There is no lock-in to CloudTopia.' }

// [slug, service, pillarKey, seoTitle, seoDesc, badge, t1, t2, subtitle, heading, statV, statT, items(3) [[t,d]x3], faqs(2) [[q,a]x2]]
const d = [
['automated-lead-qualification-sequences','Automated Lead Qualification Sequences','social-media-management','Automated Lead Qualification | CloudTopia','We build automated sequences that capture, score, and route your leads so your team only works the ones ready to buy. Free consultation.','Lead Qualification','Automated sequences that','qualify leads while you sleep','Capture, score, and route every inquiry automatically — so your team spends time only on leads that are actually ready to buy.','Stop chasing cold leads','24/7','Always-on capture',
 [['Multi-channel capture','Pull leads from forms, WhatsApp, ads, and DMs into one qualified pipeline.'],['Smart scoring rules','Score and tag leads by budget, intent, and fit so the hottest ones surface first.'],['Instant auto-routing','Send each qualified lead to the right rep or list the moment it is ready.']],
 [['What channels can you capture from?','Web forms, WhatsApp, landing pages, social DMs, and ad lead forms — unified into one qualification flow connected to the tools you already use.'],['How are leads scored?','We define rules with you based on budget, timeline, location, and intent signals, then tag each lead automatically so your team sees the best first.']]],

['custom-client-dashboards','Custom Client Dashboards','customer-experience-portals','Custom Client Dashboards | CloudTopia','We build custom client dashboards that give your customers a clear, secure view of their account, orders, and documents. Free consultation & demo.','Client Dashboards','Client dashboards that','give customers a clear view','Give every client a secure, branded dashboard for their orders, documents, requests, and status — instead of endless emails and phone calls.','A self-serve hub your clients actually use','100%','Branded to you',
 [['Tailored to your data','Surface the exact orders, invoices, tickets, and files each client needs to see.'],['Role-based access','Every user sees only what they should, with secure, permissioned logins.'],['Connected to your systems','Pulls live data from your CRM, ERP, or database so the dashboard is always current.']],
 [['Can it connect to our existing systems?','Yes — we integrate the dashboard with your CRM, ERP, accounting, or custom database via secure APIs so the data stays in sync.'],['Is the data secure?','Each client only sees their own data through permissioned logins, with encryption and audit logging built in.']]],

['secure-customer-login-portals','Secure Customer Login Portals','customer-experience-portals','Secure Customer Login Portals | CloudTopia','We build secure, branded customer login portals with role-based access so clients reach their account and documents safely. Free consultation.','Login Portals','Secure portals that','protect every customer login','Give customers a secure, branded place to log in and manage their account, documents, and requests — with the access controls your business needs.','Security and access, done right','2FA','Secure by default',
 [['Strong authentication','Email/password, 2FA, and SSO options to keep accounts protected.'],['Role-based permissions','Granular access so each user and team sees only what they should.'],['Audit & session control','Full activity logs and session management for accountability.']],
 [['What sign-in options do you support?','Email/password, two-factor authentication, magic links, and SSO — chosen to fit your security needs and your users.'],['Can different users have different access?','Yes. We set role-based permissions so customers, staff, and admins each get the right level of access.']]],

['self-service-support-hubs-and-knowledge-bases','Self-Service Support Hubs & Knowledge Bases','customer-experience-portals','Self-Service Support Hubs | CloudTopia','We build searchable self-service support hubs and knowledge bases that cut your ticket volume and answer customers instantly. Free consultation.','Support Hubs','A help center that','answers before they ask','Deflect repetitive tickets with a fast, searchable knowledge base and help center — so customers solve problems instantly and your team focuses on the hard cases.','Fewer tickets, happier customers','24/7','Self-serve answers',
 [['Searchable knowledge base','Organized articles, guides, and FAQs your customers can actually find.'],['Ticket deflection','Answer common questions automatically before they reach your inbox.'],['Easy to maintain','A simple editor so your team keeps articles current without a developer.']],
 [['Will this reduce our support load?','Yes — a well-structured, searchable knowledge base deflects the most common questions so your team handles fewer repetitive tickets.'],['Can our team update the content?','Absolutely. You get a simple editor to add and edit articles anytime, no developer needed.']]],

['interactive-booking-and-scheduling-systems','Interactive Booking & Scheduling Systems','customer-experience-portals','Interactive Booking & Scheduling | CloudTopia','We build interactive booking and scheduling systems with real-time availability, reminders, and payments — fully owned by you. Free consultation.','Booking Systems','Booking systems that','fill your calendar automatically','Let customers book appointments, services, or resources online with real-time availability, automated reminders, and optional payments.','Bookings without the back-and-forth','24/7','Online booking',
 [['Real-time availability','Live calendars prevent double-bookings across staff, rooms, or resources.'],['Automated reminders','WhatsApp, SMS, and email reminders that cut no-shows.'],['Payments & deposits','Take secure online payments or deposits at the time of booking.']],
 [['Can customers pay when booking?','Yes — we integrate payment gateways so you can collect full payment or a deposit at booking time.'],['Does it send reminders?','It sends automated WhatsApp, SMS, and email reminders to reduce no-shows and keep both sides in sync.']]],

['b2b-vendor-and-supplier-portals','B2B Vendor & Supplier Portals','customer-experience-portals','B2B Vendor & Supplier Portals | CloudTopia','We build B2B vendor and supplier portals for ordering, documents, and approvals — connected to your systems and owned by you. Free consultation.','Vendor Portals','Portals that','streamline B2B ordering','Give vendors and suppliers a secure portal to place orders, share documents, track status, and handle approvals — without the email chaos.','One place for every B2B relationship','100%','Yours to own',
 [['Self-serve ordering','Vendors place and re-order with agreed catalogs, pricing, and terms.'],['Document exchange','Share POs, invoices, and contracts securely in one auditable place.'],['Approval workflows','Route requests and approvals to the right people automatically.']],
 [['Can it handle custom pricing per vendor?','Yes — each vendor or supplier sees their own catalog, pricing, and terms, controlled from your admin.'],['Does it connect to our ERP?','We integrate the portal with your ERP or accounting system so orders and documents stay in sync.']]],

['customer-loyalty-and-rewards-dashboards','Customer Loyalty & Rewards Dashboards','customer-experience-portals','Customer Loyalty & Rewards Dashboards | CloudTopia','We build loyalty and rewards dashboards that track points, tiers, and redemptions to bring customers back. Free consultation & demo.','Loyalty & Rewards','Loyalty programs that','bring customers back','Reward repeat customers with points, tiers, and perks — tracked in a branded dashboard that drives retention and repeat purchases.','Turn one-time buyers into regulars','100%','Branded to you',
 [['Points & tiers','Flexible earning and redemption rules tailored to your business.'],['Member dashboard','Customers see their balance, tier, and rewards in one place.'],['Integrated with sales','Points sync automatically with your POS, store, or CRM.']],
 [['Can we set our own rewards rules?','Yes — earning rates, tiers, perks, and redemption rules are fully configurable to fit your business model.'],['Does it work with our store or POS?','We connect the program to your e-commerce store, POS, or CRM so points are tracked automatically.']]],

['affiliate-management-portals','Affiliate Management Portals','customer-experience-portals','Affiliate Management Portals | CloudTopia','We build affiliate management portals with tracking, dashboards, and payouts so partners drive sales for you. Free consultation & demo.','Affiliate Portals','Portals that','turn partners into a sales channel','Recruit, track, and pay affiliates from one portal — with unique links, real-time performance, and clean commission reporting.','Scale revenue through partners','100%','Yours to own',
 [['Tracked referral links','Unique links and codes that attribute every sale accurately.'],['Affiliate dashboards','Partners see clicks, conversions, and earnings in real time.'],['Commission & payouts','Automated commission rules and clear payout reporting.']],
 [['How are sales attributed to affiliates?','Each affiliate gets unique tracked links and codes, so clicks and conversions are attributed accurately with full reporting.'],['Can we set different commission rates?','Yes — commission structures can vary by affiliate, product, or tier, all managed from your admin.']]],

['warranty-and-returns-management-portals','Warranty & Returns Management Portals','customer-experience-portals','Warranty & Returns Portals | CloudTopia','We build warranty and returns portals that let customers file, track, and resolve claims — cutting support load. Free consultation & demo.','Warranty & Returns','Portals that','make returns painless','Let customers register products, file warranty claims, and request returns online — with status tracking that cuts your support load and builds trust.','Claims and returns, organized','24/7','Self-serve claims',
 [['Online claim filing','Customers register products and submit claims with photos and details.'],['Status tracking','Both sides follow each claim from request to resolution.'],['Workflow & approvals','Route, approve, and resolve claims with clear internal steps.']],
 [['Can customers track their claim?','Yes — every claim and return has a live status, so customers always know where things stand without calling support.'],['Does it connect to our inventory?','We can integrate with your inventory or ERP so approved returns and replacements update stock automatically.']]],

['seo-blog-post-and-article-writing','SEO Blog Post & Article Writing','content-marketing-authority','SEO Blog & Article Writing | CloudTopia','We write SEO blog posts and articles that rank, read well, and turn searchers into customers — in Arabic and English. Free consultation.','Blog & Articles','Articles that','rank and convert','Original, research-backed articles built around real search intent — written to rank on Google and turn readers into enquiries, not just traffic.','Content that earns rankings and trust','EN + AR','Bilingual writing',
 [['Search-intent driven','Every piece targets keywords your customers actually search for.'],['Original & accurate','Genuinely useful, fact-checked writing in your brand voice — no filler.'],['On-page SEO built in','Structured headings, internal links, and meta written to rank.']],
 [['Do you do keyword research?','Yes — we map each article to real search intent and keywords so it has a genuine chance to rank, not just fill a calendar.'],['Is the content original?','Always. Every article is written from scratch in your brand voice and fact-checked — never spun or duplicated.']]],

['website-copywriting','Website Copywriting','content-marketing-authority','Website Copywriting | CloudTopia','We write clear, persuasive website copy that explains your value and turns visitors into customers — in Arabic and English. Free consultation.','Website Copy','Website copy that','makes visitors take action','Sharp, structured copy for every page — homepage to services — that explains what you do, why it matters, and what to do next.','Words that sell, not just describe','EN + AR','Bilingual copy',
 [['Conversion-focused','Every page guides visitors toward a clear next step.'],['Structured for clarity','Headlines, sections, and CTAs that are easy to scan and act on.'],['Your voice, sharpened','Copy that sounds like you — only clearer and more persuasive.']],
 [['Which pages do you cover?','Homepage, about, services, product, and landing pages — whatever your site needs, structured and written to convert.'],['Do you write for SEO too?','Yes — copy is written for readers first and search engines second, with keywords woven in naturally.']]],

['landing-page-copywriting','Landing Page Copywriting','content-marketing-authority','Landing Page Copywriting | CloudTopia','We write high-converting landing page copy for campaigns, launches, and ads — built to win the click and the lead. Free consultation.','Landing Pages','Landing copy that','turns clicks into leads','Persuasive, single-focus landing page copy for ads, launches, and campaigns — with the message, structure, and CTA that convert paid traffic.','Make every ad click count','EN + AR','Bilingual copy',
 [['Single clear offer','One focused message and CTA so visitors know exactly what to do.'],['Built for paid traffic','Copy aligned to your ad so the click-to-page story is seamless.'],['Objection-handling','Proof, benefits, and FAQs that remove hesitation before the form.']],
 [['Do you match copy to our ads?','Yes — we align the landing page message to your ad so visitors get a seamless, high-converting experience.'],['Can you write A/B variants?','We can write multiple headline and CTA variants so you can test what converts best.']]],

['case-study-and-portfolio-writing','Case Study & Portfolio Writing','content-marketing-authority','Case Study & Portfolio Writing | CloudTopia','We write case studies and portfolio pieces that prove your results and win trust with serious buyers. Free consultation & demo.','Case Studies','Case studies that','prove your results','Turn your best projects into persuasive case studies — challenge, approach, and outcome — that give serious buyers a reason to choose you.','Show the work that wins deals','EN + AR','Bilingual writing',
 [['Story structure','Clear challenge → approach → result narratives that build credibility.'],['Outcome-focused','We frame real results in language buyers care about.'],['Interview-led','We pull the details from your team so each story rings true.']],
 [['How do you get the details?','We interview your team and review project notes, then shape an accurate, compelling story — you approve every claim before publishing.'],['Can you design the layout too?','Yes — we can pair the writing with on-brand design for the web or a downloadable PDF.']]],

['whitepaper-and-e-book-creation','Whitepaper & E-Book Creation','content-marketing-authority','Whitepaper & E-Book Creation | CloudTopia','We research, write, and design whitepapers and e-books that generate leads and position you as the authority. Free consultation.','Whitepapers','Long-form content that','positions you as the authority','Research-backed whitepapers and e-books that capture qualified leads and make your business the obvious expert in your field.','Authority content that captures leads','EN + AR','Bilingual + designed',
 [['Researched & credible','Well-structured arguments backed by real data and sources.'],['Lead-magnet ready','Built to gate behind a form and feed your pipeline.'],['Written and designed','Professional copy paired with clean, on-brand layout.']],
 [['Do you handle design as well as writing?','Yes — we deliver a finished, on-brand PDF, not just text, so it is ready to publish and gate.'],['Can it be used for lead generation?','That is the point — we structure it as a lead magnet with a landing page and form to capture qualified contacts.']]],

['email-newsletter-copywriting','Email Newsletter Copywriting','content-marketing-authority','Email Newsletter Copywriting | CloudTopia','We write email newsletters that get opened, read, and clicked — keeping your audience engaged and buying. Free consultation & demo.','Email Copy','Newsletters that','get opened and clicked','Engaging, on-brand email copy — subject lines to CTAs — that keeps your list warm and turns subscribers into repeat customers.','Email that earns the open','EN + AR','Bilingual copy',
 [['Subject lines that land','Tested, curiosity-driven lines that lift your open rates.'],['Value-first content','Emails people actually want to read, not just promotions.'],['Clear CTAs','Every send drives one obvious, measurable action.']],
 [['Do you set up the email platform too?','We can write within your existing platform (Mailchimp, Klaviyo, etc.) or help set one up and connect it to your audience.'],['How often should we send?','We help you find a sustainable cadence that keeps your list engaged without fatigue — quality over volume.']]],

['press-release-writing-and-distribution','Press Release (PR) Writing & Distribution','content-marketing-authority','Press Release Writing & Distribution | CloudTopia','We write professional press releases and distribute them to the right outlets to earn coverage and authority. Free consultation.','Press Releases','PR that','earns real coverage','Newsworthy, professionally written press releases — and distribution to the outlets that matter — so your announcements get seen and build authority.','Announcements that get picked up','EN + AR','Bilingual PR',
 [['Newsworthy angles','We shape your news into a story journalists actually want.'],['Press-standard writing','Proper structure, quotes, and boilerplate ready to publish.'],['Targeted distribution','Sent to relevant outlets and wires for maximum pickup.']],
 [['Can you guarantee coverage?','No one can honestly guarantee editorial coverage. We maximize your odds with strong, newsworthy writing and targeted distribution to the right outlets.'],['Do you write in Arabic for regional media?','Yes — we produce bilingual releases tailored for both Arabic and English outlets across the GCC.']]],

['video-scriptwriting','Video Scriptwriting','content-marketing-authority','Video Scriptwriting | CloudTopia','We write video scripts for ads, explainers, and social that hook viewers fast and drive action. Free consultation & demo.','Video Scripts','Scripts that','hook viewers in seconds','Tight, structured scripts for explainers, ads, and social video — built to grab attention in the first seconds and carry viewers to a clear action.','Words that make video work','EN + AR','Bilingual scripts',
 [['Strong hooks','Openers engineered to stop the scroll and hold attention.'],['Format-aware','Scripts shaped for Reels, TikTok, YouTube, or explainer length.'],['Action-driven','Every script ends with one clear, persuasive call to action.']],
 [['What types of video do you script?','Explainers, product and ad videos, social shorts (Reels/TikTok/Shorts), and brand films — each structured for its platform.'],['Do you provide shot or scene direction?','Yes — scripts can include scene, visual, and tone notes so production runs smoothly.']]],

['podcast-show-notes-and-structuring','Podcast Show Notes & Structuring','content-marketing-authority','Podcast Show Notes & Structuring | CloudTopia','We structure podcast episodes and write SEO show notes that grow your audience and reach. Free consultation & demo.','Podcasts','Show notes that','grow your podcast audience','Episode structuring plus SEO-friendly show notes, timestamps, and summaries that make your podcast discoverable and easy to share.','Make every episode work harder','EN + AR','Bilingual notes',
 [['Episode structuring','Clear segment outlines that keep episodes sharp and listenable.'],['SEO show notes','Summaries, keywords, and timestamps that help people find you.'],['Repurpose-ready','Notes built to spin into social posts and clips.']],
 [['What do show notes include?','A summary, key takeaways, timestamped chapters, guest details, and relevant links — written with SEO in mind.'],['Can you help repurpose episodes?','Yes — we can turn each episode into social posts, quote cards, and clip suggestions to extend its reach.']]],

['automated-review-generation-setup','Automated Review Generation Setup','review-reputation-management','Automated Review Generation | CloudTopia','We set up automated flows that ask happy customers for reviews at the right moment — growing your rating. Free consultation.','Review Generation','Systems that','grow your reviews automatically','Automatically invite happy customers to leave reviews at the perfect moment — turning good experiences into a steady stream of 5-star ratings.','Turn happy customers into reviews','Automated','Set and forget',
 [['Smart timing','Requests sent right after a positive experience, when goodwill is highest.'],['Multi-channel asks','WhatsApp, SMS, and email invitations that meet customers where they are.'],['Routed to the right place','Guide reviewers to Google, Trustpilot, or the platform you want to grow.']],
 [['How does it know when to ask?','We trigger requests off events like a completed order or service, so customers are asked when their experience is freshest.'],['Which review platforms can you target?','Google, Trustpilot, Facebook, and industry-specific sites — we route customers to wherever you want to build your rating.']]],

['google-reviews-management','Google Reviews Management','review-reputation-management','Google Reviews Management | CloudTopia','We help you earn, monitor, and respond to Google reviews to lift your local rating and trust. Free consultation & demo.','Google Reviews','Management that','lifts your Google rating','Earn more reviews, respond professionally, and monitor your Google rating — the single biggest trust signal for local customers in the GCC.','Your rating is your reputation','5-star','Rating growth',
 [['More reviews, faster','Automated, well-timed requests that grow your review count.'],['Professional responses','On-brand replies to every review that show you care.'],['Monitoring & alerts','Know the moment a new review lands, good or bad.']],
 [['Do you respond to reviews for us?','We can draft and manage responses in your voice — or set up templates and alerts so your team replies quickly and consistently.'],['Can you help remove fake reviews?','We can flag policy-violating reviews to Google for removal, though approval is always Google\'s decision.']]],

['trustpilot-and-third-party-review-management','Trustpilot & Third-Party Review Management','review-reputation-management','Trustpilot & Review Management | CloudTopia','We manage Trustpilot and third-party review profiles — collecting reviews and responding to protect your reputation. Free consultation.','Review Platforms','Management across','every review platform','Build and protect your reputation on Trustpilot and other third-party review sites — collecting reviews and responding where buyers check before they trust you.','Reputation, everywhere it matters','Multi-site','Coverage',
 [['Profile optimization','Complete, credible profiles on the platforms your buyers use.'],['Review collection','Steady invitations that build volume and recency.'],['Consistent responses','Professional replies that show accountability across every site.']],
 [['Which platforms do you cover?','Trustpilot, Google, Facebook, and industry or marketplace review sites relevant to your business.'],['Can you consolidate reviews on our site?','Yes — we can display verified reviews on your website with widgets so visitors see your reputation in one place.']]],

['online-brand-sentiment-monitoring','Online Brand Sentiment Monitoring','review-reputation-management','Brand Sentiment Monitoring | CloudTopia','We monitor what people say about your brand online and alert you to sentiment shifts before they grow. Free consultation & demo.','Sentiment Monitoring','Monitoring that','catches issues early','Track mentions, reviews, and social chatter about your brand — so you see sentiment shifts and respond before a small issue becomes a big one.','Hear what the market is saying','Real-time','Alerts',
 [['Mention tracking','Monitor reviews, social, and the web for your brand and products.'],['Sentiment signals','See whether the conversation is trending positive or negative.'],['Early alerts','Get notified of spikes so you can act fast.']],
 [['What sources do you monitor?','Review sites, social platforms, forums, and the broader web for mentions of your brand, products, and key people.'],['How quickly are we alerted?','We set up near-real-time alerts for spikes and negative sentiment so your team can respond before issues escalate.']]],

['crisis-management-and-negative-feedback-mitigation','Crisis Management & Negative Feedback Mitigation','review-reputation-management','Crisis & Feedback Management | CloudTopia','We help you respond to negative feedback and online crises calmly and effectively to protect your reputation. Free consultation.','Crisis Management','A plan that','protects you under pressure','Respond to negative reviews, complaints, and online crises with a clear, calm playbook — protecting trust when it matters most.','Stay in control when it counts','Rapid','Response',
 [['Response playbooks','Pre-agreed templates and steps so you react fast, not in panic.'],['De-escalation','Professional replies that defuse tension and move issues offline.'],['Recovery plan','Rebuild rating and sentiment after a difficult period.']],
 [['Can you respond on our behalf during a crisis?','Yes — we can manage responses in your voice with your sign-off, or coach your team in real time, depending on what you need.'],['How do you handle unfair negative reviews?','We respond professionally, flag policy violations for removal where applicable, and focus on growing genuine positive reviews to restore balance.']]],

['employer-branding-management','Employer Branding (Glassdoor, Indeed) Management','review-reputation-management','Employer Branding Management | CloudTopia','We manage your employer brand on Glassdoor and Indeed to attract talent and improve your reputation as a workplace. Free consultation.','Employer Brand','Management that','helps you attract talent','Build a strong employer reputation on Glassdoor, Indeed, and beyond — so the best candidates choose you and your hiring gets easier.','Win the talent before the interview','Talent','Attraction',
 [['Profile management','Complete, compelling employer profiles that reflect your culture.'],['Review strategy','Encourage authentic employee reviews and respond professionally.'],['Candidate trust','Present a workplace reputation that converts applicants.']],
 [['Which platforms do you manage?','Glassdoor, Indeed, LinkedIn, and other sites where candidates research employers before applying.'],['Can you respond to employee reviews?','Yes — we help craft professional, on-brand responses that show you take feedback seriously, which itself attracts better candidates.']]],

['google-analytics-setup-and-tracking','Google Analytics (GA4) Setup & Tracking','analytics-performance-reporting','GA4 Setup & Tracking | CloudTopia','We set up Google Analytics 4 with accurate event and conversion tracking so your data is trustworthy. Free consultation & demo.','GA4 Analytics','GA4 setup that','makes your data trustworthy','Proper Google Analytics 4 setup with the events, conversions, and goals that actually matter — so you make decisions on data you can trust.','Decisions need data you trust','100%','Accurate tracking',
 [['Clean GA4 setup','Correctly configured properties, streams, and data settings.'],['Event & conversion tracking','Track the actions that matter — leads, sales, signups, calls.'],['Privacy-aware','Consent and data settings handled responsibly.']],
 [['Can you migrate us from Universal Analytics?','Yes — we set up GA4 properly and rebuild the events and conversions you relied on, configured for how GA4 actually works.'],['Will tracking be accurate?','We test every event and conversion so your reports reflect reality — no guesswork or double-counting.']]],

['google-tag-manager-integration','Google Tag Manager Integration','analytics-performance-reporting','Google Tag Manager Setup | CloudTopia','We implement Google Tag Manager so you can manage tracking tags cleanly without touching code. Free consultation & demo.','Tag Manager','GTM setup that','keeps tracking clean','Implement Google Tag Manager properly so analytics, ads, and conversion tags are managed in one place — accurately, and without editing code each time.','One clean home for every tag','Centralized','Tag control',
 [['Proper container setup','A clean, organized GTM container built to scale.'],['Reliable triggers','Tags that fire exactly when they should — no missed or double events.'],['Ads & pixels ready','Google Ads, Meta, and conversion pixels wired in correctly.']],
 [['Why use GTM instead of hard-coding tags?','GTM lets you add and edit tracking without developer changes each time, reduces errors, and keeps every tag organized in one place.'],['Can you fix our messy existing container?','Yes — we audit, clean up, and restructure existing GTM setups so tags fire reliably and accurately.']]],

['custom-data-dashboards','Custom Data Dashboards (Looker Studio)','analytics-performance-reporting','Custom Data Dashboards | CloudTopia','We build custom Looker Studio dashboards that pull all your data into one clear, live view. Free consultation & demo.','Data Dashboards','Dashboards that','put your data in one view','Bring website, ads, sales, and CRM data into one live Looker Studio dashboard — so you stop exporting spreadsheets and start seeing the full picture.','See everything that matters at a glance','Live','One view',
 [['All sources, one place','Combine GA4, ads, sheets, CRM, and more into a single dashboard.'],['Built around your KPIs','We design the views around the numbers you actually decide on.'],['Always live','Auto-refreshing data — no more manual report building.']],
 [['What data sources can you connect?','GA4, Google and Meta ads, Google Sheets, your CRM, databases, and most tools with an API or connector.'],['Can each team get its own view?','Yes — we build role-specific dashboards so leadership, marketing, and sales each see what is relevant to them.']]],

['live-kpi-and-conversion-tracking','Live KPI & Conversion Tracking','analytics-performance-reporting','Live KPI & Conversion Tracking | CloudTopia','We set up live KPI and conversion tracking so you always know what is working and what is not. Free consultation.','KPI Tracking','Tracking that','shows what is working now','Define and track the KPIs and conversions that drive your business — live — so you spot what is working and fix what is not, fast.','Know your numbers in real time','Real-time','KPI clarity',
 [['The right KPIs','We define metrics that map to revenue and goals, not vanity numbers.'],['Conversion tracking','Every lead, sale, and signup tracked end to end.'],['Live visibility','Always-current numbers your whole team can see.']],
 [['Which KPIs should we track?','We work with you to choose metrics tied to revenue and goals — leads, conversion rate, cost per acquisition, retention — not vanity counts.'],['Can you track offline conversions too?','Where possible, yes — we can connect CRM or call data so offline conversions are reflected alongside online ones.']]],

['heatmap-and-user-behavior-tracking','Heatmap & User Behavior Tracking','analytics-performance-reporting','Heatmap & Behavior Tracking | CloudTopia','We set up heatmaps and session tracking to show exactly how visitors use your site — and where they drop off. Free consultation.','Behavior Tracking','Tracking that','shows how visitors really behave','See where visitors click, scroll, and drop off with heatmaps and session recordings — so you fix the real friction instead of guessing.','Watch your users, fix the friction','Visual','Behavior insight',
 [['Heatmaps','Click, scroll, and attention maps that reveal what gets noticed.'],['Session recordings','Watch real visits to see exactly where users struggle.'],['Drop-off insight','Pinpoint the steps where people abandon and why.']],
 [['What tools do you use?','Tools like Hotjar, Microsoft Clarity, or similar — set up properly and privacy-aware — chosen to fit your needs.'],['How does this help conversions?','By showing exactly where visitors hesitate or leave, you fix real problems instead of guessing — which directly lifts conversions.']]],

['conversion-rate-optimization','Conversion Rate Optimization (CRO)','analytics-performance-reporting','Conversion Rate Optimization (CRO) | CloudTopia','We run CRO audits and tests to turn more of your existing traffic into leads and sales. Free consultation & demo.','CRO','Optimization that','gets more from your traffic','Audit, test, and refine your pages and funnels so more of the visitors you already have become leads and customers — no extra ad spend needed.','More results from the same traffic','Data-led','Optimization',
 [['Funnel audit','We find exactly where visitors drop and why.'],['Prioritized tests','High-impact changes first, backed by data not opinions.'],['Measured uplift','Every change is measured so you see real gains.']],
 [['How is CRO different from just redesigning?','CRO is evidence-based — we test specific changes and measure the impact, so improvements are proven rather than assumed.'],['How long until we see results?','Quick wins often land in the first round; compounding gains come from continuous testing over time.']]],

['a-b-testing-and-multivariate-testing','A/B Testing & Multivariate Testing','analytics-performance-reporting','A/B & Multivariate Testing | CloudTopia','We run A/B and multivariate tests to find what actually converts — backed by real data. Free consultation & demo.','A/B Testing','Testing that','proves what converts','Stop guessing which version works. We design and run A/B and multivariate tests so your decisions are backed by real visitor data.','Let your visitors decide','Proven','By data',
 [['Hypothesis-driven','We test changes that are likely to move the needle, not random tweaks.'],['Statistically sound','Tests run until results are reliable — not called early.'],['Clear winners','You get a clear answer and the data behind it.']],
 [['What can we test?','Headlines, layouts, CTAs, forms, pricing presentation, page flows — anything that affects how visitors convert.'],['Do we need a lot of traffic?','Higher traffic gives faster, more reliable results; for lower traffic we focus on bigger changes and longer test windows.']]],

['monthly-digital-presence-audits','Monthly Digital Presence Audits','analytics-performance-reporting','Monthly Digital Presence Audits | CloudTopia','We deliver monthly audits of your website, SEO, and channels with clear, prioritized actions. Free consultation & demo.','Monthly Audits','Audits that','keep your digital presence sharp','A recurring health check of your website, SEO, performance, and channels — delivered as a clear, prioritized action list, not a data dump.','Always know your next move','Monthly','Clear actions',
 [['Full-stack review','Site health, SEO, speed, analytics, and channel performance in one report.'],['Prioritized actions','We tell you what to fix first and why it matters.'],['Tracked progress','Each month builds on the last so you see steady improvement.']],
 [['What does the audit cover?','Website health and speed, technical and on-page SEO, analytics accuracy, and performance across your key channels.'],['Is it just a report or do you help fix things?','You get a prioritized action list, and we can implement the fixes too — your call each month.']]],
]

let n = 0
for (const e of d) {
    const [slug, service, pillar, seoTitle, seoDesc, badge, t1, t2, subtitle, heading, statV, statT, items, faqs] = e
    const obj = {
        slug, service, pillarSlug: pillar, pillarName: PN[pillar],
        seo: { title: seoTitle, description: seoDesc },
        hero: { badge, title1: t1, title2: t2, subtitle },
        features: {
            eyebrow: 'Why CloudTopia', heading,
            stat: { value: statV, title: statT },
            items: [...items.map(([title, description]) => ({ title, description })), OWN_ITEM],
        },
        faqs: [...faqs.map(([question, answer]) => ({ question, answer })), BILINGUAL_FAQ, OWN_FAQ],
    }
    fs.writeFileSync('lib/services/dp-subs/' + slug + '.json', JSON.stringify(obj, null, 2))
    n++
}
console.log('wrote', n, 'DP files directly')
