/**
 * generate-llms.ts
 *
 * Regenerates the dynamic "Articles" section of public/llms.txt directly from
 * the production database so it can never drift from the live, published posts.
 *
 * Only the block between the `<!-- ARTICLES:START ... -->` and
 * `<!-- ARTICLES:END -->` markers is replaced; the hand-curated company /
 * services / pricing / industries / markets / FAQ sections above are left
 * untouched. All article URLs use the canonical `/articles/<slug>` (EN) and
 * `/ar/articles/<slug>` (AR) routes — never the legacy `/blog` paths.
 *
 * Usage:
 *   npx tsx scripts/generate-llms.ts          # write public/llms.txt in place
 *   npx tsx scripts/generate-llms.ts --check  # exit 1 if the file is stale
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { Client } from 'pg'
import { getDatabaseUrl, databaseRequiresSsl } from '../lib/cms/env.ts'
import { serviceDetailSlugs, servicesBySlug, serviceCategories, localizedServiceValue } from '../lib/seo/services.ts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const LLMS_PATH = path.resolve(__dirname, '../public/llms.txt')
const START_MARKER = '<!-- ARTICLES:START (regenerated by scripts/generate-llms.ts — do not edit by hand) -->'
const END_MARKER = '<!-- ARTICLES:END -->'
const SERVICES_START = '<!-- SERVICES:START (regenerated by scripts/generate-llms.ts — do not edit by hand) -->'
const SERVICES_END = '<!-- SERVICES:END -->'

const BASE = 'https://cloudtopia.net'

type Post = { title: string; slug: string; excerpt: string | null; locale: string }

// Replace the inner content between a start/end marker pair, keeping the
// markers themselves. Throws if either marker is missing so we never clobber
// the hand-curated sections.
function replaceBlock(content: string, start: string, end: string, inner: string): string {
  const startIdx = content.indexOf(start)
  const endIdx = content.indexOf(end)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`Could not find ${start} / ${end} markers in public/llms.txt — aborting to avoid clobbering the file.`)
  }
  const before = content.slice(0, startIdx)
  const after = content.slice(endIdx + end.length)
  return `${before}${start}\n${inner}\n${end}${after}`
}

// Build the full /services/<slug> detail-page index from the static service
// taxonomy so AI crawlers can enumerate every one of the 69 sub-service pages.
// Grouped by the 7 categories; ordered by serviceDetailSlugs within each.
function buildServicesBlock(): string {
  const lines: string[] = []
  lines.push(`## Service detail pages (${serviceDetailSlugs.length})`)
  lines.push('')
  lines.push('Every sub-service has its own detail page at `https://cloudtopia.net/services/<slug>` (Arabic at `/ar/services/<slug>`):')
  lines.push('')
  for (const category of serviceCategories) {
    const slugs = serviceDetailSlugs.filter((slug) => servicesBySlug[slug]?.categorySlug === category.slug)
    if (slugs.length === 0) continue
    lines.push(`### ${localizedServiceValue(category.name, 'en')}`)
    for (const slug of slugs) {
      const name = localizedServiceValue(servicesBySlug[slug].name, 'en')
      lines.push(`- ${name} — ${BASE}/services/${slug}`)
    }
    lines.push('')
  }
  return lines.join('\n').trimEnd()
}

function oneLine(value: string | null): string {
  if (!value) return ''
  return value.replace(/\s+/g, ' ').trim()
}

function renderPost(post: Post): string {
  const prefix = post.locale === 'ar' ? `${BASE}/ar/articles/` : `${BASE}/articles/`
  const url = `${prefix}${post.slug}`
  const summary = oneLine(post.excerpt)
  const line = `- ${post.title} — ${url}`
  return summary ? `${line}\n  ${summary}` : line
}

function buildArticlesBlock(en: Post[], ar: Post[]): string {
  const lines: string[] = []
  lines.push(START_MARKER)
  lines.push(`## Articles — English (${en.length} published)`)
  lines.push('')
  lines.push('All English articles live at `https://cloudtopia.net/articles/<slug>`.')
  lines.push('')
  for (const post of en) lines.push(renderPost(post))
  lines.push('')
  lines.push(`## Articles — Arabic (${ar.length} published)`)
  lines.push('')
  lines.push('All Arabic articles live at `https://cloudtopia.net/ar/articles/<slug>`.')
  lines.push('')
  for (const post of ar) lines.push(renderPost(post))
  lines.push(END_MARKER)
  return lines.join('\n')
}

async function fetchPublishedPosts(locale: 'en' | 'ar'): Promise<Post[]> {
  const databaseUrl = getDatabaseUrl()
  if (!databaseUrl) throw new Error('DATABASE_URL is not configured.')
  const client = new Client({
    connectionString: databaseUrl,
    // Remote Postgres (Supabase) requires SSL; localhost does not. Mirrors lib/cms/db.ts.
    ssl: databaseRequiresSsl() ? { rejectUnauthorized: false } : undefined,
  })
  await client.connect()
  try {
    const { rows } = await client.query<Post>(
      `SELECT title, slug, excerpt, locale
         FROM blog_posts
        WHERE status = 'published' AND locale = $1
        ORDER BY published_at DESC, slug ASC`,
      [locale],
    )
    return rows
  } finally {
    await client.end()
  }
}

async function main() {
  const checkOnly = process.argv.includes('--check')

  const [en, ar] = await Promise.all([fetchPublishedPosts('en'), fetchPublishedPosts('ar')])

  const current = fs.readFileSync(LLMS_PATH, 'utf8')
  const startIdx = current.indexOf(START_MARKER)
  const endIdx = current.indexOf(END_MARKER)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error('Could not find ARTICLES markers in public/llms.txt — aborting to avoid clobbering the file.')
  }

  const before = current.slice(0, startIdx)
  const after = current.slice(endIdx + END_MARKER.length)
  let next = before + buildArticlesBlock(en, ar) + after

  // Regenerate the static /services/<slug> detail-page index in place too.
  next = replaceBlock(next, SERVICES_START, SERVICES_END, buildServicesBlock())

  if (checkOnly) {
    if (next !== current) {
      console.error('public/llms.txt articles section is STALE. Run: npx tsx scripts/generate-llms.ts')
      process.exit(1)
    }
    console.log('public/llms.txt articles section is up to date.')
    return
  }

  if (next === current) {
    console.log(`No changes — public/llms.txt already lists ${en.length} EN + ${ar.length} AR articles.`)
    return
  }

  fs.writeFileSync(LLMS_PATH, next)
  console.log(`Updated public/llms.txt with ${en.length} EN + ${ar.length} AR articles.`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
