/**
 * Deterministic generator for `lib/services/subservice-nav-index.ts` — a
 * compact bilingual navigation index (pillar → sub-service name/description/
 * href) that client components can import WITHOUT pulling the full service
 * content databases into their bundles.
 *
 * Run: npm run generate:service-nav
 */
import { writeFileSync } from 'node:fs'
import { allStructuredPillars } from '../lib/services/structured-catalog'
import { getBusinessSystemsSubServicesByPillar } from '../lib/services/business-systems-content'
import { getDigitalPresenceSubServicesByPillar } from '../lib/services/digital-presence-content'
import { getWebApplicationsSubServicesByPillar } from '../lib/services/web-applications'

type NavItem = { slug: string; name: string; description?: string; href: string }

const slugify = (name: string) =>
    name
        .toLowerCase()
        .replace(/&/g, 'and')
        .replace(/[^a-z0-9؀-ۿ]+/g, '-')
        .replace(/^-+|-+$/g, '')

function itemsFor(pillar: (typeof allStructuredPillars)[number], locale: 'en' | 'ar'): NavItem[] {
    const bs = getBusinessSystemsSubServicesByPillar(pillar.slug, locale)
    if (bs.length > 0) {
        return bs.map((s) => ({ slug: s.slug, name: s.name, description: s.desc, href: s.href }))
    }
    const dp = getDigitalPresenceSubServicesByPillar(pillar.slug, locale)
    if (dp.length > 0) {
        return dp.map((s) => ({ slug: s.slug, name: s.name, description: s.desc, href: s.href }))
    }
    // Web-app (and structured fallback) sub-services have no standalone pages:
    // they navigate to their parent pillar. Slugs derive from the English name
    // so both locales stay aligned.
    const waEn = getWebApplicationsSubServicesByPillar(pillar.slug, 'en')
    if (waEn.length > 0) {
        const waLoc = getWebApplicationsSubServicesByPillar(pillar.slug, locale)
        return waEn.map((en, i) => ({
            slug: slugify(en.name),
            name: waLoc[i]?.name ?? en.name,
            ...(waLoc[i]?.desc ? { description: waLoc[i].desc } : {}),
            href: pillar.href,
        }))
    }
    const fallback = (pillar as { subServices?: string[] }).subServices ?? []
    return fallback.map((name) => ({ slug: slugify(name), name, href: pillar.href }))
}

const index: Record<string, { en: NavItem[]; ar: NavItem[] }> = {}
for (const pillar of [...allStructuredPillars].sort((a, b) => a.slug.localeCompare(b.slug))) {
    const en = itemsFor(pillar, 'en')
    const ar = itemsFor(pillar, 'ar')
    if (en.length === 0) continue
    index[pillar.slug] = { en, ar }
}

const body = JSON.stringify(index, null, 2)

const output = `// AUTO-GENERATED by scripts/generate-subservice-nav-index.ts — do not edit by hand.
// Regenerate with: npm run generate:service-nav
import type { Locale } from '@/lib/i18n/config'

export type SubserviceNavItem = { slug: string; name: string; description?: string; href: string }

const INDEX: Record<string, { en: SubserviceNavItem[]; ar: SubserviceNavItem[] }> = ${body}

export function getSubserviceNavItems(pillarSlug: string, locale: Locale, limit?: number): readonly SubserviceNavItem[] {
    const entry = INDEX[pillarSlug]
    if (!entry) return []
    const items = locale === 'ar' ? entry.ar : entry.en
    return typeof limit === 'number' ? items.slice(0, limit) : items
}
`

writeFileSync('lib/services/subservice-nav-index.ts', output)
console.log(`generated lib/services/subservice-nav-index.ts (${Object.keys(index).length} pillars)`)
