import {
  defineIndustryWorld,
  type IndustryWorldConfig,
  type LocalizedCopy,
} from '@/lib/industries/definitions/define-industry-world'

const t = (en: string, ar: string): LocalizedCopy => ({ en, ar })

const configurations = [
  {
    slug: 'fintech',
    worldId: 'trust-ledger',
    worldName: t('Trust Ledger', 'سجل الثقة'),
    signatureId: 'trust-boundary-map',
    signatureName: t('Trust boundary map', 'خريطة حدود الثقة'),
    signatureCarrier: 'constraints',
    heroScene: 'fintech-ledger',
    heroTreatment: 'route-field',
    theme: {
      canvas: '#071A22', surface: '#0E2831', elevatedSurface: '#173640',
      ink: '#F4FBFA', mutedInk: '#B7D3D4', accent: '#27C7A8',
      accentInk: '#071A22', signal: '#38BDF8', line: '#42646D', focus: '#38BDF8',
      displayTreatment: 'technical', radiusMode: 'square', motifDensity: 'dense', sceneTreatment: 'route-field',
    },
    eyebrow: t('Financial product systems', 'أنظمة المنتجات المالية'),
    promise: t('Build trust into every financial step.', 'ابنوا الثقة في كل خطوة مالية.'),
    sceneSummary: t(
      'Identity, consent, account decisions, transactions, and exceptions stay visible on one controlled event rail.',
      'تبقى الهوية والموافقة وقرارات الحساب والمعاملات والاستثناءات مرئية على مسار أحداث منضبط واحد.',
    ),
    stages: [
      { id: 'consent', label: t('Discover and consent', 'الاكتشاف والموافقة'), state: t('Declared', 'معلنة') },
      { id: 'identity', label: t('Identity review', 'التحقق من الهوية'), state: t('Reviewed', 'قيد المراجعة') },
      { id: 'decision', label: t('Account decision', 'قرار تفعيل الحساب'), state: t('Owned', 'بمالك واضح') },
      { id: 'transaction', label: t('Transaction', 'المعاملة'), state: t('Recorded', 'مسجلة') },
      { id: 'exception', label: t('Exception and audit', 'الاستثناء والتدقيق'), state: t('Traceable', 'قابلة للتتبع') },
    ],
    primaryCta: t('Map your onboarding and transaction flow', 'لنرسم رحلة العميل من التسجيل إلى المعاملة'),
    secondaryCta: t('Explore FinTech system paths', 'استكشفوا مسارات أنظمة التقنية المالية'),
    primaryService: 'web-applications',
    guardrails: [
      t('Compliance-related capabilities support an approved process; they do not certify or authorize it.', 'القدرات المرتبطة بالامتثال تدعم عملية معتمدة ولا تمنح اعتماداً أو ترخيصاً.'),
      t('Identity, consent, and transaction records require explicit ownership, retention, and access rules.', 'تتطلب سجلات الهوية والموافقة والمعاملات قواعد صريحة للملكية والاحتفاظ والصلاحيات.'),
      t('Payment and verification integrations remain dependent on validated provider access and market availability.', 'تبقى تكاملات الدفع والتحقق معتمدة على وصول موثوق للمزود وتوفره في السوق.'),
    ],
    extraFaqs: [
      { question: t('How should exception queues be scoped?', 'كيف نحدد نطاق قوائم الاستثناءات؟'), answer: t('Start with named exception types, owners, evidence requirements, and a documented return path to the main journey.', 'ابدؤوا بأنواع استثناءات محددة ومالكين ومتطلبات إثبات ومسار موثق للعودة إلى الرحلة الأساسية.') },
      { question: t('Can the product explain financial decisions clearly?', 'هل يمكن للمنتج شرح القرارات المالية بوضوح؟'), answer: t('Yes. Decision states, required actions, and approved explanations can be designed into each customer and operator view.', 'نعم. يمكن تصميم حالات القرار والإجراءات المطلوبة والتفسيرات المعتمدة ضمن واجهات العميل وفريق التشغيل.') },
    ],
    rhythm: {
      pressure: 'dense-ledger', journey: 'dual-lane', system: 'constellation',
      services: 'route-links', constraints: 'boundary-map', regional: 'market-path',
      faq: 'grouped-questions', close: 'split-close',
    },
    order: ['constraints', 'pressure', 'journey', 'system', 'evidence', 'services', 'regional', 'faq', 'close'],
  },
  {
    slug: 'ecommerce-retail',
    worldId: 'catalog-rush',
    worldName: t('Catalog Rush', 'حركة الكتالوج'),
    signatureId: 'bilingual-product-shelf',
    signatureName: t('The bilingual product shelf', 'رف المنتجات ثنائي اللغة'),
    signatureCarrier: 'sequence',
    heroScene: 'ecommerce-catalog',
    heroTreatment: 'editorial-pass',
    theme: {
      canvas: '#121012', surface: '#211A1E', elevatedSurface: '#33252B',
      ink: '#FFF8F3', mutedInk: '#D8BEC9', accent: '#E84B91',
      accentInk: '#121012', signal: '#F59E42', line: '#76515F', focus: '#F59E42',
      displayTreatment: 'editorial', radiusMode: 'cut', motifDensity: 'dense', sceneTreatment: 'service-pass',
    },
    eyebrow: t('E-commerce operating systems', 'أنظمة التجارة الإلكترونية'),
    promise: t('Turn product discovery into a faster path to purchase.', 'حوّلوا اكتشاف المنتجات إلى مسار شراء أسرع.'),
    sceneSummary: t(
      'A bilingual product shelf accelerates into cart, payment, fulfillment, and the next customer relationship.',
      'ينتقل رف منتجات ثنائي اللغة بسرعة إلى السلة والدفع والتجهيز والعلاقة التالية مع العميل.',
    ),
    stages: [
      { id: 'discover', label: t('Discover', 'الاكتشاف'), state: t('Relevant', 'ملائم') },
      { id: 'choose', label: t('Choose a product', 'اختيار المنتج'), state: t('Comparable', 'قابل للمقارنة') },
      { id: 'checkout', label: t('Cart and checkout', 'السلة والدفع'), state: t('Confirmed', 'مؤكد') },
      { id: 'fulfillment', label: t('Fulfillment', 'التجهيز والتوصيل'), state: t('Trackable', 'قابل للتتبع') },
      { id: 'return', label: t('Return journey', 'الشراء المتكرر'), state: t('Retained', 'مستمر') },
    ],
    primaryCta: t('Plan your commerce journey', 'خطّطوا لمسار التجارة الإلكترونية'),
    secondaryCta: t('Explore commerce build paths', 'استكشفوا مسارات بناء التجارة'),
    primaryService: 'ecommerce-development',
    guardrails: [
      t('Prices, tax presentation, product details, and availability must come from operator-approved sources.', 'يجب أن تأتي الأسعار وعرض الضريبة وتفاصيل المنتجات والتوفر من مصادر يعتمدها المشغل.'),
      t('Payment and shipping options depend on validated gateway, carrier, and market access.', 'تعتمد خيارات الدفع والشحن على وصول موثوق لبوابات الدفع وشركات التوصيل والسوق.'),
      t('Returns and stock exceptions need visible states, owners, and customer communication.', 'تحتاج استثناءات الإرجاع والمخزون إلى حالات مرئية ومالكين وتواصل واضح مع العميل.'),
    ],
    extraFaqs: [
      { question: t('How should a bilingual catalog be structured?', 'كيف يُنظم كتالوج ثنائي اللغة؟'), answer: t('Product names, options, pricing context, media, and search terms are authored and checked independently in Arabic and English.', 'تُصاغ أسماء المنتجات والخيارات وسياق السعر والوسائط وعبارات البحث وتُراجع بشكل مستقل بالعربية والإنجليزية.') },
      { question: t('Where should commerce automation begin?', 'من أين تبدأ أتمتة التجارة؟'), answer: t('Begin where customers or operators lose the most context: catalog updates, checkout recovery, fulfillment status, or repeat-purchase communication.', 'ابدؤوا عند أكثر نقطة يفقد فيها العميل أو الفريق السياق: تحديث الكتالوج أو استعادة الدفع أو حالة التجهيز أو تواصل الشراء المتكرر.') },
    ],
    rhythm: {
      pressure: 'split-signal', journey: 'linear-route', sequence: 'operating-matrix',
      system: 'service-line', services: 'capability-stack', constraints: 'boundary-map',
      regional: 'bilingual-operations', faq: 'editorial-list', close: 'framed-close',
    },
    order: ['journey', 'sequence', 'pressure', 'system', 'services', 'constraints', 'regional', 'faq', 'close'],
  },
  {
    slug: 'real-estate',
    worldId: 'spatial-registry',
    worldName: t('Spatial Registry', 'السجل المكاني'),
    signatureId: 'plot-to-prospect',
    signatureName: t('From plot to prospect', 'من الموقع إلى العميل المحتمل'),
    signatureCarrier: 'system',
    heroScene: 'real-estate-registry',
    heroTreatment: 'route-field',
    theme: {
      canvas: '#F2EFE7', surface: '#FFFCF6', elevatedSurface: '#E5DFD1',
      ink: '#173F35', mutedInk: '#48665E', accent: '#8D4C31',
      accentInk: '#FFFFFF', signal: '#5F7F91', line: '#A89F8C', focus: '#8D4C31',
      displayTreatment: 'technical', radiusMode: 'square', motifDensity: 'quiet', sceneTreatment: 'route-field',
    },
    eyebrow: t('Property discovery systems', 'أنظمة الرحلة العقارية'),
    promise: t('Move property seekers from interest to viewing with clarity.', 'رحلة عقارية أوضح من البحث إلى المعاينة.'),
    sceneSummary: t(
      'Location, development, unit, qualification, and agent handoff sit in one readable property registry.',
      'يجمع سجل عقاري واضح الموقع والمشروع والوحدة وتأهيل الاهتمام والتسليم للوسيط.',
    ),
    stages: [
      { id: 'explore', label: t('Explore the project', 'استكشاف المشروع'), state: t('Located', 'محدد') },
      { id: 'compare', label: t('Filter and compare', 'التصفية والمقارنة'), state: t('Comparable', 'قابل للمقارنة') },
      { id: 'qualify', label: t('Qualify interest', 'تأهيل الاهتمام'), state: t('Qualified', 'مؤهل') },
      { id: 'viewing', label: t('Book a viewing', 'حجز المعاينة'), state: t('Scheduled', 'مجدول') },
      { id: 'handoff', label: t('Agent handoff', 'التسليم للوسيط'), state: t('Owned', 'بمالك واضح') },
    ],
    primaryCta: t('Design your property journey', 'صمّموا رحلة عقارية أوضح'),
    secondaryCta: t('Explore property platform paths', 'استكشفوا مسارات المنصات العقارية'),
    primaryService: 'website-development',
    guardrails: [
      t('Availability, pricing, ownership, and disclosure data must come from approved property sources.', 'يجب أن تأتي بيانات التوفر والأسعار والملكية والإفصاحات من مصادر عقارية معتمدة.'),
      t('Maps, floor plans, and media need explicit rights, version ownership, and update responsibility.', 'تحتاج الخرائط والمخططات والوسائط إلى حقوق صريحة وملكية للإصدار ومسؤولية للتحديث.'),
      t('Lead routing must preserve inquiry context and expose the receiving agent and next action.', 'يجب أن يحافظ توجيه العميل المحتمل على سياق الاستفسار ويظهر الوسيط المستلم والخطوة التالية.'),
    ],
    extraFaqs: [
      { question: t('Can a property journey work without live inventory?', 'هل تعمل الرحلة العقارية دون مخزون مباشر؟'), answer: t('Yes. The first release can present approved projects and qualify interest, while live availability remains clearly labeled until an integration is validated.', 'نعم. يمكن للإصدار الأول عرض المشاريع المعتمدة وتأهيل الاهتمام، مع توضيح أن التوفر ليس مباشراً حتى يتم اعتماد التكامل.') },
      { question: t('How are agents connected to qualified inquiries?', 'كيف تُربط الاستفسارات المؤهلة بالوسطاء؟'), answer: t('Rules can route by project, location, language, budget, or availability while preserving the full inquiry history.', 'يمكن لقواعد التوجيه الاعتماد على المشروع أو الموقع أو اللغة أو الميزانية أو التوفر مع حفظ سجل الاستفسار كاملاً.') },
    ],
    rhythm: {
      pressure: 'split-signal', journey: 'linear-route', system: 'stacked-layers',
      services: 'route-links', constraints: 'boundary-map', regional: 'market-path',
      faq: 'grouped-questions', close: 'framed-close',
    },
    order: ['pressure', 'journey', 'system', 'evidence', 'services', 'constraints', 'regional', 'faq', 'close'],
  },
  {
    slug: 'education',
    worldId: 'learning-constellation',
    worldName: t('Learning Constellation', 'كوكبة التعلّم'),
    signatureId: 'one-journey-many-roles',
    signatureName: t('One journey, many roles', 'رحلة واحدة، أدوار متعددة'),
    signatureCarrier: 'signature-journey',
    heroScene: 'education-constellation',
    heroTreatment: 'corridor-split',
    theme: {
      canvas: '#F8F2DF', surface: '#FFFDF6', elevatedSurface: '#EDE3C5',
      ink: '#14213D', mutedInk: '#4E5871', accent: '#445FAE',
      accentInk: '#FFFFFF', signal: '#D79A18', line: '#AFA582', focus: '#445FAE',
      displayTreatment: 'editorial', radiusMode: 'soft', motifDensity: 'medium', sceneTreatment: 'pulse-corridor',
    },
    eyebrow: t('Learning and enrollment systems', 'أنظمة التعلّم والتسجيل'),
    promise: t('Connect enrollment, learning, and achievement.', 'اربطوا التسجيل بالتعلّم والإنجاز.'),
    sceneSummary: t(
      'Learner milestones connect discovery, enrollment, learning, assessment, and completion while every supporting role stays visible.',
      'تربط مراحل المتعلم الاكتشاف والتسجيل والتعلّم والتقييم والإتمام مع إبقاء كل دور مساند مرئياً.',
    ),
    stages: [
      { id: 'discover', label: t('Discover a program', 'اكتشاف البرنامج'), state: t('Understood', 'مفهوم') },
      { id: 'enroll', label: t('Apply and enroll', 'التقديم والتسجيل'), state: t('Confirmed', 'مؤكد') },
      { id: 'learn', label: t('Learn', 'التعلّم'), state: t('Active', 'نشط') },
      { id: 'assess', label: t('Assess progress', 'تقييم التقدّم'), state: t('Visible', 'مرئي') },
      { id: 'complete', label: t('Complete', 'الإتمام'), state: t('Recorded', 'مسجل') },
    ],
    primaryCta: t('Map your learning experience', 'لنرسم تجربة التعلّم لديكم'),
    secondaryCta: t('Explore education platform paths', 'استكشفوا مسارات منصات التعليم'),
    primaryService: 'web-applications',
    guardrails: [
      t('Accreditation, certification, and learning-outcome wording requires institution-approved evidence.', 'تتطلب صياغة الاعتماد والشهادات ونتائج التعلّم أدلة تعتمدها المؤسسة.'),
      t('Learner, guardian, instructor, and administrator access must be defined separately.', 'يجب تحديد صلاحيات المتعلم وولي الأمر والمدرب والإدارة كل على حدة.'),
      t('Assessment and completion states require clear ownership and correction paths.', 'تحتاج حالات التقييم والإتمام إلى ملكية واضحة ومسارات للتصحيح.'),
    ],
    extraFaqs: [
      { question: t('How do multiple education roles share one journey?', 'كيف تشترك أدوار التعليم المتعددة في رحلة واحدة؟'), answer: t('The journey keeps shared milestones consistent while each role receives only its tasks, evidence, and permitted views.', 'تحافظ الرحلة على مراحل مشتركة متسقة، بينما يتلقى كل دور مهامه وأدلته وواجهاته المصرح بها فقط.') },
      { question: t('Can enrollment launch before a full learning platform?', 'هل يمكن إطلاق التسجيل قبل منصة تعلّم كاملة؟'), answer: t('Yes. Discovery, application, document collection, and status communication can launch first, then connect to the learning layer.', 'نعم. يمكن إطلاق الاكتشاف والتقديم وجمع المستندات وتواصل الحالة أولاً ثم ربطها بطبقة التعلّم.') },
    ],
    rhythm: {
      pressure: 'split-signal', journey: 'linear-route', signatureJourney: 'dual-lane',
      system: 'constellation', services: 'capability-stack', constraints: 'boundary-map',
      regional: 'bilingual-operations', faq: 'grouped-questions', close: 'split-close',
    },
    evidenceCarrier: 'evidence',
    order: ['journey', 'signature-journey', 'pressure', 'system', 'evidence', 'services', 'regional', 'faq', 'close'],
  },
  {
    slug: 'travel-hospitality',
    worldId: 'guest-journey-atlas',
    worldName: t('Guest Journey Atlas', 'أطلس رحلة الضيف'),
    signatureId: 'guest-horizon',
    signatureName: t('The guest horizon', 'أفق رحلة الضيف'),
    signatureCarrier: 'signature-journey',
    heroScene: 'travel-itinerary',
    heroTreatment: 'editorial-pass',
    theme: {
      canvas: '#F7F0E3', surface: '#FFF9F0', elevatedSurface: '#DCEBE8',
      ink: '#083A5B', mutedInk: '#476475', accent: '#176B7B',
      accentInk: '#FFFFFF', signal: '#E86F4A', line: '#91A9A7', focus: '#E86F4A',
      displayTreatment: 'editorial', radiusMode: 'soft', motifDensity: 'medium', sceneTreatment: 'service-pass',
    },
    eyebrow: t('Guest experience systems', 'أنظمة تجربة الضيف'),
    promise: t('Connect every guest moment, before and beyond the stay.', 'اربطوا كل لحظة في رحلة الضيف قبل الإقامة وما بعدها.'),
    sceneSummary: t(
      'The guest-facing itinerary and the operating layer move together from inspiration to booking, stay, and return.',
      'يتحرك مسار الضيف وطبقة التشغيل معاً من الإلهام إلى الحجز والإقامة والعودة.',
    ),
    stages: [
      { id: 'inspire', label: t('Inspire', 'الإلهام والاكتشاف'), state: t('Desired', 'مرغوب') },
      { id: 'availability', label: t('Check availability', 'التحقق من التوفر'), state: t('Current', 'محدث') },
      { id: 'booking', label: t('Book and confirm', 'الحجز والتأكيد'), state: t('Confirmed', 'مؤكد') },
      { id: 'stay', label: t('Arrive and stay', 'الوصول والإقامة'), state: t('Supported', 'مدعوم') },
      { id: 'return', label: t('Return', 'العودة والولاء'), state: t('Remembered', 'محفوظ') },
    ],
    primaryCta: t('Shape your guest journey', 'صمّموا رحلة ضيوفكم'),
    secondaryCta: t('Explore hospitality build paths', 'استكشفوا مسارات بناء الضيافة'),
    primaryService: 'website-development',
    guardrails: [
      t('Rates, packages, availability, and booking status depend on approved property or provider data.', 'تعتمد الأسعار والباقات والتوفر وحالة الحجز على بيانات معتمدة من المنشأة أو المزود.'),
      t('Property-system and payment connections require validated access before live promises are shown.', 'تتطلب تكاملات أنظمة المنشأة والدفع وصولاً موثوقاً قبل عرض وعود مباشرة.'),
      t('Pre-arrival and stay communication needs consent, timing ownership, and a staffed recovery path.', 'يحتاج تواصل ما قبل الوصول وأثناء الإقامة إلى موافقة وملكية للتوقيت ومسار معالجة يديره الفريق.'),
    ],
    extraFaqs: [
      { question: t('What should sit above and below the guest horizon?', 'ما الذي يظهر فوق أفق الضيف وتحته؟'), answer: t('Guests see inspiration, choices, confirmation, and support; teams coordinate availability, property data, payment, and communication below that line.', 'يرى الضيف الإلهام والخيارات والتأكيد والدعم، بينما تنسق الفرق التوفر وبيانات المنشأة والدفع والتواصل تحت هذا الخط.') },
      { question: t('Can the journey begin with inquiry instead of instant booking?', 'هل يمكن أن تبدأ الرحلة بالاستفسار بدلاً من الحجز الفوري؟'), answer: t('Yes. Inquiry, request-to-book, and direct booking are different states that can share one clear itinerary.', 'نعم. الاستفسار وطلب الحجز والحجز المباشر حالات مختلفة يمكن أن تشترك في مسار واضح واحد.') },
    ],
    rhythm: {
      pressure: 'constraints-first', journey: 'linear-route', signatureJourney: 'dual-lane',
      system: 'service-line', services: 'route-links', constraints: 'owner-register',
      regional: 'market-path', faq: 'editorial-list', close: 'framed-close',
    },
    order: ['journey', 'signature-journey', 'pressure', 'system', 'constraints', 'services', 'regional', 'faq', 'close'],
  },
  {
    slug: 'legal-firms',
    worldId: 'case-docket',
    worldName: t('Case Docket', 'سجل القضية'),
    signatureId: 'confidential-threshold',
    signatureName: t('The confidential threshold', 'عتبة السرية'),
    signatureCarrier: 'constraints',
    heroScene: 'legal-docket',
    heroTreatment: 'editorial-pass',
    theme: {
      canvas: '#F4EBDD', surface: '#FFF9EF', elevatedSurface: '#E4D5C0',
      ink: '#231C1D', mutedInk: '#625153', accent: '#4A1620',
      accentInk: '#FFFFFF', signal: '#9B672D', line: '#B49A79', focus: '#4A1620',
      displayTreatment: 'editorial', radiusMode: 'cut', motifDensity: 'quiet', sceneTreatment: 'service-pass',
    },
    eyebrow: t('Legal client intake systems', 'أنظمة استقبال عملاء المكاتب القانونية'),
    promise: t('Make the first legal conversation clear and confidential.', 'اجعلوا أول تواصل قانوني واضحاً وسرياً.'),
    sceneSummary: t(
      'Public practice information, pre-engagement intake, and authenticated matter communication remain visibly separated.',
      'تبقى معلومات الممارسة العامة والاستقبال قبل الارتباط وتواصل القضية الموثق منفصلة بوضوح.',
    ),
    stages: [
      { id: 'practice', label: t('Find the practice', 'تحديد مجال الممارسة'), state: t('Public', 'عام') },
      { id: 'suitability', label: t('Initial suitability check', 'التحقق الأولي من الملاءمة'), state: t('Screened', 'مفحوص') },
      { id: 'intake', label: t('Confidential intake', 'استقبال المعلومات والمستندات'), state: t('Controlled', 'منضبط') },
      { id: 'consultation', label: t('Consultation decision', 'قرار الاستشارة'), state: t('Decided', 'محسوم') },
      { id: 'matter', label: t('Matter communication', 'تواصل القضية'), state: t('Authenticated', 'موثق') },
    ],
    primaryCta: t('Review your legal client intake', 'راجعوا مسار استقبال العملاء القانوني'),
    secondaryCta: t('Explore legal system paths', 'استكشفوا مسارات الأنظمة القانونية'),
    primaryService: 'website-development',
    guardrails: [
      t('Public information, pre-engagement intake, and authenticated matter communication require separate boundaries.', 'تتطلب المعلومات العامة والاستقبال قبل الارتباط وتواصل القضية الموثق حدوداً منفصلة.'),
      t('Intake wording needs legal review and must not create advice, outcome, or relationship promises.', 'تحتاج صياغة الاستقبال إلى مراجعة قانونية ويجب ألا تنشئ وعداً باستشارة أو نتيجة أو علاقة مهنية.'),
      t('Documents and matter updates require project-defined roles, retention rules, and escalation ownership.', 'تتطلب المستندات وتحديثات القضية أدواراً محددة للمشروع وقواعد احتفاظ وملكية للتصعيد.'),
    ],
    extraFaqs: [
      { question: t('Where does confidential intake begin?', 'أين يبدأ استقبال المعلومات السرية؟'), answer: t('The page must mark the boundary between public qualification and the approved channel used for confidential details and documents.', 'يجب أن توضح الصفحة الحد بين التأهيل العام والقناة المعتمدة لاستقبال التفاصيل والمستندات السرية.') },
      { question: t('Can a legal portal imply an attorney-client relationship?', 'هل يمكن للبوابة القانونية أن توحي بقيام علاقة مهنية؟'), answer: t('No. Status, consent, and engagement wording must be approved by the firm and remain explicit throughout the journey.', 'لا. يجب أن تعتمد المنشأة صياغة الحالة والموافقة والارتباط وأن تبقى صريحة طوال الرحلة.') },
    ],
    rhythm: {
      pressure: 'constraints-first', journey: 'linear-route', system: 'stacked-layers',
      services: 'route-links', constraints: 'boundary-map', regional: 'bilingual-operations',
      faq: 'grouped-questions', close: 'split-close',
    },
    order: ['constraints', 'journey', 'pressure', 'system', 'evidence', 'services', 'regional', 'faq', 'close'],
  },
  {
    slug: 'construction',
    worldId: 'site-sequence',
    worldName: t('Site Sequence', 'تسلسل المشروع'),
    signatureId: 'decision-latency',
    signatureName: t('Decision latency', 'زمن انتظار القرار'),
    signatureCarrier: 'journey',
    heroScene: 'construction-sequence',
    heroTreatment: 'route-field',
    theme: {
      canvas: '#ECECE8', surface: '#F9F9F5', elevatedSurface: '#DCE5E9',
      ink: '#132A3A', mutedInk: '#4A5B66', accent: '#246A9A',
      accentInk: '#FFFFFF', signal: '#E96128', line: '#8196A3', focus: '#E96128',
      displayTreatment: 'technical', radiusMode: 'square', motifDensity: 'dense', sceneTreatment: 'route-field',
    },
    eyebrow: t('Project delivery systems', 'أنظمة إدارة رحلة المشروع'),
    promise: t('Keep every project decision visible and moving.', 'اجعلوا مسار كل قرار في المشروع واضحاً ومتحركاً.'),
    sceneSummary: t(
      'Tender, RFI, approval, supply, and milestone states expose who owns each decision and what waits behind it.',
      'تكشف حالات المناقصة وطلب المعلومات والاعتماد والتوريد والمراحل من يملك كل قرار وما ينتظر خلفه.',
    ),
    stages: [
      { id: 'tender', label: t('Prequalify and tender', 'التأهيل والمناقصة'), state: t('Open', 'مفتوح') },
      { id: 'rfi', label: t('RFI and submittal', 'طلب المعلومات والتقديم'), state: t('Submitted', 'مقدم') },
      { id: 'approval', label: t('Review and approve', 'المراجعة والاعتماد'), state: t('Waiting', 'بانتظار القرار') },
      { id: 'supply', label: t('Supply and execute', 'التوريد والتنفيذ'), state: t('Released', 'محرر') },
      { id: 'milestone', label: t('Milestone and report', 'المرحلة والتقرير'), state: t('Recorded', 'مسجل') },
    ],
    primaryCta: t('Map your construction project workflow', 'لنرسم سير عمل مشاريع الإنشاء لديكم'),
    secondaryCta: t('Explore construction system paths', 'استكشفوا مسارات أنظمة الإنشاء'),
    primaryService: 'business-systems-development',
    guardrails: [
      t('Project status, safety, certification, and contractual data must come from permissioned sources.', 'يجب أن تأتي حالة المشروع وبيانات السلامة والشهادات والعقود من مصادر مصرح بها.'),
      t('Every RFI, submittal, approval, and supplier handoff needs a named owner and dated state.', 'يحتاج كل طلب معلومات وتقديم واعتماد وتسليم للمورد إلى مالك محدد وحالة مؤرخة.'),
      t('The system records decisions and evidence; it does not imply engineering or contractual authority.', 'يسجل النظام القرارات والأدلة ولا يوحي بسلطة هندسية أو تعاقدية.'),
    ],
    extraFaqs: [
      { question: t('How is decision latency made visible?', 'كيف يظهر زمن انتظار القرار؟'), answer: t('Each waiting state shows its owner, required evidence, due context, and downstream work that cannot proceed.', 'تعرض كل حالة انتظار مالكها والأدلة المطلوبة وسياق الموعد والعمل اللاحق الذي لا يمكنه التقدم.') },
      { question: t('Can supplier and client views stay separate?', 'هل يمكن فصل واجهات المورد والعميل؟'), answer: t('Yes. Role-based views can expose only the packages, documents, approvals, and milestones each party is permitted to see.', 'نعم. يمكن للواجهات حسب الدور إظهار الحزم والمستندات والاعتمادات والمراحل المسموح لكل طرف برؤيتها فقط.') },
    ],
    rhythm: {
      pressure: 'dense-ledger', journey: 'exception-lane', sequence: 'numbered-flow',
      system: 'service-line', services: 'capability-stack', constraints: 'boundary-map',
      regional: 'market-path', faq: 'editorial-list', close: 'split-close',
    },
    order: ['pressure', 'journey', 'sequence', 'system', 'evidence', 'services', 'constraints', 'regional', 'faq', 'close'],
  },
  {
    slug: 'retail',
    worldId: 'store-pulse',
    worldName: t('Store Pulse', 'نبض المتجر'),
    signatureId: 'one-customer-many-shelves',
    signatureName: t('One customer, many shelves', 'عميل واحد، قنوات بيع متعددة'),
    signatureCarrier: 'sequence',
    heroScene: 'retail-pulse',
    heroTreatment: 'editorial-pass',
    theme: {
      canvas: '#FCF8F2', surface: '#FFFFFF', elevatedSurface: '#F0E8ED',
      ink: '#36143F', mutedInk: '#6A4C70', accent: '#9B3D91',
      accentInk: '#FFFFFF', signal: '#A7C92A', line: '#B99CB7', focus: '#9B3D91',
      displayTreatment: 'editorial', radiusMode: 'cut', motifDensity: 'medium', sceneTreatment: 'service-pass',
    },
    eyebrow: t('Omnichannel retail systems', 'أنظمة التجزئة متعددة القنوات'),
    promise: t('Connect the shelf, the branch, and the customer.', 'اربطوا الرف والفرع والعميل في تجربة واحدة.'),
    sceneSummary: t(
      'Branch, shelf, POS, collection, support, and loyalty moments pulse around one continuous customer identity.',
      'تتحرك لحظات الفرع والرف ونقطة البيع والاستلام والدعم والولاء حول هوية عميل واحدة ومستمرة.',
    ),
    stages: [
      { id: 'discover', label: t('Discover a branch or product', 'اكتشاف الفرع أو المنتج'), state: t('Found', 'موجود') },
      { id: 'stock', label: t('Check stock and offer', 'التحقق من المخزون والعرض'), state: t('Current', 'محدث') },
      { id: 'buy', label: t('Buy or reserve', 'الشراء أو الحجز'), state: t('Committed', 'مؤكد') },
      { id: 'collect', label: t('Collect or receive service', 'الاستلام أو الخدمة'), state: t('Fulfilled', 'منفذ') },
      { id: 'loyalty', label: t('Loyalty and support', 'الولاء والدعم'), state: t('Connected', 'متصل') },
    ],
    primaryCta: t('Connect your retail store journey', 'اربطوا رحلة متاجركم'),
    secondaryCta: t('Explore omnichannel retail paths', 'استكشفوا مسارات التجزئة متعددة القنوات'),
    primaryService: 'ecommerce-development',
    guardrails: [
      t('Inventory, branch hours, offers, and reservation states depend on disciplined source-system updates.', 'تعتمد حالات المخزون وساعات الفروع والعروض والحجوزات على تحديث منضبط في أنظمة المصدر.'),
      t('POS, web, campaign, and loyalty identities need explicit matching and consent rules.', 'تحتاج هويات نقطة البيع والويب والحملات والولاء إلى قواعد صريحة للمطابقة والموافقة.'),
      t('Collection and service exceptions require a visible branch owner and a customer recovery path.', 'تحتاج استثناءات الاستلام والخدمة إلى مالك واضح في الفرع ومسار لمعالجة تجربة العميل.'),
    ],
    extraFaqs: [
      { question: t('How are physical and digital shelves connected?', 'كيف يرتبط الرف الفعلي بالرف الرقمي؟'), answer: t('A shared product and branch model links catalog content, stock context, campaigns, reservation, collection, and support.', 'يربط نموذج مشترك للمنتج والفرع محتوى الكتالوج وسياق المخزون والحملات والحجز والاستلام والدعم.') },
      { question: t('Should online-first retail use the commerce journey?', 'هل تستخدم التجزئة الرقمية أولاً رحلة التجارة الإلكترونية؟'), answer: t('Yes. Online-first catalog, checkout, and fulfillment needs should connect to the E-commerce world while branch-led operations stay here.', 'نعم. ترتبط احتياجات الكتالوج والدفع والتجهيز الرقمية أولاً بعالم التجارة الإلكترونية، بينما تبقى عمليات الفروع هنا.') },
    ],
    rhythm: {
      pressure: 'dense-ledger', journey: 'linear-route', sequence: 'operating-matrix',
      system: 'constellation', services: 'capability-stack', constraints: 'owner-register',
      regional: 'market-path', faq: 'grouped-questions', close: 'framed-close',
    },
    order: ['journey', 'sequence', 'pressure', 'system', 'services', 'constraints', 'regional', 'faq', 'close'],
  },
  {
    slug: 'professional-services',
    worldId: 'expertise-architecture',
    worldName: t('Expertise Architecture', 'هندسة الخبرة'),
    signatureId: 'expertise-model',
    signatureName: t('The expertise model', 'نموذج الخبرة'),
    signatureCarrier: 'system',
    heroScene: 'expertise-architecture',
    heroTreatment: 'editorial-pass',
    theme: {
      canvas: '#F7F4EC', surface: '#FFFFFF', elevatedSurface: '#E7ECF6',
      ink: '#101828', mutedInk: '#4B5568', accent: '#1B57D0',
      accentInk: '#FFFFFF', signal: '#7184B4', line: '#9CAAC7', focus: '#1B57D0',
      displayTreatment: 'editorial', radiusMode: 'square', motifDensity: 'quiet', sceneTreatment: 'pulse-corridor',
    },
    eyebrow: t('Expert-led service systems', 'أنظمة شركات الخدمات المهنية'),
    promise: t('Turn expertise into a clear client journey.', 'حوّلوا خبراتكم إلى رحلة عميل واضحة ومفهومة.'),
    sceneSummary: t(
      'Diagnosis, offer design, proposal, delivery, and reporting become visible bays in one expertise architecture.',
      'تتحول مراحل التشخيص وصياغة العرض والمقترح والتنفيذ والتقرير إلى وحدات مرئية في هندسة خبرة واحدة.',
    ),
    stages: [
      { id: 'diagnose', label: t('Diagnose the need', 'تشخيص الاحتياج'), state: t('Framed', 'محدد') },
      { id: 'shape', label: t('Shape the offer', 'صياغة العرض'), state: t('Packaged', 'مصاغ') },
      { id: 'propose', label: t('Propose and approve', 'العرض والاعتماد'), state: t('Agreed', 'متفق') },
      { id: 'deliver', label: t('Deliver and review', 'التنفيذ والمراجعة'), state: t('Visible', 'مرئي') },
      { id: 'report', label: t('Report and expand', 'التقرير والتوسّع'), state: t('Learned', 'موثق') },
    ],
    primaryCta: t('Structure your professional client journey', 'نظّموا رحلة عملائكم المهنية'),
    secondaryCta: t('Explore expertise system paths', 'استكشفوا مسارات أنظمة الخبرة'),
    primaryService: 'website-development',
    guardrails: [
      t('Expertise, credentials, outcomes, and ROI wording require approved, project-specific evidence.', 'تتطلب صياغة الخبرة والمؤهلات والنتائج والعائد أدلة معتمدة خاصة بالمشروع.'),
      t('Diagnosis, proposal, approval, delivery, and reporting need explicit client and team ownership.', 'تحتاج مراحل التشخيص والمقترح والاعتماد والتنفيذ والتقرير إلى ملكية صريحة للعميل والفريق.'),
      t('Client portals must separate firm knowledge, client material, permissions, and retention rules.', 'يجب أن تفصل بوابات العملاء بين معرفة الشركة ومواد العميل والصلاحيات وقواعد الاحتفاظ.'),
    ],
    extraFaqs: [
      { question: t('How does expertise become easier to buy?', 'كيف تصبح الخبرة أسهل في الشراء؟'), answer: t('The site makes the problem, diagnostic approach, deliverables, decisions, boundaries, and next step visible before a proposal.', 'يوضح الموقع المشكلة ومنهج التشخيص والمخرجات والقرارات والحدود والخطوة التالية قبل تقديم المقترح.') },
      { question: t('Can delivery reporting connect back to sales?', 'هل يمكن ربط تقارير التنفيذ بالمبيعات؟'), answer: t('Yes. Approved milestones, feedback, and expansion signals can flow into account planning without exposing restricted client material.', 'نعم. يمكن للمراحل المعتمدة والملاحظات وإشارات التوسع أن تنتقل إلى تخطيط الحساب دون كشف مواد العميل المقيدة.') },
    ],
    rhythm: {
      pressure: 'split-signal', journey: 'linear-route', system: 'service-line',
      services: 'route-links', constraints: 'owner-register', regional: 'bilingual-operations',
      faq: 'editorial-list', close: 'split-close',
    },
    evidenceCarrier: 'evidence',
    order: ['system', 'pressure', 'journey', 'evidence', 'services', 'constraints', 'regional', 'faq', 'close'],
  },
  {
    slug: 'government-public-sector',
    worldId: 'public-service-standard',
    worldName: t('Public Service Standard', 'معيار الخدمة العامة'),
    signatureId: 'service-standard',
    signatureName: t('The service standard', 'معيار الخدمة'),
    signatureCarrier: 'evidence',
    heroScene: 'public-service-standard',
    heroTreatment: 'corridor-split',
    theme: {
      canvas: '#F4F8F7', surface: '#FFFFFF', elevatedSurface: '#E1EFEC',
      ink: '#12304B', mutedInk: '#4B6374', accent: '#087867',
      accentInk: '#FFFFFF', signal: '#3178C6', line: '#8BA9A4', focus: '#3178C6',
      displayTreatment: 'technical', radiusMode: 'soft', motifDensity: 'quiet', sceneTreatment: 'pulse-corridor',
    },
    eyebrow: t('Public service systems', 'أنظمة الخدمات العامة'),
    promise: t('Make public services clearer for people and easier to operate.', 'اجعلوا الخدمات العامة أوضح للناس وأسهل في التشغيل.'),
    sceneSummary: t(
      'Eligibility, application, documents, case ownership, assistance, and completion form one calm, accessible civic pathway.',
      'تشكل الأهلية والتقديم والمستندات وملكية المعاملة والمساعدة والإتمام مسار خدمة عامة هادئاً وسهل الوصول.',
    ),
    stages: [
      { id: 'eligibility', label: t('Find service and eligibility', 'العثور على الخدمة والأهلية'), state: t('Clear', 'واضح') },
      { id: 'apply', label: t('Apply and submit documents', 'التقديم وإرفاق المستندات'), state: t('Received', 'مستلم') },
      { id: 'route', label: t('Route to a case owner', 'توجيه المعاملة للمسؤول'), state: t('Owned', 'بمالك واضح') },
      { id: 'track', label: t('Track and request assistance', 'متابعة الحالة وطلب المساعدة'), state: t('Visible', 'مرئي') },
      { id: 'complete', label: t('Decision and completion', 'القرار وإتمام الخدمة'), state: t('Recorded', 'مسجل') },
    ],
    primaryCta: t('Review a public service journey', 'راجعوا رحلة إحدى خدماتكم العامة'),
    secondaryCta: t('Explore public service system paths', 'استكشفوا مسارات أنظمة الخدمة العامة'),
    primaryService: 'web-applications',
    guardrails: [
      t('Policy, eligibility, identity, data residency, and service decisions remain owned by the responsible authority.', 'تبقى السياسات والأهلية والهوية وإقامة البيانات وقرارات الخدمة تحت ملكية الجهة المسؤولة.'),
      t('Accessibility, language, assisted service, and procurement requirements must be validated for each program.', 'يجب اعتماد متطلبات سهولة الوصول واللغة والخدمة المساندة والمشتريات لكل برنامج.'),
      t('The experience must not imply a government mandate, client, clearance, or guaranteed compliance.', 'يجب ألا توحي التجربة بتكليف حكومي أو عميل أو تصريح أو امتثال مضمون.'),
    ],
    extraFaqs: [
      { question: t('What does the public service standard review?', 'ما الذي يراجعه معيار الخدمة العامة؟'), answer: t('It reviews clarity, accessibility, language, status visibility, ownership, evidence, and assisted-service paths across one service.', 'يراجع الوضوح وسهولة الوصول واللغة وظهور الحالة والملكية والأدلة ومسارات الخدمة المساندة ضمن خدمة واحدة.') },
      { question: t('Can one service path launch before a full portal?', 'هل يمكن إطلاق مسار خدمة واحد قبل بوابة كاملة؟'), answer: t('Yes. A priority service can launch with clear eligibility, application, status, and assistance, then expand through validated modules.', 'نعم. يمكن إطلاق خدمة ذات أولوية بأهلية وتقديم وحالة ومساعدة واضحة، ثم توسيعها عبر وحدات معتمدة.') },
    ],
    rhythm: {
      pressure: 'constraints-first', journey: 'linear-route', system: 'constellation',
      services: 'capability-stack', constraints: 'boundary-map', regional: 'bilingual-operations',
      faq: 'grouped-questions', close: 'framed-close',
    },
    evidenceCarrier: 'evidence',
    order: ['evidence', 'journey', 'pressure', 'system', 'constraints', 'services', 'regional', 'faq', 'close'],
  },
] as const satisfies readonly IndustryWorldConfig[]

const definitions = Object.fromEntries(
  configurations.map((configuration) => [
    configuration.slug,
    defineIndustryWorld(configuration),
  ]),
) as Record<(typeof configurations)[number]['slug'], ReturnType<typeof defineIndustryWorld>>

export const fintechDefinition = definitions.fintech
export const ecommerceRetailDefinition = definitions['ecommerce-retail']
export const realEstateDefinition = definitions['real-estate']
export const educationDefinition = definitions.education
export const travelHospitalityDefinition = definitions['travel-hospitality']
export const legalFirmsDefinition = definitions['legal-firms']
export const constructionDefinition = definitions.construction
export const retailDefinition = definitions.retail
export const professionalServicesDefinition = definitions['professional-services']
export const governmentPublicSectorDefinition = definitions['government-public-sector']
